using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BMC.Reports
{
    public class clsResourceParams
    {
        public string OddRowColor { get; set; }
        public string EvenRowColor { get; set; }
        public string Key_RC_ActivatedBy { get; set; }
        public string Key_RC_ActivationDate { get; set; }
        public string Key_RC_ActPerc { get; set; }
        public string Key_RC_ActPercentage { get; set; }
        public string Key_RC_Actual { get; set; }
        public string Key_RC_ActualAssetNumber { get; set; }
        public string Key_RC_ActualAverageNetWinOrNumberOfSlot { get; set; }
        public string Key_RC_ActualHold { get; set; }
        public string Key_RC_ActualHoldPercentage { get; set; }
        public string Key_RC_ActualSerialNumber { get; set; }
        public string Key_RC_ActualTheoVarPercentage { get; set; }
        public string Key_RC_ActualTotal { get; set; }
        public string Key_RC_ActualTreasuryDate { get; set; }
        public string Key_RC_ActualWinPerDay { get; set; }
        public string Key_RC_ActWinPercentage { get; set; }
        public string Key_RC_AdjustmentAmount { get; set; }
        public string Key_RC_AdvancetoRetailer { get; set; }
        public string Key_RC_AfterImage { get; set; }
        public string Key_RC_AlertLevel { get; set; }
        public string Key_RC_AltSerialNo { get; set; }
        public string Key_RC_Amount { get; set; }
        public string Key_RC_AmountFilled { get; set; }
        public string Key_RC_Area { get; set; }
        public string Key_RC_Asset { get; set; }
        public string Key_RC_AssetAndPosition { get; set; }
        public string Key_RC_AssetGameTitle { get; set; }
        public string Key_RC_AssetNo { get; set; }
        public string Key_RC_AssetNumber { get; set; }
        public string Key_RC_AssetOrMachine { get; set; }
        public string Key_RC_Assets { get; set; }
        public string Key_RC_AssignedEmployee { get; set; }
        public string Key_RC_AssignedSiteCode { get; set; }
        public string Key_RC_AssignedSiteID { get; set; }
        public string Key_RC_AttendantPay { get; set; }
        public string Key_RC_AttendantPayOrJackpot { get; set; }
        public string Key_RC_Attendantpays { get; set; }
        public string Key_RC_AttendantPays { get; set; }
        public string Key_RC_AttendantPayVar { get; set; }
        public string Key_RC_AttendantPDCancelledCredits { get; set; }
        public string Key_RC_AttendantPDJackpot { get; set; }
        public string Key_RC_AttendantVar { get; set; }
        public string Key_RC_AttendanyPay { get; set; }
        public string Key_RC_AttnPay { get; set; }
        public string Key_RC_AttnPayProg { get; set; }
        public string Key_RC_AttnPayProgVar { get; set; }
        public string Key_RC_AttnPayVar { get; set; }
        public string Key_RC_AttractDowntime { get; set; }
        public string Key_RC_AuditDate { get; set; }
        public string Key_RC_AuditDateTime { get; set; }
        public string Key_RC_AuditField { get; set; }
        public string Key_RC_AuditID { get; set; }
        public string Key_RC_AuditNewVl { get; set; }
        public string Key_RC_AuditOldVl { get; set; }
        public string Key_RC_AuditUserID { get; set; }
        public string Key_RC_AverageBet { get; set; }
        public string Key_RC_AverageBetOrNumberOfSlot { get; set; }
        public string Key_RC_AverageNet { get; set; }
        public string Key_RC_AverageNetPerc { get; set; }
        public string Key_RC_AverageWin { get; set; }
        public string Key_RC_AvgBet { get; set; }
        public string Key_RC_AvgBetsOrHP { get; set; }
        public string Key_RC_AvgCIPDPM { get; set; }
        public string Key_RC_AvgDailyWin { get; set; }
        public string Key_RC_AvgNet { get; set; }
        public string Key_RC_AvgWin { get; set; }
        public string Key_RC_AvgWinPDPM { get; set; }
        public string Key_RC_BalanceDue { get; set; }
        public string Key_RC_BarPositionName { get; set; }
        public string Key_RC_BarPositionNumber { get; set; }
        public string Key_RC_BatchName { get; set; }
        public string Key_RC_BatchNo { get; set; }
        public string Key_RC_BeforeImage { get; set; }
        public string Key_RC_Bet { get; set; }
        public string Key_RC_Bets { get; set; }
        public string Key_RC_BetsPerDay { get; set; }
        public string Key_RC_Bill1 { get; set; }
        public string Key_RC_Bill10 { get; set; }
        public string Key_RC_Bill100 { get; set; }
        public string Key_RC_Bill2 { get; set; }
        public string Key_RC_Bill20 { get; set; }
        public string Key_RC_Bill5 { get; set; }
        public string Key_RC_Bill50 { get; set; }
        public string Key_RC_Bills { get; set; }
        public string Key_RC_BillsAndTicketCount { get; set; }
        public string Key_RC_BillsIn { get; set; }
        public string Key_RC_BillsVar { get; set; }
        public string Key_RC_BillTotal { get; set; }
        public string Key_RC_BleedAmount { get; set; }
        public string Key_RC_Bleeds { get; set; }
        public string Key_RC_BMCTotal { get; set; }
        public string Key_RC_BMCValue { get; set; }
        public string Key_RC_BMCVariance { get; set; }
        public string Key_RC_CalculatedNetWin { get; set; }
        public string Key_RC_CancelledBy { get; set; }
        public string Key_RC_CancelledDate { get; set; }
        public string Key_RC_Capacity { get; set; }
        public string Key_RC_CardNumber { get; set; }
        public string Key_RC_CardStatus { get; set; }
        public string Key_RC_CardType { get; set; }
        public string Key_RC_CarriedForward { get; set; }
        public string Key_RC_CarriedForwardExpense { get; set; }
        public string Key_RC_CarryForward { get; set; }
        public string Key_RC_CarryForwardExpense { get; set; }
        public string Key_RC_Cashable { get; set; }
        public string Key_RC_CashableAmt { get; set; }
        public string Key_RC_CashableEPromoIn { get; set; }
        public string Key_RC_CashableEPromoOut { get; set; }
        public string Key_RC_CashableIn { get; set; }
        public string Key_RC_CashableNet { get; set; }
        public string Key_RC_CashableOut { get; set; }
        public string Key_RC_CashableProm { get; set; }
        public string Key_RC_CashCollected10000p { get; set; }
        public string Key_RC_CashCollected1000p { get; set; }
        public string Key_RC_CashCollected100p { get; set; }
        public string Key_RC_CashCollected2000p { get; set; }
        public string Key_RC_CashCollected5000p { get; set; }
        public string Key_RC_CashCollected500p { get; set; }
        public string Key_RC_CashDeskCoins { get; set; }
        public string Key_RC_CashDeskMovement { get; set; }
        public string Key_RC_CashdeskResultReport { get; set; }
        public string Key_RC_CashIn { get; set; }
        public string Key_RC_CashOut { get; set; }
        public string Key_RC_CasinoWin { get; set; }
        public string Key_RC_CassetteHopperName { get; set; }
        public string Key_RC_CassetteOrHopperBalance { get; set; }
        public string Key_RC_CassetteOrHopperName { get; set; }
        public string Key_RC_Category { get; set; }
        public string Key_RC_CDCoins { get; set; }
        public string Key_RC_CDCVouchersQty { get; set; }
        public string Key_RC_CDCVouchersValue { get; set; }
        public string Key_RC_CEPromoIn { get; set; }
        public string Key_RC_CEPromoOut { get; set; }
        public string Key_RC_ChangeField { get; set; }
        public string Key_RC_ChangeTime { get; set; }
        public string Key_RC_CIOrUOrD { get; set; }
        public string Key_RC_claimedincashdeskqty { get; set; }
        public string Key_RC_claimedincashdeskValue { get; set; }
        public string Key_RC_ClaimedVouchers { get; set; }
        public string Key_RC_Code { get; set; }
        public string Key_RC_Coin { get; set; }
        public string Key_RC_CoinIn { get; set; }
        public string Key_RC_Coins { get; set; }
        public string Key_RC_CoinsIn { get; set; }
        public string Key_RC_CoinsOut { get; set; }
        public string Key_RC_CoinVar { get; set; }
        public string Key_RC_CollectionNoHourMGMDSessionNo { get; set; }
        public string Key_RC_CollectionOtherShare { get; set; }
        public string Key_RC_Collector { get; set; }
        public string Key_RC_Comments { get; set; }
        public string Key_RC_Cost { get; set; }
        public string Key_RC_Count { get; set; }
        public string Key_RC_CPromoIn { get; set; }
        public string Key_RC_CPromoOut { get; set; }
        public string Key_RC_CreatedBy { get; set; }
        public string Key_RC_CreatedOn { get; set; }
        public string Key_RC_CreationDate { get; set; }
        public string Key_RC_Current { get; set; }
        public string Key_RC_CurrentBalance { get; set; }
        public string Key_RC_CurrentInventory { get; set; }
        public string Key_RC_CurrentStatus { get; set; }
        public string Key_RC_CurrSymbol10 { get; set; }
        public string Key_RC_CurrSymbol100 { get; set; }
        public string Key_RC_CurrSymbol20 { get; set; }
        public string Key_RC_CurrSymbol5 { get; set; }
        public string Key_RC_CurrSymbol50 { get; set; }
        public string Key_RC_CVoucherIn { get; set; }
        public string Key_RC_CVoucherOut { get; set; }
        public string Key_RC_DailyWin { get; set; }
        public string Key_RC_Date { get; set; }
        public string Key_RC_DateTime { get; set; }
        public string Key_RC_Days { get; set; }
        public string Key_RC_DaysOn { get; set; }
        public string Key_RC_DaysRemaining { get; set; }
        public string Key_RC_DeclarationDateTime { get; set; }
        public string Key_RC_DeclaredDateTime { get; set; }
        public string Key_RC_DeclaredTotal { get; set; }
        public string Key_RC_DeclaredUser { get; set; }
        public string Key_RC_Denom { get; set; }
        public string Key_RC_Depot { get; set; }
        public string Key_RC_DepPerWeek { get; set; }
        public string Key_RC_Description { get; set; }
        public string Key_RC_Difference { get; set; }
        public string Key_RC_DiffToCD { get; set; }
        public string Key_RC_DiffToWL { get; set; }
        public string Key_RC_Drop { get; set; }
        public string Key_RC_DropAmount { get; set; }
        public string Key_RC_DropArea { get; set; }
        public string Key_RC_DropBalance { get; set; }
        public string Key_RC_DropDateTime { get; set; }
        public string Key_RC_DropeFunds { get; set; }
        public string Key_RC_DropId { get; set; }
        public string Key_RC_DropNumber { get; set; }
        public string Key_RC_DropPeriod { get; set; }
        public string Key_RC_ECashEnabled { get; set; }
        public string Key_RC_EffectiveDate { get; set; }
        public string Key_RC_EFTIn { get; set; }
        public string Key_RC_EftInVar { get; set; }
        public string Key_RC_EFTOut { get; set; }
        public string Key_RC_EftOutVar { get; set; }
        public string Key_RC_EmployeeName { get; set; }
        public string Key_RC_EndDate { get; set; }
        public string Key_RC_EndMeter { get; set; }
        public string Key_RC_Engineer { get; set; }
        public string Key_RC_EnrollmentStatus { get; set; }
        public string Key_RC_ErrorCode { get; set; }
        public string Key_RC_ErrorMessage { get; set; }
        public string Key_RC_EventDescription { get; set; }
        public string Key_RC_EventID { get; set; }
        public string Key_RC_EventType { get; set; }
        public string Key_RC_ExpenseAmount { get; set; }
        public string Key_RC_ExpenseeFunds { get; set; }
        public string Key_RC_ExpenseShare { get; set; }
        public string Key_RC_Expired { get; set; }
        public string Key_RC_ExpiredAmt { get; set; }
        public string Key_RC_ExpiredCalendars { get; set; }
        public string Key_RC_ExpiredDateTime { get; set; }
        public string Key_RC_ExpiredYearEnd { get; set; }
        public string Key_RC_ExpiredYearStart { get; set; }
        public string Key_RC_ExpiryDate { get; set; }
        public string Key_RC_ExpiryDateTime { get; set; }
        public string Key_RC_FillAmount { get; set; }
        public string Key_RC_Fills { get; set; }
        public string Key_RC_FirstName { get; set; }
        public string Key_RC_FirstNameInbox { get; set; }
        public string Key_RC_FixedExpense { get; set; }
        public string Key_RC_For { get; set; }
        public string Key_RC_FromSite { get; set; }
        public string Key_RC_FromSiteCode { get; set; }
        public string Key_RC_Game { get; set; }
        public string Key_RC_GameCategoryName { get; set; }
        public string Key_RC_GameCode { get; set; }
        public string Key_RC_GameName { get; set; }
        public string Key_RC_GameSequenceNumber { get; set; }
        public string Key_RC_GamesPlayed { get; set; }
        public string Key_RC_GameTitle { get; set; }
        public string Key_RC_GamingDay { get; set; }
        public string Key_RC_GMUNumber { get; set; }
        public string Key_RC_GPS { get; set; }
        public string Key_RC_GrandTotal { get; set; }
        public string Key_RC_Gross { get; set; }
        public string Key_RC_GrossCoin { get; set; }
        public string Key_RC_GrossMetersIn { get; set; }
        public string Key_RC_Handle { get; set; }
        public string Key_RC_HandlePulls { get; set; }
        public string Key_RC_Handpay { get; set; }
        public string Key_RC_HandPayOrJackpot { get; set; }
        public string Key_RC_Handpays { get; set; }
        public string Key_RC_InstallationEndDate { get; set; }
        public string Key_RC_InstallationDays { get; set; }
        public string Key_RC_TotalCMPShare { get; set; }
        public string Key_RC_InstallationNo { get; set; }
        public string Key_RC_InstallDays { get; set; }
        public string Key_RC_InventoryLevel { get; set; }
        public string Key_RC_InventoryLimit { get; set; }
        public string Key_RC_InventoryMethod { get; set; }
        public string Key_RC_IsMasterCard { get; set; }
        public string Key_RC_IssueDateTime { get; set; }
        public string Key_RC_IssueInformation { get; set; }
        public string Key_RC_Jackpot { get; set; }
        public string Key_RC_JackpotType { get; set; }
        public string Key_RC_JackpotWinValue { get; set; }
        public string Key_RC_JP { get; set; }
        public string Key_RC_JPPerDay { get; set; }
        public string Key_RC_LastDropDate { get; set; }
        public string Key_RC_LastModifedOn { get; set; }
        public string Key_RC_LastName { get; set; }
        public string Key_RC_LastUpdated { get; set; }
        public string Key_RC_Liability { get; set; }
        public string Key_RC_LicenseKey { get; set; }
        public string Key_RC_LicenseNumber { get; set; }
        public string Key_RC_LicenseStatus { get; set; }
        public string Key_RC_LiquidationDate { get; set; }
        public string Key_RC_Machine { get; set; }
        public string Key_RC_MachineCallinMachineDays { get; set; }
        public string Key_RC_MachineMovement { get; set; }
        public string Key_RC_MachineName { get; set; }
        public string Key_RC_MachineStockNumber { get; set; }
        public string Key_RC_MachineWinLoss { get; set; }
        public string Key_RC_Manager { get; set; }
        public string Key_RC_ManualAP { get; set; }
        public string Key_RC_ManualJP { get; set; }
        public string Key_RC_ManualProg { get; set; }
        public string Key_RC_Manufacturer { get; set; }
        public string Key_RC_ManufacturerType { get; set; }
        public string Key_RC_Meter { get; set; }
        public string Key_RC_MeterDelta { get; set; }
        public string Key_RC_MeterDrop { get; set; }
        public string Key_RC_Model { get; set; }
        public string Key_RC_Module { get; set; }
        public string Key_RC_Name { get; set; }
        public string Key_RC_NBV { get; set; }
        public string Key_RC_NCEPromoIn { get; set; }
        public string Key_RC_NCEPromoOut { get; set; }
        public string Key_RC_NCePromoOut { get; set; }
        public string Key_RC_NCOut { get; set; }
        public string Key_RC_NCPromoIn { get; set; }
        public string Key_RC_NCPromoOut { get; set; }
        public string Key_RC_NCVoucherIn { get; set; }
        public string Key_RC_NCVoucherOut { get; set; }
        public string Key_RC_NCVouchersIn { get; set; }
        public string Key_RC_NCVouchersOut { get; set; }
        public string Key_RC_Net { get; set; }
        public string Key_RC_NetCoin { get; set; }
        public string Key_RC_NetWin { get; set; }
        public string Key_RC_NetWinLoss { get; set; }
        public string Key_RC_NewValue { get; set; }
        public string Key_RC_NonCashable { get; set; }
        public string Key_RC_NonCashableAmt { get; set; }
        public string Key_RC_NonCashableEPromoeFundsOut { get; set; }
        public string Key_RC_NonCashableEPromoIn { get; set; }
        public string Key_RC_NonCashableProm { get; set; }
        public string Key_RC_NonCashableVoucherOut { get; set; }
        public string Key_RC_Notes { get; set; }
        public string Key_RC_NoteVar { get; set; }
        public string Key_RC_NumberofCassettes { get; set; }
        public string Key_RC_NumberofCoinHoppers { get; set; }
        public string Key_RC_NumberofDaysOnline { get; set; }
        public string Key_RC_NumberofEnrollment { get; set; }
        public string Key_RC_NumberOfSlot { get; set; }
        public string Key_RC_NumberofVouchers { get; set; }
        public string Key_RC_NumberOfVouchersExpired { get; set; }
        public string Key_RC_NumberOfVouchersRedeemed { get; set; }
        public string Key_RC_NumberOfVouchersVoided { get; set; }
        public string Key_RC_OldValue { get; set; }
        public string Key_RC_Operation { get; set; }
        public string Key_RC_OperationType { get; set; }
        public string Key_RC_Operator { get; set; }
        public string Key_RC_Other { get; set; }
        public string Key_RC_Others { get; set; }
        public string Key_RC_OverallVar { get; set; }
        public string Key_RC_PaidAP { get; set; }
        public string Key_RC_PaidAsset { get; set; }
        public string Key_RC_PaidDate { get; set; }
        public string Key_RC_PaidJP { get; set; }
        public string Key_RC_PaidPosition { get; set; }
        public string Key_RC_PaidProg { get; set; }
        public string Key_RC_PayoutDescription { get; set; }
        public string Key_RC_PayoutPercent { get; set; }
        public string Key_RC_PayoutPercentAct { get; set; }
        public string Key_RC_PayoutPercentVar { get; set; }
        public string Key_RC_PayoutPercetTheo { get; set; }
        public string Key_RC_PayPeriod { get; set; }
        public string Key_RC_Paytable { get; set; }
        public string Key_RC_PaytableCount { get; set; }
        public string Key_RC_PaytableDescription { get; set; }
        public string Key_RC_PaytableID { get; set; }
        public string Key_RC_PercentageShare { get; set; }
        public string Key_RC_PercVar { get; set; }
        public string Key_RC_Period { get; set; }
        public string Key_RC_PeriodDep { get; set; }
        public string Key_RC_PeriodEnd { get; set; }
        public string Key_RC_PersonelNo { get; set; }
        public string Key_RC_PlayerID { get; set; }
        public string Key_RC_Plays { get; set; }
        public string Key_RC_Pos { get; set; }
        public string Key_RC_Position { get; set; }
        public string Key_RC_PositionOrAssetNo { get; set; }
        public string Key_RC_PosName { get; set; }
        public string Key_RC_PosOrAsset { get; set; }
        public string Key_RC_PostCode { get; set; }
        public string Key_RC_Previous { get; set; }
        public string Key_RC_PrintAsset { get; set; }
        public string Key_RC_PrintedAssets { get; set; }
        public string Key_RC_PrintedDate { get; set; }
        public string Key_RC_PrintPosition { get; set; }
        public string Key_RC_ProcessedDate { get; set; }
        public string Key_RC_ProcessedTime { get; set; }
        public string Key_RC_ProcessType { get; set; }
        public string Key_RC_Prog { get; set; }
        public string Key_RC_Progressive { get; set; }
        public string Key_RC_ProgressiveJackpot { get; set; }
        public string Key_RC_ProgressiveValueDeclared { get; set; }
        public string Key_RC_PromoCashable { get; set; }
        public string Key_RC_PromoCashableIn { get; set; }
        public string Key_RC_PromoCashableNet { get; set; }
        public string Key_RC_PromoCashableOut { get; set; }
        public string Key_RC_PromoCIn { get; set; }
        public string Key_RC_PromoNCIn { get; set; }
        public string Key_RC_Purchased { get; set; }
        public string Key_RC_Qty { get; set; }
        public string Key_RC_QtyDrops { get; set; }
        public string Key_RC_ReceivedDateTime { get; set; }
        public string Key_RC_RedeemDateTime { get; set; }
        public string Key_RC_RedeemedAmt { get; set; }
        public string Key_RC_RedemptionExpiryVoidedInformation { get; set; }
        public string Key_RC_RedemptionInformation { get; set; }
        public string Key_RC_Reference { get; set; }
        public string Key_RC_Refills { get; set; }
        public string Key_RC_Refunds { get; set; }
        public string Key_RC_Region { get; set; }
        public string Key_RC_ReleasedByEmpName { get; set; }
        public string Key_RC_ReleasedByPlayerOrEmp { get; set; }
        public string Key_RC_ReleasedDateTime { get; set; }
        public string Key_RC_ReportTotalCashIn { get; set; }
        public string Key_RC_ReservedByEmpName { get; set; }
        public string Key_RC_ReservedByPlayerOrEmp { get; set; }
        public string Key_RC_ReservedDateTime { get; set; }
        public string Key_RC_ReservedForPlayer { get; set; }
        public string Key_RC_ResponseInHrs { get; set; }
        public string Key_RC_Result { get; set; }
        public string Key_RC_RetailerName { get; set; }
        public string Key_RC_RetailerNetRevenue { get; set; }
        public string Key_RC_RetailerShareafterNegativeNet { get; set; }
        public string Key_RC_RetailerShareBeforeAdjustment { get; set; }
        public string Key_RC_RetailersNegativeNetPriorCollection { get; set; }
        public string Key_RC_RetailersNegativeNetPriorRead { get; set; }
        public string Key_RC_RetailersShareBeforeFixedExpenses { get; set; }
        public string Key_RC_RouteName { get; set; }
        public string Key_RC_RuleName { get; set; }
        public string Key_RC_ScreenName { get; set; }
        public string Key_RC_Seq { get; set; }
        public string Key_RC_Sequence { get; set; }
        public string Key_RC_SerialNo { get; set; }
        public string Key_RC_SessionDuration { get; set; }
        public string Key_RC_SessionEnd { get; set; }
        public string Key_RC_SessionStart { get; set; }
        public string Key_RC_ShareHolderName { get; set; }
        public string Key_RC_ShortPay { get; set; }
        public string Key_RC_Shortpay { get; set; }
        public string Key_RC_Shortpays { get; set; }
        public string Key_RC_Signature { get; set; }
        public string Key_RC_SiteAddress { get; set; }
        public string Key_RC_SiteCallinSiteDays { get; set; }
        public string Key_RC_SiteCode { get; set; }
        public string Key_RC_SiteID { get; set; }
        public string Key_RC_SiteName { get; set; }
        public string Key_RC_SlipAmount { get; set; }
        public string Key_RC_SLOT { get; set; }
        public string Key_RC_SlotHoldPercentage { get; set; }
        public string Key_RC_Source { get; set; }
        public string Key_RC_SrNo { get; set; }
        public string Key_RC_StackerLevelPercentage { get; set; }
        public string Key_RC_StaffFirstName { get; set; }
        public string Key_RC_StaffLastName { get; set; }
        public string Key_RC_Stand { get; set; }
        public string Key_RC_StartDate { get; set; }
        public string Key_RC_StartMeter { get; set; }
        public string Key_RC_Status { get; set; }
        public string Key_RC_StockStatus { get; set; }
        public string Key_RC_SummaryFlashReport { get; set; }
        public string Key_RC_Telephone { get; set; }
        public string Key_RC_TheoAvgNetWinOrSlot { get; set; }
        public string Key_RC_TheoHold { get; set; }
        public string Key_RC_TheoHoldPercentage { get; set; }
        public string Key_RC_TheoPerc { get; set; }
        public string Key_RC_TheoPercentage { get; set; }
        public string Key_RC_TheoreticalHold { get; set; }
        public string Key_RC_TheoreticalWin { get; set; }
        public string Key_RC_TheoWin { get; set; }
        public string Key_RC_TheoWinPerDay { get; set; }
        public string Key_RC_TicketsExpected { get; set; }
        public string Key_RC_TicketsExpectedMetersOut { get; set; }
        public string Key_RC_TicketsPaid { get; set; }
        public string Key_RC_TicketType { get; set; }
        public string Key_RC_To { get; set; }
        public string Key_RC_ToSite { get; set; }
        public string Key_RC_ToSiteCode { get; set; }
        public string Key_RC_ToSiteID { get; set; }
        public string Key_RC_Total { get; set; }
        public string Key_RC_TotalAmount { get; set; }
        public string Key_RC_TotalBet { get; set; }
        public string Key_RC_TotalBills { get; set; }
        public string Key_RC_TotalBillsIn { get; set; }
        public string Key_RC_TotalCash { get; set; }
        public string Key_RC_TotalCashIn { get; set; }
        public string Key_RC_TotalCashOut { get; set; }
        public string Key_RC_TotalCoins { get; set; }
        public string Key_RC_TotalDeclaredIn { get; set; }
        public string Key_RC_TotalDeclaredOut { get; set; }
        public string Key_RC_TotalDeo { get; set; }
        public string Key_RC_TotalDep { get; set; }
        public string Key_RC_TotalDrop { get; set; }
        public string Key_RC_TotalDue { get; set; }
        public string Key_RC_TotalExpense { get; set; }
        public string Key_RC_TotalExpenses { get; set; }
        public string Key_RC_TotalFundsAtSite { get; set; }
        public string Key_RC_TotalFundsIn { get; set; }
        public string Key_RC_TotalFundsInVGT { get; set; }
        public string Key_RC_TotalIn { get; set; }
        public string Key_RC_TotalJackpots { get; set; }
        public string Key_RC_TotalMeterIn { get; set; }
        public string Key_RC_TotalMeterOut { get; set; }
        public string Key_RC_TotalNet { get; set; }
        public string Key_RC_TotalOut { get; set; }
        public string Key_RC_TotalRetailersNetRevenueAfterCollection { get; set; }
        public string Key_RC_TotalTimeReserved { get; set; }
        public string Key_RC_TotalWon { get; set; }
        public string Key_RC_TotCmpShare { get; set; }
        public string Key_RC_TotOpShare { get; set; }
        public string Key_RC_TotSiteShare { get; set; }
        public string Key_RC_Transaction { get; set; }
        public string Key_RC_TransactionAmount { get; set; }
        public string Key_RC_TransactionDate { get; set; }
        public string Key_RC_TransactionDateTime { get; set; }
        public string Key_RC_TransactionID { get; set; }
        public string Key_RC_TransactionType { get; set; }
        public string Key_RC_Type { get; set; }
        public string Key_RC_User { get; set; }
        public string Key_RC_UserLevel { get; set; }
        public string Key_RC_UserName { get; set; }
        public string Key_RC_UserNameOutbox { get; set; }
        public string Key_RC_ValidationNumber { get; set; }
        public string Key_RC_Value { get; set; }
        public string Key_RC_Variance { get; set; }
        public string Key_RC_VariancePercentage { get; set; }
        public string Key_RC_VarPercentage { get; set; }
        public string Key_RC_VaultBalance { get; set; }
        public string Key_RC_VaultID { get; set; }
        public string Key_RC_VaultName { get; set; }
        public string Key_RC_VaultStatus { get; set; }
        public string Key_RC_VaultTotal { get; set; }
        public string Key_RC_VaultType { get; set; }
        public string Key_RC_VaultVariance { get; set; }
        public string Key_RC_Void { get; set; }
        public string Key_RC_VoidedAmt { get; set; }
        public string Key_RC_VoidVouchers { get; set; }
        public string Key_RC_Voucher { get; set; }
        public string Key_RC_VoucherInVar { get; set; }
        public string Key_RC_VoucherNumber { get; set; }
        public string Key_RC_VoucherOut { get; set; }
        public string Key_RC_VoucherOutVar { get; set; }
        public string Key_RC_Vouchers { get; set; }
        public string Key_RC_vouchersIn { get; set; }
        public string Key_RC_VouchersIn { get; set; }
        public string Key_RC_VouchersOut { get; set; }
        public string Key_RC_VouchersVar { get; set; }
        public string Key_RC_VouchersVoided { get; set; }
        public string Key_RC_VoucherType { get; set; }
        public string Key_RC_VoucherVar { get; set; }
        public string Key_RC_WATAmt { get; set; }
        public string Key_RC_WATIn { get; set; }
        public string Key_RC_WATOut { get; set; }
        public string Key_RC_WeightedAvgPercentage { get; set; }
        public string Key_RC_WeightedHold { get; set; }
        public string Key_RC_Win { get; set; }
        public string Key_RC_WinLoss { get; set; }
        public string Key_RC_WinLossDec { get; set; }
        public string Key_RC_WinLossReport { get; set; }
        public string Key_RC_WinLossVar { get; set; }
        public string Key_RC_WinOrLoss { get; set; }
        public string Key_RC_WinPercentageDiff { get; set; }
        public string Key_RC_WinperDevice { get; set; }
        public string Key_RC_WinPerDevicePer { get; set; }
        public string Key_RC_Wins { get; set; }
        public string Key_RC_WinsPerDay { get; set; }
        public string Key_RC_WinValue { get; set; }
        public string Key_RC_WOrUOrD { get; set; }
        public string Key_RC_WriteOff { get; set; }
        public string Key_RC_WriteOffs { get; set; }
        public string Key_RC_Zone { get; set; }
        public string Key_RC_ZoneName { get; set; }
        public string Key_RetailersNegativeNetPriorWeeksCollection { get; set; }
        public string Key_RF_Area { get; set; }
        public string Key_RF_BalanceDateTime { get; set; }
        public string Key_RF_BarPosition { get; set; }
        public string Key_RF_BatchNo { get; set; }
        public string Key_RF_BatchReference { get; set; }
        public string Key_RF_CardNumber { get; set; }
        public string Key_RF_CardStatus { get; set; }
        public string Key_RF_CardType { get; set; }
        public string Key_RF_Category { get; set; }
        public string Key_RF_CollectionDate { get; set; }
        public string Key_RF_Company { get; set; }
        public string Key_RF_Depot { get; set; }
        public string Key_RF_DeviceType { get; set; }
        public string Key_RF_District { get; set; }
        public string Key_RF_DropType { get; set; }
        public string Key_RF_EmployeeCard { get; set; }
        public string Key_RF_EmployeeCardId { get; set; }
        public string Key_RF_EmployeeName { get; set; }
        public string Key_RF_EndDate { get; set; }
        public string Key_RF_From { get; set; }
        public string Key_RF_GamingDate { get; set; }
        public string Key_RF_GamingDay { get; set; }
        public string Key_RF_GrandTotal { get; set; }
        public string Key_RF_GroupBy { get; set; }
        public string Key_RF_GroupByZone { get; set; }
        public string Key_RF_Grouping { get; set; }
        public string Key_RF_GroupingOn { get; set; }
        public string Key_RF_HideZeroVarianceCollections { get; set; }
        public string Key_RF_IncludeNonCashable { get; set; }
        public string Key_RF_IncludeZero { get; set; }
        public string Key_RF_InventoryLevel { get; set; }
        public string Key_RF_InventoryType { get; set; }
        public string Key_RF_IsGamingDayBasedReport { get; set; }
        public string Key_RF_IssueDate { get; set; }
        public string Key_RF_MachineCollectionGrouping { get; set; }
        public string Key_RF_MachineName { get; set; }
        public string Key_RF_MachineType { get; set; }
        public string Key_RF_ModuleName { get; set; }
        public string Key_RF_Name { get; set; }
        public string Key_RF_NumberOfMachines { get; set; }
        public string Key_RF_OrderBy { get; set; }
        public string Key_RF_Period { get; set; }
        public string Key_RF_PeriodFrom { get; set; }
        public string Key_RF_PeriodTo { get; set; }
        public string Key_RF_PerodFrom { get; set; }
        public string Key_RF_PurchasedFrom { get; set; }
        public string Key_RF_PurchasedTo { get; set; }
        public string Key_RF_Region { get; set; }
        public string Key_RF_ReportDate { get; set; }
        public string Key_RF_ReportPeriod { get; set; }
        public string Key_RF_ReportSelectionCriteria { get; set; }
        public string Key_RF_RouteName { get; set; }
        public string Key_RF_RuleName { get; set; }
        public string Key_RF_SC { get; set; }
        public string Key_RF_SCZ { get; set; }
        public string Key_RF_ShowHandpay { get; set; }
        public string Key_RF_ShowJackpot { get; set; }
        public string Key_RF_Signature { get; set; }
        public string Key_RF_Site { get; set; }
        public string Key_RF_SiteCode { get; set; }
        public string Key_RF_SiteName { get; set; }
        public string Key_RF_SiteNo { get; set; }
        public string Key_RF_Slot { get; set; }
        public string Key_RF_StackerLevel { get; set; }
        public string Key_RF_StartDate { get; set; }
        public string Key_RF_Status { get; set; }
        public string Key_RF_StockStatus { get; set; }
        public string Key_RF_SubCompany { get; set; }
        public string Key_RF_SummaryOnly { get; set; }
        public string Key_RF_Supplier { get; set; }
        public string Key_RF_To { get; set; }
        public string Key_RF_TransactionType { get; set; }
        public string Key_RF_UsePhysicalWin { get; set; }
        public string Key_RF_UsePurchaseDateFilter { get; set; }
        public string Key_RF_User { get; set; }
        public string Key_RF_UserName { get; set; }
        public string Key_RF_Variance { get; set; }
        public string Key_RF_VaultStatus { get; set; }
        public string Key_RF_VGT { get; set; }
        public string Key_RF_VoucherStatus { get; set; }
        public string Key_RF_WeekDate { get; set; }
        public string Key_RF_WeekNo { get; set; }
        public string Key_RF_Zone { get; set; }
        public string Key_RG_Address { get; set; }
        public string Key_RG_Area { get; set; }
        public string Key_RG_Asset { get; set; }
        public string Key_RG_AssetSubTotal { get; set; }
        public string Key_RG_AssetType { get; set; }
        public string Key_RG_Batch { get; set; }
        public string Key_RG_Category { get; set; }
        public string Key_RG_CategorySubTotal { get; set; }
        public string Key_RG_Code { get; set; }
        public string Key_RG_Company { get; set; }
        public string Key_RG_CompanySubTotal { get; set; }
        public string Key_RG_Default { get; set; }
        public string Key_RG_Denom { get; set; }
        public string Key_RG_DenomSubTotal { get; set; }
        public string Key_RG_District { get; set; }
        public string Key_RG_DropID { get; set; }
        public string Key_RG_DropSubTotal { get; set; }
        public string Key_RG_EmployeeCardNo { get; set; }
        public string Key_RG_EmployeeCardNoSubTotal { get; set; }
        public string Key_RG_GameCategory { get; set; }
        public string Key_RG_GameCategorySubTotal { get; set; }
        public string Key_RG_GameName { get; set; }
        public string Key_RG_GameNameSubTotal { get; set; }
        public string Key_RG_GameSubTotal { get; set; }
        public string Key_RG_GameTitle { get; set; }
        public string Key_RG_GameTitleSubTotal { get; set; }
        public string Key_RG_GrandTotal { get; set; }
        public string Key_RG_IssuedMachine { get; set; }
        public string Key_RG_Machine { get; set; }
        public string Key_RG_MachineStockNo { get; set; }
        public string Key_RG_MachineStockNoSubTotal { get; set; }
        public string Key_RG_MachineType { get; set; }
        public string Key_RG_MachineTypeCode { get; set; }
        public string Key_RG_MachineTypeCodeSubTotal { get; set; }
        public string Key_RG_MachineTypeDescription { get; set; }
        public string Key_RG_MachineTypeDescriptionSubTotal { get; set; }
        public string Key_RG_Manufacturer { get; set; }
        public string Key_RG_ManufacturerSubTotal { get; set; }
        public string Key_RG_Maufacturer { get; set; }
        public string Key_RG_NotSet { get; set; }
        public string Key_RG_PayPeriod { get; set; }
        public string Key_RG_PayPeriodSubTotal { get; set; }
        public string Key_RG_Region { get; set; }
        public string Key_RG_RegionSubtotal { get; set; }
        public string Key_RG_Site { get; set; }
        public string Key_RG_SiteBatchID { get; set; }
        public string Key_RG_SiteBatchIDSubTotal { get; set; }
        public string Key_RG_SiteCodeSubTotal { get; set; }
        public string Key_RG_SiteName { get; set; }
        public string Key_RG_SiteSubTotal { get; set; }
        public string Key_RG_SLAName { get; set; }
        public string Key_RG_Slot { get; set; }
        public string Key_RG_SlotSubTotal { get; set; }
        public string Key_RG_Status { get; set; }
        public string Key_RG_StatusSubTotal { get; set; }
        public string Key_RG_SubCompany { get; set; }
        public string Key_RG_SubCompanyRegion { get; set; }
        public string Key_RG_SubCompanyRegionSubTotal { get; set; }
        public string Key_RG_SubCompanySubTotal { get; set; }
        public string Key_RG_SubTotal { get; set; }
        public string Key_RG_SubTotalFor { get; set; }
        public string Key_RG_SubtotalForAssetType { get; set; }
        public string Key_RG_SubtotalForbatch { get; set; }
        public string Key_RG_SubTotalforDropID { get; set; }
        public string Key_RG_SubTotalForDropID { get; set; }
        public string Key_RG_SubTotalforIssuedMachine { get; set; }
        public string Key_RG_SubTotalforMachine { get; set; }
        public string Key_RG_SubTotalforMachineTypeCode { get; set; }
        public string Key_RG_SubTotalForTransType { get; set; }
        public string Key_RG_SubTotalforVoucherType { get; set; }
        public string Key_RG_TimeReserved { get; set; }
        public string Key_RG_TotalAmountforVaultName { get; set; }
        public string Key_RG_TotalMachines { get; set; }
        public string Key_RG_TotalMachinesforSlot { get; set; }
        public string Key_RG_TotalSites { get; set; }
        public string Key_RG_TotalTimeReserved { get; set; }
        public string Key_RG_TransactionTotal { get; set; }
        public string Key_RG_TransactionType { get; set; }
        public string Key_RG_UserName { get; set; }
        public string Key_RG_UserNameSubTotal { get; set; }
        public string Key_RG_VaultSubTotal { get; set; }
        public string Key_RG_ZipCode { get; set; }
        public string Key_RG_Zone { get; set; }
        public string Key_RG_ZoneSubTotal { get; set; }
        public string Key_RT_AccountingDetailedReport { get; set; }
        public string Key_RT_AccountingMachineWinLossReport { get; set; }
        public string Key_RT_AccountingSummaryReport { get; set; }
        public string Key_RT_AFTAuditTrailReport { get; set; }
        public string Key_RT_AssetDetailedReport { get; set; }
        public string Key_RT_AssetDetailsReport { get; set; }
        public string Key_RT_AssetReport { get; set; }
        public string Key_RT_AuditTrailReport { get; set; }
        public string Key_RT_BATCHDROPEXCEPTIONREPORT { get; set; }
        public string Key_RT_BatchWinLoss { get; set; }
        public string Key_RT_BatchWinLossReport { get; set; }
        public string Key_RT_BMCMeterAdjustmentAuditReport { get; set; }
        public string Key_RT_CappedGameListReport { get; set; }
        public string Key_RT_CappedGameSummaryReport { get; set; }
        public string Key_RT_CashDeskMovementReport { get; set; }
        public string Key_RT_CashDispenserAccountingReport { get; set; }
        public string Key_RT_CashDispenserCassetteAccountingDetailsReport { get; set; }
        public string Key_RT_CashDispenserCassettesInventoryStatusReport { get; set; }
        public string Key_RT_CashDispenserConfigurationDetailsReport { get; set; }
        public string Key_RT_CashDispenserDropReport { get; set; }
        public string Key_RT_CashDispenserInventoryStatusReport { get; set; }
        public string Key_RT_CashDispenserLevelDetailsReport { get; set; }
        public string Key_RT_CashDispenserTransactionDetailsReport { get; set; }
        public string Key_RT_CashDispenserVarianceReport { get; set; }
        public string Key_RT_CashierTransactionsDetailedView { get; set; }
        public string Key_RT_CoinInbyPaytableReport { get; set; }
        public string Key_RT_ConsolidatedMCCollectionVarianceReport { get; set; }
        public string Key_RT_ConsolidatedSystemBalancingReport { get; set; }
        public string Key_RT_CrossPropertyLiabilityTransferDetailsReport { get; set; }
        public string Key_RT_CrossPropertyLiabilityTransferSummaryReport { get; set; }
        public string Key_RT_CrossPropertyTicketAnalysisReport { get; set; }
        public string Key_RT_DailyAccountingDetailReport { get; set; }
        public string Key_RT_DailyAccountingPerEnrollmentReport { get; set; }
        public string Key_RT_DailyAccountingSummaryReport { get; set; }
        public string Key_RT_DailyCashDeskReconciliationReport { get; set; }
        public string Key_RT_DeclarationSummaryReport { get; set; }
        public string Key_RT_DeclaredVaultDropsCassetteDetails { get; set; }
        public string Key_RT_DeclaredVaultDropsHistoryReport { get; set; }
        public string Key_RT_DepreciationReport { get; set; }
        public string Key_RT_DropScheduleDetailsReport { get; set; }
        public string Key_RT_EFTQuestionableTransactionsReport { get; set; }
        public string Key_RT_EFTSlotActivityCumulativeReport { get; set; }
        public string Key_RT_EFTSlotActivityReport { get; set; }
        public string Key_RT_ElecTransferVsRevenueComparisonReport { get; set; }
        public string Key_RT_ElectronicGamingCashDeskMovementReport { get; set; }
        public string Key_RT_EmployeeCardListReport { get; set; }
        public string Key_RT_EmployeeCardSessionReport { get; set; }
        public string Key_RT_EnrollmentWinLossReport { get; set; }
        public string Key_RT_ExpenseDetailReport { get; set; }
        public string Key_RT_ExpiredCalendarsReport { get; set; }
        public string Key_RT_ExpiredVoucherCouponReport { get; set; }
        public string Key_RT_FixedExpenseDetailsReport { get; set; }
        public string Key_RT_FixedExpenseDueFrom { get; set; }
        public string Key_RT_GamePerformanceReport { get; set; }
        public string Key_RT_GameReport { get; set; }
        public string Key_RT_JackpotSlipSummaryReport { get; set; }
        public string Key_RT_LicenseExpiryReport { get; set; }
        public string Key_RT_LicenseHistoryReport { get; set; }
        public string Key_RT_MajorPrizeReport { get; set; }
        public string Key_RT_ManufacturerPerformanceReport { get; set; }
        public string Key_RT_MeterComparisonReport { get; set; }
        public string Key_RT_MeterDetailedFlashReport { get; set; }
        public string Key_RT_MeterPeriodComparisonReport { get; set; }
        public string Key_RT_MeterSummaryFlashReport { get; set; }
        public string Key_RT_MGMDByGamingDeviceCabinetReport { get; set; }
        public string Key_RT_MultiDenomSlotDetailReport { get; set; }
        public string Key_RT_MultiGameDenomPerformanceReport { get; set; }
        public string Key_RT_MultiGameMultiDenomSummaryAnalysis { get; set; }
        public string Key_RT_MultiGameSlotDetailReport { get; set; }
        public string Key_RT_PeriodEndLiquidationRevenueReport { get; set; }
        public string Key_RT_ProgressiveWinDetailedReport { get; set; }
        public string Key_RT_ProgressiveWinSummaryReport { get; set; }
        public string Key_RT_PromotionalSummaryReport { get; set; }
        public string Key_RT_PromotionalVoucherListingReport { get; set; }
        public string Key_RT_RedeemedVoucherByDeviceReport { get; set; }
        public string Key_RT_ReportLiquidationSummary_CollectionBased { get; set; }
        public string Key_RT_ReportLiquidationSummary_ReadBased { get; set; }
        public string Key_RT_ServiceFaultGroupReport { get; set; }
        public string Key_RT_ServiceRemedyCodesReport { get; set; }
        public string Key_RT_ServiceSLATermsReport { get; set; }
        public string Key_RT_SiteAddressListReport { get; set; }
        public string Key_RT_SlotEnrollmentReport { get; set; }
        public string Key_RT_SlotMachinePerformanceReport { get; set; }
        public string Key_RT_SoftCountComparisionReport { get; set; }
        public string Key_RT_StackerLevelDetailsReport { get; set; }
        public string Key_RT_StaffListDetailedReport { get; set; }
        public string Key_RT_StaffListReport { get; set; }
        public string Key_RT_TotalFundsInDetailsReport { get; set; }
        public string Key_RT_TotalFundsInSummaryReport { get; set; }
        public string Key_RT_UndeclaredVaultDropsCassetteDetails { get; set; }
        public string Key_RT_UndeclaredVaultDropsReport { get; set; }
        public string Key_RT_ViewSiteAssetGameReport { get; set; }
        public string Key_RT_VoucherLiabilityReport { get; set; }
        public string Key_RT_VoucherListingReport { get; set; }
        public string Key_RT_VSAssetGameReport { get; set; }
        public string Key_RT_WeeklyExceptionSummaryReport { get; set; }
        public string Key_RT_WeeklyWinLoss { get; set; }
        public string Key_RT_WeeklyWinLossReport { get; set; }
        public string Key_RT_WinComparisonReport { get; set; }
        public string Key_RX_Active { get; set; }
        public string Key_RX_ActiveSitesOnly { get; set; }
        public string Key_RX_All { get; set; }
        public string Key_RX_AllSites { get; set; }
        public string Key_RX_AllWithHyphens { get; set; }
        public string Key_RX_AmountIn { get; set; }
        public string Key_RX_AnyWithHyphens { get; set; }
        public string Key_RX_AssignedToSite { get; set; }
        public string Key_RX_Available { get; set; }
        public string Key_RX_BatchRefernece { get; set; }
        public string Key_RX_BMC { get; set; }
        public string Key_RX_BreakDownOf { get; set; }
        public string Key_RX_CEPromo { get; set; }
        public string Key_RX_CollectionDate { get; set; }
        public string Key_RX_CompanyConfidential { get; set; }
        public string Key_RX_Converted { get; set; }
        public string Key_RX_Deposit { get; set; }
        public string Key_RX_DueOut { get; set; }
        public string Key_RX_EFTWithdraw { get; set; }
        public string Key_RX_EndDate { get; set; }
        public string Key_RX_Event { get; set; }
        public string Key_RX_FromDate { get; set; }
        public string Key_RX_Game { get; set; }
        public string Key_RX_GamingDate { get; set; }
        public string Key_RX_GamingDay { get; set; }
        public string Key_RX_Handpay { get; set; }
        public string Key_RX_InActive { get; set; }
        public string Key_RX_InStock { get; set; }
        public string Key_RX_InStockUnusable { get; set; }
        public string Key_RX_InUse { get; set; }
        public string Key_RX_Jackpot { get; set; }
        public string Key_RX_Legend { get; set; }
        public string Key_Rx_MGMDCabinetGroupBy { get; set; }
        public string Key_RX_MGMDSummaryAnalysisLegend { get; set; }
        public string Key_RX_Mystery { get; set; }
        public string Key_RX_NCEPromo { get; set; }
        public string Key_RX_None { get; set; }
        public string Key_RX_NoneWithHyphens { get; set; }
        public string Key_RX_NoRecords_Found { get; set; }
        public string Key_RX_Of { get; set; }
        public string Key_RX_OnOrder { get; set; }
        public string Key_RX_Page { get; set; }
        public string Key_RX_Progessive { get; set; }
        public string Key_RX_PublishedByBMCVersion { get; set; }
        public string Key_RX_ReadDate { get; set; }
        public string Key_RX_ReportFilterCriteria { get; set; }
        public string Key_RX_Reserved { get; set; }
        public string Key_RX_RouteName { get; set; }
        public string Key_RX_ServiceNo { get; set; }
        public string Key_RX_ServiceYes { get; set; }
        public string Key_RX_SiteDenom { get; set; }
        public string Key_RX_SiteDenoZone { get; set; }
        public string Key_RX_SlotMachinePerformanceLegend { get; set; }
        public string Key_RX_Sold { get; set; }
        public string Key_RX_StartDate { get; set; }
        public string Key_RX_StatusOn { get; set; }
        public string Key_RX_Terminated { get; set; }
        public string Key_RX_TotalChangeToAccount { get; set; }
        public string Key_RX_TotalDeposit { get; set; }
        public string Key_RX_TotalWithdraw { get; set; }
        public string Key_RX_Uncategorised { get; set; }
        public string Key_RX_UnderRepair { get; set; }
        public string Key_RX_Unusable { get; set; }
        public string Key_RX_User { get; set; }
        public string Key_RX_Vault { get; set; }
        public string Key_RX_Voucher { get; set; }
        public string Key_RX_WAT { get; set; }
        public string Key_RX_Week { get; set; }
        public string Key_RX_WeekDate { get; set; }
        public string Key_RX_WeekNo { get; set; }
        public string Key_RX_BatchId { get; set; }
		public string Key_RX_ExcludingBadMeters { get; set; }
        public string Key_False { get; set; }
        public string Key_True { get; set; }

        public string Key_RL_AccountingWinLoss { get; set; }
        public string Key_RL_DailyAccountingDetail { get; set; }
        public string Key_RL_DailyAccountingPerInstallation { get; set; }
        public string Key_RL_DailyAccountingSummary { get; set; }
        public string Key_RL_EFTQuestionableTransactionsReport { get; set; }
        public string Key_RL_EFTSlotActivityCumulativeReport { get; set; }
        public string Key_RL_EFTSlotActivityReport { get; set; }
        public string Key_RL_ElecTransferVsRevenueComparisonReport { get; set; }
        public string Key_RL_ENT_CashDeskReconicilationReport { get; set; }
        public string Key_RL_ManufacturerPerformanceReport { get; set; }
        public string Key_RX_Supplier { get; set; }
        public string Key_RC_Company { get; set; }
        public string Key_RC_SubCompany { get; set; }
        public string Key_RX_Site { get; set; }
        public string Key_RX_Category { get; set; }
        public string Key_RX_Zone { get; set; }

        public string Key_RX_ReportDate { get; set; }
        public string Key_RX_IssueDateTime { get; set; }
        public string Key_RT_DailyElectronicFundRevenueReport { get; set; }
        public string Key_RL_DailyElectronicFundRevenueReport { get; set; }

        public string Key_DoubleSpace { get; set; }
        public string Key_SingleSpace { get; set; }
		public string Key_RC_Site { get; set; }
        public string Key_RC_CashVouchersIn{get;set;}
        public string Key_RC_CashVoucherOut { get; set; }
        public string Key_RF_Site_NoColon { get; set; }
        public string Key_RF_Zone_NoColon { get; set; }
 		public string Key_RC_AssignedSiteCodeWithoutColon { get; set; }
        public string Key_RX_NoSite{get;set;}

        public string Key_RC_TransactionIDWithColan { get; set; }
        public string Key_AllVaultStatus { get; set; }

        public string Key_RL_ENT_SystemBalancing { get; set; }
        public string Key_RC_MeterBalance { get; set; }

    }
}
