USE [Enterprise]
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__014B97D0]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__014B97D0] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__020C488D]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__020C488D] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__0723A160]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__0723A160] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__0A01A4B9]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__0A01A4B9] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__0C9C8394]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__0C9C8394] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__0E3B7E9A]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__0E3B7E9A] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__0EA4C797]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__0EA4C797] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__11ADB379]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__11ADB379] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__19F74A09]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__19F74A09] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__1A4DE672]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__1A4DE672] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__1A9733DE]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__1A9733DE] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__1CAB3030]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__1CAB3030] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__1EE6E7AF]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__1EE6E7AF] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__242B8B10]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__242B8B10] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__24367808]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__24367808] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__2667428F]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__2667428F] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__2CAAF721]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__2CAAF721] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__2FB317AC]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__2FB317AC] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__36A89750]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__36A89750] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__388854CF]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__388854CF] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__398FF0F3]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__398FF0F3] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__3B6E17C4]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__3B6E17C4] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__3C417515]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__3C417515] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__3E605E5F]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__3E605E5F] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__3F4995A0]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__3F4995A0] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__40071901]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__40071901] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__417B2B7E]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__417B2B7E] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__48E8D9CA]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__48E8D9CA] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__5205CDAB]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__5205CDAB] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__52469024]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__52469024] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__588A44B6]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__588A44B6] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__5B5BC469]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__5B5BC469] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__5D391FE3]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__5D391FE3] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__5EE3D338]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__5EE3D338] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__5F4ABA30]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__5F4ABA30] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__612A77AF]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__612A77AF] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__623D00CB]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__623D00CB] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__63DB307A]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__63DB307A] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__670BD789]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__670BD789] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__69CAAAA8]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__69CAAAA8] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__6B49AA1D]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__6B49AA1D] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__70554AA1]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__70554AA1] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__73A84F46]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__73A84F46] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__750FDE1D]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__750FDE1D] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__796C1594]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__796C1594] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__7D1BDF90]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__7D1BDF90] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__7D3284D7]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__7D3284D7] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__7ECE5281]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__7ECE5281] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__DELET__7EEE4E12]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__DELET__7EEE4E12] FOREIGN KEY([DELETEDBY])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__023FBC09]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__023FBC09] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__03006CC6]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__03006CC6] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__0817C599]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__0817C599] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__0AF5C8F2]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__0AF5C8F2] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__0D90A7CD]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__0D90A7CD] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__0F2FA2D3]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__0F2FA2D3] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__0F98EBD0]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__0F98EBD0] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__12A1D7B2]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__12A1D7B2] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__1AEB6E42]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__1AEB6E42] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__1B420AAB]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__1B420AAB] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__1B8B5817]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__1B8B5817] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__1D9F5469]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__1D9F5469] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__1FDB0BE8]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__1FDB0BE8] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__251FAF49]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__251FAF49] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__252A9C41]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__252A9C41] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__275B66C8]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__275B66C8] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__2D9F1B5A]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__2D9F1B5A] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__30A73BE5]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__30A73BE5] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__379CBB89]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__379CBB89] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__397C7908]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__397C7908] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__3A84152C]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__3A84152C] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__3C623BFD]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__3C623BFD] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__3D35994E]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__3D35994E] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__3F548298]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__3F548298] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__403DB9D9]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__403DB9D9] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__40FB3D3A]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__40FB3D3A] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__426F4FB7]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__426F4FB7] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__49DCFE03]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__49DCFE03] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__52F9F1E4]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__52F9F1E4] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__533AB45D]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__533AB45D] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__597E68EF]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__597E68EF] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__5C4FE8A2]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__5C4FE8A2] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__5E2D441C]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__5E2D441C] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__5FD7F771]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__5FD7F771] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__603EDE69]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__603EDE69] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__621E9BE8]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__621E9BE8] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__63312504]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__63312504] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__64CF54B3]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__64CF54B3] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__67FFFBC2]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__67FFFBC2] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__6ABECEE1]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__6ABECEE1] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__6C3DCE56]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__6C3DCE56] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__71496EDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__71496EDA] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__749C737F]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__749C737F] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__76040256]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__76040256] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__7A6039CD]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__7A6039CD] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__7E1003C9]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__7E1003C9] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__7E26A910]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__7E26A910] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__7FC276BA]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__7FC276BA] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__INACTIVEU__Secur__7FE2724B]') AND parent_object_id = OBJECT_ID(N'[dbo].[INACTIVEUSER]'))

ALTER TABLE [dbo].[INACTIVEUSER]  WITH CHECK ADD  CONSTRAINT [FK__INACTIVEU__Secur__7FE2724B] FOREIGN KEY([SecurityUserID])
REFERENCES [USER] ([SecurityUserID])
GO

