#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.MeterAdjustmentTool
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Enterprise")]
	public partial class EnterpriseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EnterpriseDataContext() : 
				base(global::BMC.MeterAdjustmentTool.Properties.Settings.Default.EnterpriseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnterpriseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnterpriseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnterpriseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnterpriseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateSiteDBConnectionString")]
		public int FuncUpdateSiteDBConnectionString([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site_ID", DbType="Int")] System.Nullable<int> site_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site_DB_ConnectionString", DbType="VarBinary(1)")] System.Data.Linq.Binary site_DB_ConnectionString)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_ID, site_DB_ConnectionString);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rsp_AuthenticateAndGetUser")]
		public ISingleResult<rsp_AuthenticateAndGetUserResult> FuncAuthenticateAndGetUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(200)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAuthenticated", DbType="Int")] ref System.Nullable<int> isAuthenticated)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, isAuthenticated);
			isAuthenticated = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<rsp_AuthenticateAndGetUserResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.rsp_GetSiteDetailsForMeterAdjustment")]
        public ISingleResult<rsp_GetSiteDetailsResult> FuncGetSiteDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Site_Name", DbType = "VarChar(100)")] string site_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Site_Status", DbType = "Int")] System.Nullable<int> site_Status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "UserID", DbType = "Int")] System.Nullable<int> UserID)
		{
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Name, site_Status, UserID);
			return ((ISingleResult<rsp_GetSiteDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_RemoveSiteDBConnectionString")]
		public int usp_RemoveSiteDBConnectionString([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site_ID", DbType="Int")] System.Nullable<int> site_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_ID);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class rsp_AuthenticateAndGetUserResult
	{
		
		private int _SecurityUserID;
		
		private string _WindowsUserName;
		
		private string _UserName;
		
		private char _PASSWORD;
		
		private System.Nullable<int> _LanguageID;
		
		private System.Nullable<int> _CurrencyCulture;
		
		private System.Nullable<int> _DateCulture;
		
		private System.Nullable<bool> _ChangePassword;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _PasswordChangeDate;
		
		private System.Nullable<bool> _isReset;
		
		private bool _isLocked;
		
		public rsp_AuthenticateAndGetUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityUserID", DbType="Int NOT NULL")]
		public int SecurityUserID
		{
			get
			{
				return this._SecurityUserID;
			}
			set
			{
				if ((this._SecurityUserID != value))
				{
					this._SecurityUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindowsUserName", DbType="VarChar(200)")]
		public string WindowsUserName
		{
			get
			{
				return this._WindowsUserName;
			}
			set
			{
				if ((this._WindowsUserName != value))
				{
					this._WindowsUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(1) NOT NULL")]
		public char PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int")]
		public System.Nullable<int> LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this._LanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCulture", DbType="Int")]
		public System.Nullable<int> CurrencyCulture
		{
			get
			{
				return this._CurrencyCulture;
			}
			set
			{
				if ((this._CurrencyCulture != value))
				{
					this._CurrencyCulture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCulture", DbType="Int")]
		public System.Nullable<int> DateCulture
		{
			get
			{
				return this._DateCulture;
			}
			set
			{
				if ((this._DateCulture != value))
				{
					this._DateCulture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangePassword", DbType="Bit")]
		public System.Nullable<bool> ChangePassword
		{
			get
			{
				return this._ChangePassword;
			}
			set
			{
				if ((this._ChangePassword != value))
				{
					this._ChangePassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordChangeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PasswordChangeDate
		{
			get
			{
				return this._PasswordChangeDate;
			}
			set
			{
				if ((this._PasswordChangeDate != value))
				{
					this._PasswordChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isReset", DbType="Bit")]
		public System.Nullable<bool> isReset
		{
			get
			{
				return this._isReset;
			}
			set
			{
				if ((this._isReset != value))
				{
					this._isReset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isLocked", DbType="Bit NOT NULL")]
		public bool isLocked
		{
			get
			{
				return this._isLocked;
			}
			set
			{
				if ((this._isLocked != value))
				{
					this._isLocked = value;
				}
			}
		}
	}
	
	public partial class rsp_GetSiteDetailsResult
	{
		
		private int _Site_ID;
		
		private string _Site_Name;
		
		private string _Site_Status;
		
		private string _WEBUrl;
		
		private string _Site_code;
		
		private int _Site_Status_ID;
		
		private string _SettingsProfile_Description;
		
		private System.Data.Linq.Binary _Site_DB_ConnectionString;
		
		public rsp_GetSiteDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_ID", DbType="Int NOT NULL")]
		public int Site_ID
		{
			get
			{
				return this._Site_ID;
			}
			set
			{
				if ((this._Site_ID != value))
				{
					this._Site_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Name", DbType="VarChar(50)")]
		public string Site_Name
		{
			get
			{
				return this._Site_Name;
			}
			set
			{
				if ((this._Site_Name != value))
				{
					this._Site_Name = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Site_Status", DbType = "VarChar(2000)")]
        public string Site_Status
        {
            get
            {
                return this._Site_Status;
            }
            set
            {
                if ((this._Site_Status != value))
                {
                    this._Site_Status = value;
                }
            }
        }
		
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBUrl", DbType="VarChar(2000)")]
		public string WEBUrl
		{
			get
			{
				return this._WEBUrl;
			}
			set
			{
				if ((this._WEBUrl != value))
				{
					this._WEBUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_code", DbType="VarChar(50)")]
		public string Site_code
		{
			get
			{
				return this._Site_code;
			}
			set
			{
				if ((this._Site_code != value))
				{
					this._Site_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Status_ID", DbType="Int NOT NULL")]
		public int Site_Status_ID
		{
			get
			{
				return this._Site_Status_ID;
			}
			set
			{
				if ((this._Site_Status_ID != value))
				{
					this._Site_Status_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingsProfile_Description", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SettingsProfile_Description
		{
			get
			{
				return this._SettingsProfile_Description;
			}
			set
			{
				if ((this._SettingsProfile_Description != value))
				{
					this._SettingsProfile_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_DB_ConnectionString", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Site_DB_ConnectionString
		{
			get
			{
				return this._Site_DB_ConnectionString;
			}
			set
			{
				if ((this._Site_DB_ConnectionString != value))
				{
					this._Site_DB_ConnectionString = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
