//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.EnterpriseClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolStripResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolStripResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMC.EnterpriseClient.Resources.ToolStripResources", typeof(ToolStripResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string MAIN_TBAR_ACCESS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string MAIN_TBAR_ADMIN {
            get {
                return ResourceManager.GetString("MAIN_TBAR_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string MAIN_TBAR_ANALYSIS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string MAIN_TBAR_ASSETS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_ASSETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit &amp;&amp; Monitoring.
        /// </summary>
        internal static string MAIN_TBAR_AUDITMONITOR {
            get {
                return ResourceManager.GetString("MAIN_TBAR_AUDITMONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        internal static string MAIN_TBAR_CALENDARS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_CALENDARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string MAIN_TBAR_CHANGEPWD {
            get {
                return ResourceManager.GetString("MAIN_TBAR_CHANGEPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Calls.
        /// </summary>
        internal static string MAIN_TBAR_CLOSEDCALLS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_CLOSEDCALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Call.
        /// </summary>
        internal static string MAIN_TBAR_CREATECALL {
            get {
                return ResourceManager.GetString("MAIN_TBAR_CREATECALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Calls.
        /// </summary>
        internal static string MAIN_TBAR_CURRENTCALLS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_CURRENTCALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Comms Audit.
        /// </summary>
        internal static string MAIN_TBAR_DATACOMMSAUDIT {
            get {
                return ResourceManager.GetString("MAIN_TBAR_DATACOMMSAUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sheet.
        /// </summary>
        internal static string MAIN_TBAR_DATASHEET {
            get {
                return ResourceManager.GetString("MAIN_TBAR_DATASHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        internal static string MAIN_TBAR_DECLARATION {
            get {
                return ResourceManager.GetString("MAIN_TBAR_DECLARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot.
        /// </summary>
        internal static string MAIN_TBAR_DEPOT {
            get {
                return ResourceManager.GetString("MAIN_TBAR_DEPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Schedule.
        /// </summary>
        internal static string MAIN_TBAR_DROPSCHEDULE {
            get {
                return ResourceManager.GetString("MAIN_TBAR_DROPSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Card Details.
        /// </summary>
        internal static string MAIN_TBAR_EMPLOYEE {
            get {
                return ResourceManager.GetString("MAIN_TBAR_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        internal static string MAIN_TBAR_EVENTVIEWER {
            get {
                return ResourceManager.GetString("MAIN_TBAR_EVENTVIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Share Groups.
        /// </summary>
        internal static string MAIN_TBAR_EXPENSESHAREGROUPS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_EXPENSESHAREGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        internal static string MAIN_TBAR_FINANCIAL {
            get {
                return ResourceManager.GetString("MAIN_TBAR_FINANCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Library.
        /// </summary>
        internal static string MAIN_TBAR_GAMELIBRARY {
            get {
                return ResourceManager.GetString("MAIN_TBAR_GAMELIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMU Events.
        /// </summary>
        internal static string MAIN_TBAR_GMUEVENTS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_GMUEVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string MAIN_TBAR_GROUPS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MAIN_TBAR_LOGIN {
            get {
                return ResourceManager.GetString("MAIN_TBAR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MAIN_TBAR_LOGOUT {
            get {
                return ResourceManager.GetString("MAIN_TBAR_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hours.
        /// </summary>
        internal static string MAIN_TBAR_OPENHOURS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_OPENHOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        internal static string MAIN_TBAR_OPERATORS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_OPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        internal static string MAIN_TBAR_ORGANISATION {
            get {
                return ResourceManager.GetString("MAIN_TBAR_ORGANISATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Share Groups.
        /// </summary>
        internal static string MAIN_TBAR_PROFITSHAREGROUPS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_PROFITSHAREGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MAIN_TBAR_REPORTS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Admin.
        /// </summary>
        internal static string MAIN_TBAR_SERVICEADMIN {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SERVICEADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Calls.
        /// </summary>
        internal static string MAIN_TBAR_SERVICECALLS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SERVICECALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MAIN_TBAR_SETTINGS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Holders.
        /// </summary>
        internal static string MAIN_TBAR_SHAREHOLDERS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SHAREHOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Licensing.
        /// </summary>
        internal static string MAIN_TBAR_SITELICENSING {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SITELICENSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        internal static string MAIN_TBAR_SITESETTINGS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SITESETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacker.
        /// </summary>
        internal static string MAIN_TBAR_STACKER {
            get {
                return ResourceManager.GetString("MAIN_TBAR_STACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Monitoring.
        /// </summary>
        internal static string MAIN_TBAR_SYSMON {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SYSMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Audit.
        /// </summary>
        internal static string MAIN_TBAR_SYSTEMAUDIT {
            get {
                return ResourceManager.GetString("MAIN_TBAR_SYSTEMAUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        internal static string MAIN_TBAR_USERADMINISTRATION {
            get {
                return ResourceManager.GetString("MAIN_TBAR_USERADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MAIN_TBAR_USERS {
            get {
                return ResourceManager.GetString("MAIN_TBAR_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sites.
        /// </summary>
        internal static string MAIN_TBAR_VIEWSITES {
            get {
                return ResourceManager.GetString("MAIN_TBAR_VIEWSITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Administration.
        /// </summary>
        internal static string VIEWSITES_MENU_POS_ADMIN {
            get {
                return ResourceManager.GetString("VIEWSITES_MENU_POS_ADMIN", resourceCulture);
            }
        }
    }
}
