<?xml version="1.0" encoding="utf-8"?>
<Database Name="BAS" Class="BASDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BAS;User ID=sa" SettingsObjectName="BASExportImportService.Properties.Settings" SettingsPropertyName="BASConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Export_History" Member="Export_Histories">
    <Type Name="Export_History">
      <Column Name="EH_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Recieved_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EH_Exported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EH_Reference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EH_Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EH_Message" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Import_History" Member="Import_Histories">
    <Type Name="Import_History">
      <Column Name="IH_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IH_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IH_Message" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="IH_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IH_Received_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IH_Imported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IH_ExportResult" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAS_IS_Export_History" Member="BAS_IS_Export_Histories">
    <Type Name="BAS_IS_Export_History">
      <Column Name="BIEH_ID" AutoSync="Never" Type="System.Int32" DbType="Int Not Null Identity" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_Reference" Type="System.Int32" DbType="INT Not NULL Identity" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_Message_ID" Type="System.String" DbType="varchar(50)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_Message_Type" Type="System.String" DbType="varchar(5)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_Status" Type="System.Int32" DbType="INT" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BIEH_Received_Date" Type="System.DateTime" DbType="DATETIME" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BIEH_Exported_Date" Type="System.DateTime" DbType="datetime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BIEH_Comments" Type="System.String" DbType="varchar(100)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_BASMessage" Type="System.String" DbType="varchar(8000)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_ISXMLMessage" Type="System.String" DbType="varchar(8000)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BIEH_Retry_Counter" Type="System.Int32" DbType="int not null " CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.BAS_Settings" Member="BAS_Settings">
    <Type Name="BAS_Settings">
      <Column Name="Setting_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Setting_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Setting_Value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.rsp_GetUnExportedRecordsFromExportHistory" Method="rsp_GetUnExportedRecordsFromExportHistory">
    <ElementType Name="rsp_GetUnExportedRecordsFromExportHistoryResult">
      <Column Name="EH_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Recieved_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EH_Exported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EH_Reference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EH_Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EH_Message" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.rsp_GetUnExportedRecordsFromImportHistory" Method="rsp_GetUnExportedRecordsFromImportHistory">
    <ElementType Name="rsp_GetUnExportedRecordsFromImportHistoryResult">
      <Column Name="IH_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IH_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IH_Message" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="IH_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IH_Received_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IH_Imported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IH_ExportResult" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_UpdateEHRecordAsExported" Method="usp_UpdateEHRecordAsExported">
    <Parameter Name="EH_ID" Parameter="eH_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UpdateIHRecordAsExported" Method="usp_UpdateIHRecordAsExported">
    <Parameter Name="IH_ID" Parameter="iH_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IH_Success" Parameter="iH_Success" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.rsp_GetNotAcknowledgedMessages" Method="rsp_GetNotAcknowledgedMessages">
    <ElementType Name="rsp_GetNotAcknowledgedMessagesResult">
      <Column Name="IH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IH_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IH_Message" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IH_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IH_Received_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IH_Imported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IH_ExportResult" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EH_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EH_MESSAGE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Recieved_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EH_Exported_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EH_Reference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EH_Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EH_Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EH_Message" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_UpdateEHRecordFor504" Method="usp_UpdateEHRecordFor504">
    <Parameter Name="EH_ID" Parameter="eH_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_InsUpd_Export_History" Method="usp_InsUpd_Export_History">
    <Parameter Name="EH_ID" Parameter="eH_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EH_MESSAGE_ID" Parameter="eH_MESSAGE_ID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EH_Message" Parameter="eH_Message" Type="System.String" DbType="VarChar(4000)" />
    <Parameter Name="EH_Type" Parameter="eH_Type" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="EH_Status" Parameter="eH_Status" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="usp_InsUpd_Export_HistoryResult">
      <Column Name="EH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_InsertErrorMessage" Method="usp_InsertErrorMessage">
    <Parameter Name="Message_Id" Parameter="message_Id" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Message_Type" Parameter="message_Type" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Error" Parameter="error" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Details" Parameter="details" Type="System.String" DbType="VarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
</Database>