USE [Enterprise]
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AAMS_Region_Code]') AND type in (N'U'))

BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AAMS_Region_Code](
	[ARC_Code] [char](2) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[AAMS_Region_Code] ADD  CONSTRAINT [PK_AAMS_Region_Code] PRIMARY KEY CLUSTERED 
(
	[ARC_Code] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
END

GO

