USE [Enterprise]
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AAMS_Entities]') AND type in (N'U'))

BEGIN

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AAMS_Entities](
	[AE_ID] [int] NOT NULL,
	[AE_Type] [varchar](20) NOT NULL,
	[AE_Description] [varchar](50) NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[AAMS_Entities] ADD  CONSTRAINT [PK_AAMS_Entities] PRIMARY KEY CLUSTERED 
(
	[AE_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
END

GO

