#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.CashDispenser.Core
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Exchange")]
	public partial class CashDispenserDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CashDispenserDBDataContext() : 
				base(global::BMC.CashDispenser.Core.Properties.Settings.Default.ExchangeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CashDispenserDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CashDispenserDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CashDispenserDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CashDispenserDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rsp_GetCashDispenserItems")]
		public ISingleResult<rsp_GetCashDispenserItemsResult> GetCashDispenserItems()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<rsp_GetCashDispenserItemsResult>)(result.ReturnValue));
		}

        [Function(Name = "dbo.rsp_GetCashDispenserErrorCodes")]
        public ISingleResult<rsp_GetCashDispenserErrorCodes> GetCashDispenserErrorCodes()
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
            return ((ISingleResult<rsp_GetCashDispenserErrorCodes>)(result.ReturnValue));
        }
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateCashDispenserItemValues")]
		public int UpdateCashDispenserItemValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CassetteID", DbType="Int")] System.Nullable<int> cassetteID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssuedValue", DbType="Decimal(18,0)")] System.Nullable<decimal> issuedValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RejectedValue", DbType="Decimal(18,0)")] System.Nullable<decimal> rejectedValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssuedValueOut", DbType="Decimal(18,0)")] ref System.Nullable<decimal> issuedValueOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RejectedValueOut", DbType="Decimal(18,0)")] ref System.Nullable<decimal> rejectedValueOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cassetteID, issuedValue, rejectedValue, issuedValueOut, rejectedValueOut, result);
			issuedValueOut = ((System.Nullable<decimal>)(result1.GetParameterValue(3)));
			rejectedValueOut = ((System.Nullable<decimal>)(result1.GetParameterValue(4)));
			result = ((System.Nullable<int>)(result1.GetParameterValue(5)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateCashDispenserItem")]
		public int UpdateCashDispenserItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CassetteID", DbType="Int")] System.Nullable<int> cassetteID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CassetteAlias", DbType="VarChar(50)")] string cassetteAlias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Denomination", DbType="Int")] System.Nullable<int> denomination, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalValue", DbType="Decimal(18,0)")] System.Nullable<decimal> totalValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="Int")] System.Nullable<int> user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Name", DbType="VarChar(50)")] string user_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cassetteID, cassetteAlias, denomination, totalValue, user_ID, user_Name, result);
			result = ((System.Nullable<int>)(result1.GetParameterValue(6)));
			return ((int)(result1.ReturnValue));
		}
	}
	
	public partial class rsp_GetCashDispenserItemsResult
	{
		
		private int _CassetteID;
		
		private string _CassetteName;
		
		private string _CassetteAlias;
		
		private int _Denomination;
		
		private decimal _TotalValue;
		
		private decimal _IssuedValue;
		
		private decimal _RejectedValue;
		
		public rsp_GetCashDispenserItemsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CassetteID", DbType="Int NOT NULL")]
		public int CassetteID
		{
			get
			{
				return this._CassetteID;
			}
			set
			{
				if ((this._CassetteID != value))
				{
					this._CassetteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CassetteName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CassetteName
		{
			get
			{
				return this._CassetteName;
			}
			set
			{
				if ((this._CassetteName != value))
				{
					this._CassetteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CassetteAlias", DbType="VarChar(50)")]
		public string CassetteAlias
		{
			get
			{
				return this._CassetteAlias;
			}
			set
			{
				if ((this._CassetteAlias != value))
				{
					this._CassetteAlias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denomination", DbType="Int NOT NULL")]
		public int Denomination
		{
			get
			{
				return this._Denomination;
			}
			set
			{
				if ((this._Denomination != value))
				{
					this._Denomination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalValue", DbType="Decimal(18,0) NOT NULL")]
		public decimal TotalValue
		{
			get
			{
				return this._TotalValue;
			}
			set
			{
				if ((this._TotalValue != value))
				{
					this._TotalValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssuedValue", DbType="Decimal(18,0) NOT NULL")]
		public decimal IssuedValue
		{
			get
			{
				return this._IssuedValue;
			}
			set
			{
				if ((this._IssuedValue != value))
				{
					this._IssuedValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectedValue", DbType="Decimal(18,0) NOT NULL")]
		public decimal RejectedValue
		{
			get
			{
				return this._RejectedValue;
			}
			set
			{
				if ((this._RejectedValue != value))
				{
					this._RejectedValue = value;
				}
			}
		}
	}

    public partial class rsp_GetCashDispenserErrorCodes
    {

        private int _CDEC_ID;

        private int _CDEC_ErrorCode;

        private string _CDEC_Description;

        private bool _CDEC_ApplicableToLowerTray;

        private bool _CDEC_ApplicableToUpperTray;

        public rsp_GetCashDispenserErrorCodes()
        {
        }

        [Column(Storage = "_CDEC_ID", DbType = "Int NOT NULL")]
        public int CDECID
        {
            get
            {
                return this._CDEC_ID;
            }
            set
            {
                if ((this._CDEC_ID != value))
                {
                    this._CDEC_ID = value;
                }
            }
        }

        [Column(Storage = "_CDEC_ErrorCode", DbType = "Int NOT NULL")]
        public int CDEC_ErrorCode
        {
            get
            {
                return this._CDEC_ErrorCode;
            }
            set
            {
                if ((this._CDEC_ErrorCode != value))
                {
                    this._CDEC_ErrorCode = value;
                }
            }
        }

        [Column(Storage = "_CDEC_Description", DbType = "VarChar(4000)")]
        public string CDECDescription
        {
            get
            {
                return this._CDEC_Description;
            }
            set
            {
                if ((this._CDEC_Description != value))
                {
                    this._CDEC_Description = value;
                }
            }
        }

        [Column(Storage = "_CDEC_ApplicableToLowerTray", DbType = "Bit")]
        public bool CDECApplicableToLowerTray
        {
            get
            {
                return this._CDEC_ApplicableToLowerTray;
            }
            set
            {
                if ((this._CDEC_ApplicableToLowerTray != value))
                {
                    this._CDEC_ApplicableToLowerTray = value;
                }
            }
        }

        [Column(Storage = "_CDEC_ApplicableToUpperTray", DbType = "Bit")]
        public bool CDECApplicableToUpperTray
        {
            get
            {
                return this._CDEC_ApplicableToUpperTray;
            }
            set
            {
                if ((this._CDEC_ApplicableToUpperTray != value))
                {
                    this._CDEC_ApplicableToUpperTray = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
