USE [Enterprise]
GO

IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ASPNET_SP_MapUserToRole]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ASPNET_SP_MapUserToRole]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ASPNET_SP_MapUserToRole](@RoleID INT, @UserID INT)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM [ROLE] WHERE SecurityRoleID = @RoleID)
	BEGIN
		SELECT 'ERROR:02' AS RESULT
	END
	ELSE
	BEGIN
		IF EXISTS (SELECT 1 FROM [USER] WHERE SecurityUserID = @UserID )	
		BEGIN
			SELECT 'ERROR:01' AS RESULT
		END
		ELSE
		BEGIN
			IF EXISTS (SELECT 1 FROM [UserRole_lnk] WHERE SecurityUserID = @UserID AND SecurityRoleID = @RoleID )	
			BEGIN
				SELECT 'ERROR:03' AS RESULT
			END
			ELSE
			BEGIN
				INSERT INTO [UserRole_lnk] (SecurityUserID, SecurityRoleID) VALUES (@UserID, @RoleID)
				SELECT 'SUCCESS' AS RESULT
			END
		END
	END
END 

GO

