USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[rsp_GetManualDropAlertDetails]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[rsp_GetManualDropAlertDetails]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[rsp_GetManualDropAlertDetails] 
(
	@Region INT = 0,
	@SiteID INT=0,
	@StackerLevel INT=0, 	
	@StaffID INT=0
)
AS
BEGIN

DECLARE @VersionName VARCHAR(20) 
DECLARE @EmployeeName NVARCHAR(100)    
SELECT TOP 1 @VersionName=VersionName FROM VersionHistory  ORDER BY 1 DESC
SELECT @EmployeeName = Staff_First_Name + ' ' + Staff_Last_Name FROM Staff WHERE (@StaffID<>0 AND Staff_ID=@StaffID)

SELECT     
 I.INSTALLATION_ID,     
 I.BAR_POSITION_ID,     
 I.MACHINE_ID,  
 @VersionName AS VERSIONNAME,    
 BP.BAR_POSITION_NAME,   	   
 S.SITE_ID,     
 ISNULL(SCA.Sub_Company_Area_Name,'') AS SUB_COMPANY_AREA_NAME,    
 S.SITE_NAME,
 S.SITE_CODE,     
 ISNULL(SCR.Sub_Company_Region_Name,'') AS SUB_COMPANY_REGION_NAME,     
 SC.SUB_COMPANY_ID,  
 SC.Sub_Company_Name,   
 C.COMPANY_ID,     
 C.COMPANY_NAME,   
 M.Machine_Stock_No AS AssetNumber,
 ST.STACKER_ID,    
 ST.STACKERSIZE,    
 SL.BILLQTY+SL.TICKETQTY AS TOTALQTY,    
 (((SL.BILLQTY+SL.TICKETQTY)*100)/ST.STACKERSIZE) AS PERCENTAGE,
ISNULL(@EmployeeName,'') AS EmployeeName    
FROM     
 INSTALLATION I     
 INNER JOIN MACHINE M ON M.MACHINE_ID=I.MACHINE_ID
 INNER JOIN BAR_POSITION BP ON BP.BAR_POSITION_ID=I.BAR_POSITION_ID
 INNER JOIN [SITE] S ON S.SITE_ID=BP.SITE_ID
 INNER JOIN SUB_COMPANY SC ON SC.SUB_COMPANY_ID=S.SUB_COMPANY_ID    
 INNER JOIN COMPANY C ON C.COMPANY_ID=SC.COMPANY_ID
 INNER JOIN STACKER ST ON ST.STACKER_ID=M.STACKER_ID
 INNER JOIN STACKERLEVEL SL ON SL.INSTALLATION_NO=I.INSTALLATION_ID    
 LEFT JOIN Sub_Company_Region SCR ON SCR.SUB_COMPANY_REGION_ID=S.SUB_COMPANY_REGION_ID
 LEFT JOIN Sub_Company_Area SCA ON SCA.SUB_COMPANY_AREA_ID=S.SUB_COMPANY_AREA_ID     
WHERE
 (((SL.BILLQTY+SL.TICKETQTY)*100)/ST.STACKERSIZE)>=@StackerLevel    
 AND     
 ((@Region=0) OR (@Region<>0 AND S.Sub_Company_Region_id=@Region))    
 AND     
 ((@SiteID=0) OR (@SiteID<>0 AND S.SITE_ID=@SiteID)) 
 AND I.Installation_End_Date IS NULL  
 ORDER BY INSTALLATION_ID 
END 

GO

