USE [Enterprise]
GO

IF EXISTS (
       SELECT *
       FROM   sys.objects
       WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[rsp_GetTermsInfoForTermsProfileID]')
              AND TYPE IN (N'P', N'PC')
   )
    DROP PROCEDURE [dbo].[rsp_GetTermsInfoForTermsProfileID]
GO

CREATE PROCEDURE [dbo].[rsp_GetTermsInfoForTermsProfileID](@TermsProfileID INT)
AS
BEGIN
	SELECT TP.Terms_Profile_ID,
	       TP.Terms_Group_ID,
	       TP.Machine_Type_ID,
	       TP.Terms_Profile_Name,
	       TP.Terms_Profile_Partners_Supplier_Index,
	       TP.Terms_Profile_Partners_Supplier_Use,
	       TP.Terms_Profile_Partners_Supplier_Cash_Destination,
	       TP.Terms_Profile_Partners_Supplier_Deferred_Remittance,
	       TP.Terms_Profile_Partners_Supplier_Type,
	       TP.Terms_Profile_Partners_Supplier_Value,
	       TP.Terms_Profile_Partners_Supplier_Value_Guaranteed,
	       TP.Terms_Profile_Partners_Supplier_Share,
	       TP.Terms_Profile_Partners_Supplier_Share_Guaranteed,
	       TP.Terms_Profile_Partners_Supplier_Share_Schedule,
	       TP.Terms_Profile_Partners_Supplier_Rent_Schedule,
	       TP.Terms_Profile_Partners_Supplier_Guarantor,
	       TP.Terms_Profile_Partners_Supplier_Guarantor_Percentage,
	       TP.Terms_Profile_Partners_Site_Index,
	       TP.Terms_Profile_Partners_Site_Use,
	       TP.Terms_Profile_Partners_Site_Cash_Destination,
	       TP.Terms_Profile_Partners_Site_Deferred_Remittance,
	       TP.Terms_Profile_Partners_Site_Type,
	       TP.Terms_Profile_Partners_Site_Value,
	       TP.Terms_Profile_Partners_Site_Value_Guaranteed,
	       TP.Terms_Profile_Partners_Site_Share,
	       TP.Terms_Profile_Partners_Site_Share_Guaranteed,
	       TP.Terms_Profile_Partners_Site_Guarantor,
	       TP.Terms_Profile_Partners_Site_Guarantor_Percentage,
	       TP.Terms_Profile_Partners_Group_Index,
	       TP.Terms_Profile_Partners_Group_Use,
	       TP.Terms_Profile_Partners_Group_Cash_Destination,
	       TP.Terms_Profile_Partners_Group_Deferred_Remittance,
	       TP.Terms_Profile_Partners_Group_Type,
	       TP.Terms_Profile_Partners_Group_Value,
	       TP.Terms_Profile_Partners_Group_Value_Guaranteed,
	       TP.Terms_Profile_Partners_Group_Share,
	       TP.Terms_Profile_Partners_Group_Share_Guaranteed,
	       TP.Terms_Profile_Partners_Group_Guarantor,
	       TP.Terms_Profile_Partners_Group_Guarantor_Percentage,
	       TP.Terms_Profile_Partners_Sec_Group_Index,
	       TP.Terms_Profile_Partners_Sec_Group_Use,
	       TP.Terms_Profile_Partners_Sec_Group_Cash_Destination,
	       TP.Terms_Profile_Partners_Sec_Group_Deferred_Remittance,
	       TP.Terms_Profile_Partners_Sec_Group_Type,
	       TP.Terms_Profile_Partners_Sec_Group_Value,
	       TP.Terms_Profile_Partners_Sec_Group_Value_Guaranteed,
	       TP.Terms_Profile_Partners_Sec_Group_Share,
	       TP.Terms_Profile_Partners_Sec_Group_Share_Guaranteed,
	       TP.Terms_Profile_Partners_Sec_Group_Guarantor,
	       TP.Terms_Profile_Partners_Sec_Group_Guarantor_Percentage,
	       TP.Terms_Profile_VAT_Output_Index,
	       TP.Terms_Profile_VAT_Output_Use,
	       TP.Terms_Profile_VAT_Output_Cash_Destination,
	       TP.Terms_Profile_VAT_Output_Deferred_Remittance,
	       TP.Terms_Profile_VAT_Supplier_Index,
	       TP.Terms_Profile_VAT_Supplier_Use,
	       TP.Terms_Profile_VAT_Supplier_Cash_Destination,
	       TP.Terms_Profile_VAT_Supplier_Deferred_Remittance,
	       TP.Terms_Profile_VAT_Supplier_Paid_By,
	       TP.Terms_Profile_VAT_Supplier_Guarantor,
	       TP.Terms_Profile_VAT_Site_Index,
	       TP.Terms_Profile_VAT_Site_Use,
	       TP.Terms_Profile_VAT_Site_Cash_Destination,
	       TP.Terms_Profile_VAT_Site_Deferred_Remittance,
	       TP.Terms_Profile_VAT_Site_Paid_By,
	       TP.Terms_Profile_VAT_Site_Guarantor,
	       TP.Terms_Profile_VAT_Group_Index,
	       TP.Terms_Profile_VAT_Group_Use,
	       TP.Terms_Profile_VAT_Group_Cash_Destination,
	       TP.Terms_Profile_VAT_Group_Deferred_Remittance,
	       TP.Terms_Profile_VAT_Group_Paid_By,
	       TP.Terms_Profile_VAT_Group_Guarantor,
	       TP.Terms_Profile_VAT_Sec_Group_Index,
	       TP.Terms_Profile_VAT_Sec_Group_Use,
	       TP.Terms_Profile_VAT_Sec_Group_Cash_Destination,
	       TP.Terms_Profile_VAT_Sec_Group_Deferred_Remittance,
	       TP.Terms_Profile_VAT_Sec_Group_Paid_By,
	       TP.Terms_Profile_VAT_Sec_Group_Guarantor,
	       TP.Terms_Profile_Other_Licence_Index,
	       TP.Terms_Profile_Other_Licence_Use,
	       TP.Terms_Profile_Other_Licence_Vat,
	       TP.Terms_Profile_Other_Licence_Cash_Destination,
	       TP.Terms_Profile_Other_Licence_Deferred_Remittance,
	       TP.Terms_Profile_Other_Licence_Charge,
	       TP.Terms_Profile_Other_Licence_Paid_By,
	       TP.Terms_Profile_Other_Licence_Guarantor,
	       TP.Terms_Profile_Other_Licence_Frequency,
	       TP.Terms_Profile_Other_Prize_Index,
	       TP.Terms_Profile_Other_Prize_Use,
	       TP.Terms_Profile_Other_Prize_Vat,
	       TP.Terms_Profile_Other_Prize_Cash_Destination,
	       TP.Terms_Profile_Other_Prize_Deferred_Remittance,
	       TP.Terms_Profile_Other_Prize_Charge,
	       TP.Terms_Profile_Other_Prize_Paid_By,
	       TP.Terms_Profile_Other_Prize_Guarantor,
	       TP.Terms_Profile_Other_Prize_Frequency,
	       TP.Terms_Profile_Other_Consultancy_Index,
	       TP.Terms_Profile_Other_Consultancy_Use,
	       TP.Terms_Profile_Other_Consultancy_Vat,
	       TP.Terms_Profile_Other_Consultancy_Cash_Destination,
	       TP.Terms_Profile_Other_Consultancy_Deferred_Remittance,
	       TP.Terms_Profile_Other_Consultancy_Charge,
	       TP.Terms_Profile_Other_Consultancy_Paid_By,
	       TP.Terms_Profile_Other_Consultancy_Guarantor,
	       TP.Terms_Profile_Other_Consultancy_Frequency,
	       TP.Terms_Profile_Other_Royalty_Index,
	       TP.Terms_Profile_Other_Royalty_Use,
	       TP.Terms_Profile_Other_Royalty_Vat,
	       TP.Terms_Profile_Other_Royalty_Cash_Destination,
	       TP.Terms_Profile_Other_Royalty_Deferred_Remittance,
	       TP.Terms_Profile_Other_Royalty_Charge,
	       TP.Terms_Profile_Other_Royalty_Paid_By,
	       TP.Terms_Profile_Other_Royalty_Guarantor,
	       TP.Terms_Profile_Other_Royalty_Frequency,
	       TP.Terms_Profile_Other_Other1_Index,
	       TP.Terms_Profile_Other_Other1_Name,
	       TP.Terms_Profile_Other_Other1_Use,
	       TP.Terms_Profile_Other_Other1_Vat,
	       TP.Terms_Profile_Other_Other1_Cash_Destination,
	       TP.Terms_Profile_Other_Other1_Deferred_Remittance,
	       TP.Terms_Profile_Other_Other1_Charge,
	       TP.Terms_Profile_Other_Other1_Paid_By,
	       TP.Terms_Profile_Other_Other1_Guarantor,
	       TP.Terms_Profile_Other_Other1_Frequency,
	       TP.Terms_Profile_Other_Other2_Index,
	       TP.Terms_Profile_Other_Other2_Name,
	       TP.Terms_Profile_Other_Other2_Use,
	       TP.Terms_Profile_Other_Other2_Vat,
	       TP.Terms_Profile_Other_Other2_Cash_Destination,
	       TP.Terms_Profile_Other_Other2_Deferred_Remittance,
	       TP.Terms_Profile_Other_Other2_Charge,
	       TP.Terms_Profile_Other_Other2_Paid_By,
	       TP.Terms_Profile_Other_Other2_Guarantor,
	       TP.Terms_Profile_Other_Other2_Frequency,
	       TP.Terms_Profile_London_Rent_Use,
	       TP.Terms_Profile_London_Rent_Charge,
	       TP.Terms_Profile_GPT_Index,
	       TP.Terms_Profile_GPT_Use,
	       TP.Terms_Profile_GPT_Cash_Destination,
	       TP.Terms_Profile_GPT_Deferred_Remittance,
	       MT.Machine_Type_Code,
	       TG.Terms_Group_Name
	FROM   Terms_Profile TP
	       LEFT JOIN Machine_Type MT
	            ON  TP.Machine_Type_ID = MT.Machine_Type_ID
	       INNER JOIN Terms_Group TG
	            ON  TP.Terms_Group_ID = TG.Terms_Group_ID
	WHERE  TP.Terms_Profile_ID = @TermsProfileID
END  
GO
