/************************************************************
 * Code formatted by SoftTree SQL Assistant © v4.8.29
 * Time: 23/05/13 16:51:20
 ************************************************************/

USE [Enterprise]
GO

IF EXISTS (
       SELECT *
       FROM   sys.objects
       WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[rsp_GetHQ_User_AccessInfo]')
              AND TYPE IN (N'P', N'PC')
   )
    DROP PROCEDURE [dbo].[rsp_GetHQ_User_AccessInfo]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO


/*
EXEC [rsp_GetHQ_User_AccessInfo] 1

Original Query:
--SELECT Staff_ID,UserTableID, [user].Password, Staff.Depot_ID, Staff.Supplier_ID, HQ_User_Access.* FROM Staff INNER JOIN (HQ_User_Access INNER JOIN User_Group ON HQ_User_Access.HQ_User_Access_ID = User_Group.HQ_User_Access_ID)  ON Staff.User_Group_ID = User_Group.User_Group_ID INNER JOIN [user] ON  Staff.UserTableID=[user].SecurityUserID WHERE Staff.Staff_Username = 'admin' AND [user].Password = 'Yb1gxg2ftgzI/HdnZp1AoQ==' AND Staff_Terminated = 0
*/

CREATE PROCEDURE [dbo].[rsp_GetHQ_User_AccessInfo](@SecurityUserID AS INT)
AS
	/*****************************************************************************************************
DESCRIPTION		: Procedure to Get user access information
CREATED DATE	: 2012-10-30 06:03:51.280
MODULE          : Main Screen   
CHANGE HISTORY	:
------------------------------------------------------------------------------------------------------
AUTHOR                              DESCRIPTON                                            MODIFIED DATE
------------------------------------------------------------------------------------------------------
Venkatesan Haridass                Enterprise Rewrite                                     2012-10-30
------------------------------------------------------------------------------------------------------

*****************************************************************************************************/

BEGIN
	SELECT Col,
	       VALUE
	FROM   (
	           SELECT --HQ_User_Access.HQ_User_Access_ID
	                  HQ_User_Access.HQ_Admin,
	                  HQ_User_Access.HQ_Admin_Customers,
	                  HQ_User_Access.HQ_Admin_Customers_Company,
	                  HQ_User_Access.HQ_Admin_Customers_Company_Edit,
	                  HQ_User_Access.HQ_Admin_Customers_Sub,
	                  HQ_User_Access.HQ_Admin_Customers_Sub_Edit,
	                  HQ_User_Access.HQ_Admin_Customers_Site,
	                  HQ_User_Access.HQ_Admin_Customers_Site_Edit,
	                  HQ_User_Access.HQ_Admin_Customers_Zone,
	                  HQ_User_Access.HQ_Admin_Customers_Zone_Edit,
	                  HQ_User_Access.HQ_Admin_Customers_Bar,
	                  HQ_User_Access.HQ_Admin_Customers_Bar_Edit,
	                  HQ_User_Access.HQ_Admin_Groups,
	                  HQ_User_Access.HQ_Admin_Groups_Edit,
	                  HQ_User_Access.HQ_Admin_Users,
	                  HQ_User_Access.HQ_Admin_Users_ViewAll,
	                  HQ_User_Access.HQ_Admin_Users_Edit,
	                  HQ_User_Access.HQ_Admin_Users_EditAll,
	                  HQ_User_Access.HQ_Admin_Settings,
	                  HQ_User_Access.HQ_Admin_Settings_Edit,
	                  HQ_User_Access.HQ_Admin_Routes,
	                  HQ_User_Access.HQ_Admin_Routes_Edit,
	                  HQ_User_Access.HQ_Admin_Depot,
	                  HQ_User_Access.HQ_Admin_Depot_Edit,
	                  HQ_User_Access.HQ_Admin_Operator,
	                  HQ_User_Access.HQ_Admin_Operator_Edit,
	                  HQ_User_Access.HQ_Admin_Accessories,
	                  HQ_User_Access.HQ_Admin_Calendar,
	                  HQ_User_Access.HQ_Admin_Exception,
	                  HQ_User_Access.HQ_Admin_Op_Cost,
	                  HQ_User_Access.HQ_Admin_Licence,
	                  HQ_User_Access.HQ_Admin_OpenHours,
	                  HQ_User_Access.HQ_Admin_SiteUpdate,
	                  HQ_User_Access.HQ_Browse,
	                  HQ_User_Access.HQ_Search,
	                  HQ_User_Access.HQ_Sites,
	                  HQ_User_Access.HQ_Engineers,
	                  HQ_User_Access.HQ_Engineers_CreateCall,
	                  HQ_User_Access.HQ_Engineers_CreateCall_Edit,
	                  HQ_User_Access.HQ_Engineers_Current,
	                  HQ_User_Access.HQ_Engineers_Current_Edit,
	                  HQ_User_Access.HQ_Engineers_Current_Close,
	                  HQ_User_Access.HQ_Engineers_Closed,
	                  HQ_User_Access.HQ_Engineers_Closed_Edit,
	                  HQ_User_Access.HQ_Engineers_Engineers,
	                  HQ_User_Access.HQ_Engineers_Engineers_Edit,
	                  HQ_User_Access.HQ_Engineers_Schedule,
	                  HQ_User_Access.HQ_Engineers_Schedule_Edit,
	                  HQ_User_Access.HQ_Engineers_Notes,
	                  HQ_User_Access.HQ_Engineers_Notes_History,
	                  HQ_User_Access.HQ_Stock,
	                  HQ_User_Access.HQ_Stock_Edit,
	                  HQ_User_Access.HQ_Stock_MachinesInUse,
	                  HQ_User_Access.HQ_Stock_MachinesInUse_Edit,
	                  HQ_User_Access.HQ_Stock_MachinesUnderRepair,
	                  HQ_User_Access.HQ_Stock_MachinesUnderRepair_Edit,
	                  HQ_User_Access.HQ_Stock_UsableStock,
	                  HQ_User_Access.HQ_Stock_UsableStock_Edit,
	                  HQ_User_Access.HQ_Stock_MachinesOnOrder,
	                  HQ_User_Access.HQ_Stock_MachinesOnOrder_Edit,
	                  HQ_User_Access.HQ_Stock_Depreciation,
	                  HQ_User_Access.HQ_Stock_Model_Sets,
	                  HQ_User_Access.HQ_Stock_Component,
	                  HQ_User_Access.HQ_Stock_Supplier,
	                  HQ_User_Access.HQ_Stock_Manufacturer,
	                  HQ_User_Access.HQ_Stock_Machine_Type,
	                  HQ_User_Access.HQ_Stock_Machine_Model,
	                  HQ_User_Access.HQ_Stock_Movement_History,
	                  HQ_User_Access.HQ_Stock_Machine_History,
	                  HQ_User_Access.HQ_Stock_Convert_Machine,
	                  HQ_User_Access.HQ_Logistics,
	                  HQ_User_Access.HQ_Logistics_Create,
	                  HQ_User_Access.HQ_Logistics_Positions,
	                  HQ_User_Access.HQ_Logistics_Models,
	                  HQ_User_Access.HQ_Logistics_Assets,
	                  HQ_User_Access.HQ_Logistics_Authorise,
	                  HQ_User_Access.HQ_Logistics_Complete,
	                  HQ_User_Access.HQ_Licensing,
	                  HQ_User_Access.HQ_Licensing_Purchase,
	                  HQ_User_Access.HQ_Licensing_Sell,
	                  HQ_User_Access.HQ_CDS,
	                  HQ_User_Access.HQ_CDS_Edit,
	                  HQ_User_Access.HQ_CDS_Programs_View_Tab,
	                  HQ_User_Access.HQ_CDS_Programs_View_Tab_Edit,
	                  HQ_User_Access.HQ_CDS_Programs_Edit_Tab,
	                  HQ_User_Access.HQ_CDS_Programs_Edit_Tab_Edit,
	                  HQ_User_Access.HQ_CDS_Stock_Tab,
	                  HQ_User_Access.HQ_CDS_Stock_Tab_Edit,
	                  HQ_User_Access.HQ_CDS_Label_Tab,
	                  HQ_User_Access.HQ_CDS_Label_Tab_Edit,
	                  HQ_User_Access.HQ_Comms,
	                  HQ_User_Access.HQ_Comms_CE,
	                  HQ_User_Access.HQ_Comms_Site,
	                  HQ_User_Access.HQ_Comms_Site_Accept,
	                  HQ_User_Access.[HQ_Comms_Site_Accept_Edit],
	                  HQ_User_Access.HQ_Comms_Site_Inbox,
	                  HQ_User_Access.HQ_Comms_Site_Inbox_Edit,
	                  HQ_User_Access.HQ_Comms_Site_Outbox,
	                  HQ_User_Access.HQ_Comms_Site_Outbox_Edit,
	                  HQ_User_Access.HQ_Comms_Mail,
	                  HQ_User_Access.HQ_Comms_Messages,
	                  HQ_User_Access.HQ_Comms_Move_Rej,
	                  HQ_User_Access.HQ_Comms_Col_Rejects,
	                  HQ_User_Access.HQ_Comms_New_Move_Rej,
	                  HQ_User_Access.HQ_Comms_New_Col_Rej,
	                  HQ_User_Access.HQ_Comms_Amedis,
	                  HQ_User_Access.HQ_Comms_Export,
	                  HQ_User_Access.HQ_Shedules,
	                  HQ_User_Access.HQ_Shedules_Edit,
	                  HQ_User_Access.HQ_Collections,
	                  HQ_User_Access.HQ_Collections_docket,
	                  HQ_User_Access.HQ_Collections_Collection_Manager,
	                  HQ_User_Access.HQ_Collections_Col_Mismatch,
	                  HQ_User_Access.HQ_Collections_Edit_Remarks,
	                  HQ_User_Access.HQ_Collections_Royalty,
	                  HQ_User_Access.HQ_Financial,
	                  HQ_User_Access.HQ_Financial_Edit,
	                  HQ_User_Access.HQ_Financial_Terms,
	                  HQ_User_Access.HQ_Financial_Terms_Edit,
	                  HQ_User_Access.HQ_Financial_Terms_Summary,
	                  HQ_User_Access.HQ_Financial_Shares,
	                  HQ_User_Access.HQ_Financial_Shares_Edit,
	                  HQ_User_Access.HQ_Financial_Rent,
	                  HQ_User_Access.HQ_Financial_Rent_Edit,
	                  HQ_User_Access.HQ_Financial_Export,
	                  HQ_User_Access.HQ_Financial_Site_Budget,
	                  HQ_User_Access.HQ_Financial_Giro_Rec,
	                  HQ_User_Access.HQ_Reports,
	                  HQ_User_Access.HQ_Reports_Edit,
	                  HQ_User_Access.HQ_Analysis,
	                  HQ_User_Access.HQ_Analysis_Edit,
	                  HQ_User_Access.HQ_Analysis_Collection,
	                  HQ_User_Access.HQ_Analysis_Collection_Edit,
	                  HQ_User_Access.HQ_Analysis_Sessional,
	                  HQ_User_Access.HQ_Analysis_Sessional_Edit,
	                  HQ_User_Access.HQ_Analysis_Comparison,
	                  HQ_User_Access.HQ_Analysis_Comparison_Edit,
	                  HQ_User_Access.HQ_Analysis_Advanced,
	                  HQ_User_Access.HQ_Analysis_Advanced_Edit,
	                  HQ_User_Access.HQ_SUPER,
	                  HQ_User_Access.HQ_Collections_Edit,
	                  HQ_User_Access.HQ_Customer_Access_View_Entire_Database,
	                  HQ_User_Access.HQ_Collections_Site_Viewer_Input,
	                  HQ_User_Access.HQ_Security,
	                  HQ_User_Access.HQ_Security_Edit_EDC_Machine_Code,
	                  HQ_User_Access.HQ_Security_Edit_Meter_Readings,
	                  HQ_User_Access.HQ_Comms_CE_Reject,
	                  HQ_User_Access.HQ_Comms_Site_Reject,
	                  HQ_User_Access.HQ_Collections_Manager_Input,
	                  HQ_User_Access.HQ_Collections_Manager_Var_Rec,
	                  HQ_User_Access.HQ_Collections_Manager_Col_Rec,
	                  HQ_User_Access.HQ_Collections_Site_Viewer_Input_New,
	                  HQ_User_Access.HQ_Movements_Site_Viewer_Fudge,
	                  HQ_User_Access.hq_stock_machine_control,
	                  HQ_User_Access.HQ_EventViewer,
	                  HQ_User_Access.HQ_Calendar_Edit,
	                  HQ_User_Access.HQ_Sites_MC_Control,
	                  HQ_User_Access.HQ_Admin_SiteSettings,
	                  HQ_User_Access.HQ_Admin_AAMSConfig,
	                  HQ_User_Access.HQ_Gamelibrary,
	                  HQ_User_Access.HQ_Stock_BuyMachine,
	                  HQ_User_Access.HQ_Stock_NewInstall,
	                  HQ_User_Access.HQ_Stock_EditInstall,
	                  HQ_User_Access.HQ_Stock_CloseInstall,
	                  HQ_User_Access.HQ_Stock_GameLibrary,
	                  HQ_User_Access.HQ_Stock_TerminateMachine,
	                  HQ_User_Access.HQ_AuditViewer,
	                  HQ_User_Access.HQ_CashierTransactions,
	                  HQ_User_Access.HQ_Admin_Customers_Company_New,
	                  HQ_User_Access.HQ_Admin_Customers_Sub_New,
	                  HQ_User_Access.HQ_Admin_Customers_Site_New,
	                  HQ_User_Access.HQ_Admin_Customers_Zone_New,
	                  HQ_User_Access.HQ_Admin_Customers_Bar_New,
	                  HQ_User_Access.HQ_Admin_Customers_Bar_BulkCopyPositions,
	                  HQ_User_Access.HQ_Guardian,
	                  HQ_User_Access.HQ_CashierTransactions_ViewNumberTickets,
	                  HQ_User_Access.HQ_Financial_Period_End,
	                  HQ_User_Access.HQ_DataSheet,
	                  HQ_User_Access.HQ_Admin_Declaration,
	                  HQ_User_Access.HQ_Admin_StackerLevelAlert,
	                  HQ_User_Access.HQ_Admin_DropSchedule,
	                  HQ_User_Access.HQ_Admin_Access,
	                  HQ_User_Access.HQ_Admin_StackerFeature,
	                  HQ_User_Access.HQ_Admin_SiteLicensing,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_LicenseGen,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_LicenseGen_RuleInfo,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_LicenseGen_KeyGen,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_ViewCancelLicense,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_LicenseHistory,
	                  HQ_User_Access.HQ_Admin_SiteLicensing_LicenseGen_RuleInfo_AddorEditRule,
	                  HQ_User_Access.HQ_Asset_Template,
	                  HQ_User_Access.HQ_Template_Create,
	                  HQ_User_Access.HQ_Template_Edit,
	                  HQ_User_Access.HQ_Template_Delete,
					  HQ_User_Access.HQ_Admin_AGSCombination,
					  HQ_User_Access.HQ_Stock_Asset_Export,
					  HQ_User_Access.HQ_Stock_Asset_Import,
					  HQ_User_Access.HQ_Financial_ShareHolder,
	                  HQ_User_Access.HQ_Financial_ProfitShare,
	                  HQ_User_Access.HQ_Financial_ExpenseShare,
	                  HQ_User_Access.HQ_Financial_ReadLiquidation,
	                  HQ_Financial_CollectionLiquidation,
	                  HQ_Admin_EmployeeCard,
	                  HQ_Financial_ReadLiquidationReport,
	                  HQ_SystemAudit,
	                  HQ_DataCommsAudit,
	                  HQ_User_Access.HQ_Admin_VaultInterface,
	                  HQ_User_Access.HQ_Admin_CreateVault,
	                  HQ_User_Access.HQ_Admin_EditCreateVault, 
	                  HQ_User_Access.HQ_Admin_VaultDeclaration, 
	                  HQ_User_Access.HQ_Admin_EditVaultDeclaration, 
	                  HQ_User_Access.HQ_Admin_AuditVaultDeclaration, 
	                  HQ_User_Access.HQ_Admin_EditAuditVaultDeclaration,
	                  HQ_User_Access.HQ_Admin_TerminateVault,
	                  HQ_User_Access.HQ_Admin_AuthorizeProfitShare,
	                  HQ_User_Access.HQ_Admin_SiteUserAccess,
	                  HQ_User_Access.HQ_Admin_MeterAdjustment,
					  HQ_User_Access.HQ_Admin_Customers_Bar_EnableDisable,
					  HQ_Financial_TermsProfiles,
					  HQ_Financial_ShareSchedules,
					  HQ_Financial_TermsSummary,
					  HQ_Financial_PeriodEndTermsProcessor,
					  HQ_Engineer_EmailAlerts,
					  HQ_Engineer_AlertAudit,
					  HQ_Engineers_EventViewer,
					  HQ_User_Access.HQ_Admin_Users_ResetPassword,
					  HQ_User_Access.HQ_Admin_Users_Unlock,
	                  HQ_User_Access.HQ_GMU_Events,
					  HQ_User_Access.HQ_GMU_Events_Add,
					  HQ_User_Access.HQ_GMU_Events_Edit 
	           FROM   Staff WITH (NOLOCK)
	                  INNER JOIN (
	                           HQ_User_Access WITH (NOLOCK) 
	                           INNER JOIN User_Group WITH (NOLOCK) ON 
	                           HQ_User_Access.HQ_User_Access_ID = User_Group.HQ_User_Access_ID
	                       )
	                       ON  Staff.User_Group_ID = User_Group.User_Group_ID
	                  INNER JOIN [user] WITH (NOLOCK)
	                       ON  Staff.UserTableID = [user].SecurityUserID
	           WHERE  Staff.UserTableID = @SecurityUserID
	       ) AS SourceTable
	       UNPIVOT(
	           VALUE FOR Col IN --    (HQ_User_Access_ID
	                            (HQ_Admin, HQ_Admin_Customers, 
	                            HQ_Admin_Customers_Company, 
	                            HQ_Admin_Customers_Company_Edit, 
	                            HQ_Admin_Customers_Sub, 
	                            HQ_Admin_Customers_Sub_Edit, 
	                            HQ_Admin_Customers_Site, 
	                            HQ_Admin_Customers_Site_Edit, 
	                            HQ_Admin_Customers_Zone, 
	                            HQ_Admin_Customers_Zone_Edit, 
	                            HQ_Admin_Customers_Bar, 
	                            HQ_Admin_Customers_Bar_Edit, HQ_Admin_Groups, 
	                            HQ_Admin_Groups_Edit, HQ_Admin_Users, 
	                            HQ_Admin_Users_ViewAll, HQ_Admin_Users_Edit, 
	                            HQ_Admin_Users_EditAll, HQ_Admin_Settings, 
	                            HQ_Admin_Settings_Edit, HQ_Admin_Routes, 
	                            HQ_Admin_Routes_Edit, HQ_Admin_Depot, 
	                            HQ_Admin_Depot_Edit, HQ_Admin_Operator, 
	                            HQ_Admin_Operator_Edit, HQ_Admin_Accessories, 
	                            HQ_Admin_Calendar, HQ_Admin_Exception, 
	                            HQ_Admin_Op_Cost, HQ_Admin_Licence, 
	                            HQ_Admin_OpenHours, HQ_Admin_SiteUpdate, 
	                            HQ_Browse, HQ_Search, HQ_Sites, HQ_Engineers, 
	                            HQ_Engineers_CreateCall, HQ_Engineers_CreateCall_Edit,
	                            HQ_Engineers_Current, HQ_Engineers_Current_Edit, 
	                            HQ_Engineers_Current_Close, HQ_Engineers_Closed, 
	                            HQ_Engineers_Closed_Edit, HQ_Engineers_Engineers, 
	                            HQ_Engineers_Engineers_Edit, 
	                            HQ_Engineers_Schedule, 
	                            HQ_Engineers_Schedule_Edit, HQ_Engineers_Notes, 
	                            HQ_Engineers_Notes_History, HQ_Stock, 
	                            HQ_Stock_Edit, HQ_Stock_MachinesInUse, 
	                            HQ_Stock_MachinesInUse_Edit, 
	                            HQ_Stock_MachinesUnderRepair, 
	                            HQ_Stock_MachinesUnderRepair_Edit, 
	                            HQ_Stock_UsableStock, HQ_Stock_UsableStock_Edit, 
	                            HQ_Stock_MachinesOnOrder, 
	                            HQ_Stock_MachinesOnOrder_Edit, 
	                            HQ_Stock_Depreciation, HQ_Stock_Model_Sets, 
	                            HQ_Stock_Component, HQ_Stock_Supplier, 
	                            HQ_Stock_Manufacturer, HQ_Stock_Machine_Type, 
	                            HQ_Stock_Machine_Model, 
	                            HQ_Stock_Movement_History, 
	                            HQ_Stock_Machine_History, 
	                            HQ_Stock_Convert_Machine, HQ_Logistics, 
	                            HQ_Logistics_Create, HQ_Logistics_Positions, 
	                            HQ_Logistics_Models, HQ_Logistics_Assets, 
	                            HQ_Logistics_Authorise, HQ_Logistics_Complete, 
	                            HQ_Licensing, HQ_Licensing_Purchase, 
	                            HQ_Licensing_Sell, HQ_CDS, HQ_CDS_Edit, 
	                            HQ_CDS_Programs_View_Tab, 
	                            HQ_CDS_Programs_View_Tab_Edit, 
	                            HQ_CDS_Programs_Edit_Tab, 
	                            HQ_CDS_Programs_Edit_Tab_Edit, HQ_CDS_Stock_Tab, 
	                            HQ_CDS_Stock_Tab_Edit, HQ_CDS_Label_Tab, 
	                            HQ_CDS_Label_Tab_Edit, HQ_Comms, HQ_Comms_CE, 
	                            HQ_Comms_Site, HQ_Comms_Site_Accept, 
	                            [HQ_Comms_Site_Accept_Edit], 
	                            HQ_Comms_Site_Inbox, HQ_Comms_Site_Inbox_Edit, 
	                            HQ_Comms_Site_Outbox, HQ_Comms_Site_Outbox_Edit, 
	                            HQ_Comms_Mail, HQ_Comms_Messages, 
	                            HQ_Comms_Move_Rej, HQ_Comms_Col_Rejects, 
	                            HQ_Comms_New_Move_Rej, HQ_Comms_New_Col_Rej, 
	                            HQ_Comms_Amedis, HQ_Comms_Export, HQ_Shedules, 
	                            HQ_Shedules_Edit, HQ_Collections, 
	                            HQ_Collections_docket, 
	                            HQ_Collections_Collection_Manager, 
	                            HQ_Collections_Col_Mismatch, 
	                            HQ_Collections_Edit_Remarks, 
	                            HQ_Collections_Royalty, HQ_Financial, 
	                            HQ_Financial_Edit, HQ_Financial_Terms, 
	                            HQ_Financial_Terms_Edit, 
	                            HQ_Financial_Terms_Summary, HQ_Financial_Shares, 
	                            HQ_Financial_Shares_Edit, HQ_Financial_Rent, 
	                            HQ_Financial_Rent_Edit, HQ_Financial_Export, 
	                            HQ_Financial_Site_Budget, HQ_Financial_Giro_Rec, 
	                            HQ_Reports, HQ_Reports_Edit, HQ_Analysis, 
	                            HQ_Analysis_Edit, HQ_Analysis_Collection, 
	                            HQ_Analysis_Collection_Edit, 
	                            HQ_Analysis_Sessional, 
	                            HQ_Analysis_Sessional_Edit, 
	                            HQ_Analysis_Comparison, 
	                            HQ_Analysis_Comparison_Edit, 
	                            HQ_Analysis_Advanced, HQ_Analysis_Advanced_Edit, 
	                            HQ_SUPER, HQ_Collections_Edit, 
	                            HQ_Customer_Access_View_Entire_Database, 
	                            HQ_Collections_Site_Viewer_Input, HQ_Security, 
	                            HQ_Security_Edit_EDC_Machine_Code, 
	                            HQ_Security_Edit_Meter_Readings, 
	                            HQ_Comms_CE_Reject, HQ_Comms_Site_Reject, 
	                            HQ_Collections_Manager_Input, 
	                            HQ_Collections_Manager_Var_Rec, 
	                            HQ_Collections_Manager_Col_Rec, 
	                            HQ_Collections_Site_Viewer_Input_New, 
	                            HQ_Movements_Site_Viewer_Fudge, 
	                            hq_stock_machine_control, HQ_EventViewer, 
	                            HQ_Calendar_Edit, HQ_Sites_MC_Control, 
	                            HQ_Admin_SiteSettings, HQ_Admin_AAMSConfig, 
	                            HQ_Gamelibrary, HQ_Stock_BuyMachine, 
	                            HQ_Stock_NewInstall, HQ_Stock_EditInstall, 
	                            HQ_Stock_CloseInstall, HQ_Stock_GameLibrary, 
	                            HQ_Stock_TerminateMachine, HQ_AuditViewer, 
	                            HQ_CashierTransactions, 
	                            HQ_Admin_Customers_Company_New, 
	                            HQ_Admin_Customers_Sub_New, 
	                            HQ_Admin_Customers_Site_New, 
	                            HQ_Admin_Customers_Zone_New, 
	                            HQ_Admin_Customers_Bar_New, 
	                            HQ_Admin_Customers_Bar_BulkCopyPositions, 
	                            HQ_Guardian, 
	                            HQ_CashierTransactions_ViewNumberTickets, 
	                            HQ_Financial_Period_End, HQ_DataSheet, 
	                            HQ_Admin_Declaration, HQ_Admin_StackerLevelAlert, 
	                            HQ_Admin_DropSchedule, HQ_Admin_Access, 
	                            HQ_Admin_StackerFeature, HQ_Admin_SiteLicensing, 
	                            HQ_Admin_SiteLicensing_LicenseGen, 
	                            HQ_Admin_SiteLicensing_LicenseGen_RuleInfo, 
	                            HQ_Admin_SiteLicensing_LicenseGen_KeyGen, 
	                            HQ_Admin_SiteLicensing_ViewCancelLicense, 
	                            HQ_Admin_SiteLicensing_LicenseHistory, 
	                            HQ_Admin_SiteLicensing_LicenseGen_RuleInfo_AddorEditRule,
	                            HQ_Asset_Template,
	                            HQ_Template_Create,
	                            HQ_Template_Edit,
	                            HQ_Template_Delete,
	                            HQ_Admin_AGSCombination,
	                            HQ_Stock_Asset_Export,
	                            HQ_Stock_Asset_Import,
	                            HQ_Financial_ShareHolder, 
	                            HQ_Financial_ProfitShare, 
	                            HQ_Financial_ExpenseShare, 
	                            HQ_Financial_ReadLiquidation, 
	                            HQ_Financial_CollectionLiquidation, 
	                            HQ_Admin_EmployeeCard,
	                            HQ_Admin_VaultInterface,
	                            HQ_Financial_ReadLiquidationReport,
	                            HQ_SystemAudit,
	                            HQ_DataCommsAudit,
	                            HQ_Admin_CreateVault,
								HQ_Admin_EditCreateVault, 
								HQ_Admin_VaultDeclaration, 
								HQ_Admin_EditVaultDeclaration, 
								HQ_Admin_AuditVaultDeclaration, 
								HQ_Admin_EditAuditVaultDeclaration,
								HQ_Admin_TerminateVault,
	                            HQ_Admin_AuthorizeProfitShare,
	                            HQ_Admin_SiteUserAccess,
	                            HQ_Admin_MeterAdjustment,
								HQ_Admin_Customers_Bar_EnableDisable,
								HQ_Financial_TermsProfiles,
								HQ_Financial_ShareSchedules,
								HQ_Financial_TermsSummary,
								HQ_Financial_PeriodEndTermsProcessor,
							HQ_Engineer_EmailAlerts,
							HQ_Engineer_AlertAudit,
							HQ_Engineers_EventViewer,
								HQ_Admin_Users_ResetPassword,
								HQ_Admin_Users_Unlock,								
							   HQ_GMU_Events,
							  HQ_GMU_Events_Add,
							  HQ_GMU_Events_Edit 
	                  
	                            )
	       ) AS unpvt
	ORDER BY
	       1 ASC
END
GO