USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[rsp_ExportCollectionForXML]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[rsp_ExportCollectionForXML]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[rsp_ExportCollectionForXML]   
(@pvcCollection_No VARCHAR(10) , @SiteCode VARCHAR(10) )  
AS  
BEGIN  
DECLARE @collectionXML XML  
DECLARE @ResultXML XML  
DECLARE @Site_Code VARCHAR(50)  
DECLARE @User VARCHAR(50)  
  
SELECT @Site_Code = Site_Code FROM [Site]  
  
SET  @collectionXML =  (select Batch.Batch_ID,  
Batch.Batch_Ref,  
CONVERT(DATETIME, Batch.Batch_Date + ' ' + Batch.Batch_Time, 101) AS Batch_Date,  
Batch.Schedule_ID,  
Batch.Batch_Received_All,  
Batch.Staff_ID,  
Batch.Batch_Company_Bank,  
Batch.Batch_Supplier_Bank,  
Batch.Batch_LOS,  
Batch.Batch_OverBank,  
Batch.Batch_Supplier_Error,  
Batch.Batch_Company_Error,  
Batch.Batch_Collector_ID,  
Batch.Batch_Memo,  
Batch.Batch_Route_Reconciliation_Completed,  
Batch.Batch_Bank_Reconciliation_Completed,  
Batch.Batch_Process_Route_Completed,  
Batch.Batch_User_Name,  
Batch.Batch_Audit_Day_ID,  
Batch.Batch_Audit_Week_ID,  
Batch.Batch_Audit_Period_ID,  
Batch.Batch_Audit_Year_ID,  
CONVERT(DATETIME, Batch.batch_Date_Performed, 101) as batch_Date_Performed,  
Batch.batch_name,  
Batch.Collection_Batch_Advance,  
Batch.Batch_Advance,  
Batch.Batch_Negative_Net,  
Installation.Installation_id AS Installation_No,   
@Site_Code AS Site_Code,   
@User AS [User_Name],   
collection.Collection_ID,  
collection.Diary_Entry_ID,  
collection.Batch_ID,  
collection.Installation_ID,  
collection.New_Collection_ID,  
collection.Collection_Replacement,  
CONVERT(DATETIME, collection.Collection_Date + ' ' + collection.Collection_Time, 101) AS Collection_Date,  
--collection.Collection_Time,  
CONVERT(DATETIME, collection.Collection_Date_Of_Collection + ' ' + collection.Collection_Time_Of_Collection, 101) AS Collection_Date_Of_Collection,
collection.Collection_Reconciled_Against_Route,  
collection.Collection_Reconciled_Against_Collector,  
CONVERT(DATETIME, collection.Previous_Collection_Date + ' ' + collection.Previous_Collection_Time, 101) AS Previous_Collection_Date,  
--collection.Previous_Collection_Time,  
COLLECTION.CASH_IN_1P,
collection.CASH_IN_2P,  
collection.CASH_IN_5P,  
collection.CASH_IN_10P,  
collection.CASH_IN_20P,  
collection.CASH_IN_50P,  
collection.CASH_IN_100P,  
collection.CASH_IN_200P,  
collection.CASH_IN_500P,  
collection.CASH_IN_1000P,  
collection.CASH_IN_2000P,  
collection.CASH_IN_5000P,  
collection.CASH_IN_10000P,  
collection.CASH_IN_20000P,  
collection.CASH_IN_50000P,  
collection.CASH_IN_100000P,  
collection.CASH_IN_200000P,  
collection.CASH_IN_500000P,  
collection.CASH_IN_1000000P,  
collection.TOKEN_IN_5P,  
collection.TOKEN_IN_10P,  
collection.TOKEN_IN_20P,  
collection.TOKEN_IN_50P,  
collection.TOKEN_IN_100P,  
collection.TOKEN_IN_200P,  
collection.TOKEN_IN_500P,  
collection.TOKEN_IN_1000P,  
collection.CASH_OUT_1P, 
collection.CASH_OUT_2P,  
collection.CASH_OUT_5P,  
collection.CASH_OUT_10P,  
collection.CASH_OUT_20P,  
collection.CASH_OUT_50P,  
collection.CASH_OUT_100P,  
collection.CASH_OUT_200P,  
collection.CASH_OUT_500P,  
collection.CASH_OUT_1000P,  
collection.CASH_OUT_2000P,  
collection.CASH_OUT_5000P,  
collection.CASH_OUT_10000P,  
collection.CASH_OUT_20000P,  
collection.CASH_OUT_50000P,  
collection.CASH_OUT_100000P,  
collection.CASH_OUT_200000P,  
collection.CASH_OUT_500000P,  
collection.CASH_OUT_1000000P,  
collection.TOKEN_OUT_5P,  
collection.TOKEN_OUT_10P,  
collection.TOKEN_OUT_20P,  
collection.TOKEN_OUT_50P,  
collection.TOKEN_OUT_100P,  
collection.TOKEN_OUT_200P,  
collection.TOKEN_OUT_500P,  
collection.TOKEN_OUT_1000P,  
collection.CASH_REFILL_5P,  
collection.CASH_REFILL_10P,  
collection.CASH_REFILL_20P,  
collection.CASH_REFILL_50P,  
collection.CASH_REFILL_100P,  
collection.CASH_REFILL_200P,  
collection.CASH_REFILL_500P,  
collection.CASH_REFILL_1000P,  
collection.CASH_REFILL_2000P,  
collection.CASH_REFILL_5000P,  
collection.CASH_REFILL_10000P,  
collection.CASH_REFILL_20000P,  
collection.CASH_REFILL_50000P,  
collection.CASH_REFILL_100000P,  
collection.CASH_REFILL_200000P,  
collection.CASH_REFILL_500000P,  
collection.CASH_REFILL_1000000P,  
collection.TOKEN_REFILL_5P,  
collection.TOKEN_REFILL_10P,  
collection.TOKEN_REFILL_20P,  
collection.TOKEN_REFILL_50P,  
collection.TOKEN_REFILL_100P,  
collection.TOKEN_REFILL_200P,  
collection.TOKEN_REFILL_500P,  
collection.TOKEN_REFILL_1000P,  
collection.CREDITS_TAKEN,  
collection.Declaration,  
collection.CounterCashIn,  
collection.CounterCashOut,  
collection.CounterTokensIn,  
collection.CounterTokensOut,  
collection.CounterRefill,  
collection.CounterPrize,  
collection.CounterTournamentPlay,  
collection.CounterJukeBoxPlay,  
collection.Play_Meter,  
collection.FreePlays,  
collection.CashCollected,  
collection.TokensCollected,  
collection.Cash_Collected_1p, 
collection.Cash_Collected_2p,  
collection.Cash_Collected_5p,  
collection.Cash_Collected_10p,  
collection.Cash_Collected_20p,  
collection.Cash_Collected_50p,  
collection.Cash_Collected_100p,  
collection.Cash_Collected_200p,  
collection.Cash_Collected_500p,  
collection.Cash_Collected_1000p,  
collection.Cash_Collected_2000p,  
collection.Cash_Collected_5000p,  
collection.Cash_Collected_10000p,  
collection.Cash_Collected_20000p,  
collection.Cash_Collected_50000p,  
collection.Cash_Collected_100000p,  
collection.Cash_Collected_200000p,  
collection.Cash_Collected_500000p,  
collection.Cash_Collected_1000000p,  
collection.CashRefills,  
collection.TokenRefills,  
collection.Cash_Refills_2p,  
collection.Cash_Refills_5p,  
collection.Cash_Refills_10p,  
collection.Cash_Refills_20p,  
collection.Cash_Refills_50p,  
collection.Cash_Refills_100p,  
collection.Cash_Refills_200p,  
collection.Cash_Refills_500p,  
collection.Cash_Refills_1000p,  
collection.Cash_Refills_2000p,  
collection.Cash_Refills_5000p,  
collection.Cash_Refills_10000p,  
collection.Cash_Refills_20000p,  
collection.Cash_Refills_50000p,  
collection.Cash_Refills_100000p,  
collection.Cash_Refills_200000p,  
collection.Cash_Refills_500000p,  
collection.Cash_Refills_1000000p,  
collection.Tokens_Collected_5P,  
collection.Tokens_Collected_10P,  
collection.Tokens_Collected_20P,  
collection.Tokens_Collected_50P,  
collection.Tokens_Collected_100P,  
collection.Tokens_Collected_200P,  
collection.Tokens_Collected_500P,  
collection.Tokens_Collected_1000P,  
collection.CounterCashInElectronic,  
collection.CounterCashOutElectronic,  
collection.CounterTokensInElectronic,  
collection.CounterTokensOutElectronic,  
collection.JackpotsOut,  
collection.PreviousCounterCashIn,  
collection.PreviousCounterCashOut,  
collection.PreviousCounterTokensIn,  
collection.PreviousCounterTokensOut,  
collection.PreviousCounterCashInElectronic,  
collection.PreviousCounterCashOutElectronic,  
collection.PreviousCounterTokensInElectronic,  
collection.PreviousCounterTokensOutElectronic,  
collection.Dud_Coins_100p,  
collection.Dud_Coins_50p,  
collection.Dud_Coins_20p,  
collection.Dud_Coins_10p,  
collection.Dud_Coins_5p,  
collection.Token_Float_Increase,  
collection.Decrease,  
collection.Down_Days,  
collection.No_of_Claims,  
collection.No_of_ServiceCalls,  
collection.Remarks,  
collection.Collection_Processed_Through_Terms,  
collection.Collection_Transactions_Created,  
collection.Collection_Terms_Invalid,  
collection.Collection_Terms_Invalid_Ignore,  
collection.Collection_RDC_CoinsIn,  
collection.Collection_RDC_CoinsOut,  
collection.Collection_RDC_CoinsDrop,  
collection.Collection_RDC_Handpay,  
collection.Collection_RDC_ExternalCredit,  
collection.Collection_RDC_GamesBet,  
collection.Collection_RDC_GamesWon,  
collection.Collection_RDC_Notes,  
collection.Collection_Meters_CoinsIn,  
collection.Collection_Meters_CoinsOut,  
collection.Collection_Meters_CoinsDrop,  
collection.Collection_Meters_Handpay,  
collection.Collection_Meters_ExternalCredit,  
collection.Collection_Meters_GamesBet,  
collection.Collection_Meters_GamesWon,  
collection.Collection_Meters_Notes,  
collection.Collection_Treasury_Defloat,  
collection.Previous_Meters_Coins_In,  
collection.Previous_Meters_Coins_Out,  
collection.Previous_Meters_Coin_Drop,  
collection.Previous_Meters_Handpay,  
collection.Previous_Meters_External_Credit,  
collection.Previous_Meters_Games_Bet,  
collection.Previous_Meters_Games_Won,  
collection.Previous_Meters_Notes,  
collection.PreviousCounterPrize,  
collection.PreviousCounterJackpotsOut,  
collection.PreviousCounterTournament,  
collection.PreviousCounterJukebox,  
collection.PreviousCounterRefills,  
collection.Collection_Treasury_Handpay,  
collection.Wallbox_Calculated_Cash,  
collection.Collection_Replacement_Status,  
collection.Collection_Report_Status,  
collection.Collection_Source,  
collection.Collection_RDC_VTP,  
collection.Collection_RDC_Machine_Code,  
collection.Collection_RDC_Secondary_Machine_Code,  
collection.Collection_Index_Last_9_Days,  
collection.Collection_Index_Last_9_Gross,  
collection.Collection_EDC_Status,  
collection.CASH_FLOAT_CHANGE_1p,  
collection.CASH_FLOAT_CHANGE_2p,  
collection.CASH_FLOAT_CHANGE_5p,  
collection.CASH_FLOAT_CHANGE_10p,  
collection.CASH_FLOAT_CHANGE_20p,  
collection.CASH_FLOAT_CHANGE_50p,  
collection.CASH_FLOAT_CHANGE_100p,  
collection.CASH_FLOAT_CHANGE_200p,  
collection.CASH_FLOAT_CHANGE_500p,  
collection.CASH_FLOAT_CHANGE_1000p,  
collection.CASH_FLOAT_TOTAL,  
collection.COLLECTION_RDC_CANCELLED_CREDITS,  
collection.COLLECTION_RDC_GAMES_LOST,  
collection.COLLECTION_RDC_GAMES_SINCE_POWER_UP,  
collection.COLLECTION_RDC_TRUE_COIN_IN,  
collection.COLLECTION_RDC_TRUE_COIN_OUT,  
collection.COLLECTION_RDC_CURRENT_CREDITS,  
collection.CounterVTP,  
collection.PreviousCounterVTP,  
collection.CounterChange,  
collection.PreviousCounterChange,  
collection.CounterNotes,  
collection.PreviousCounterNotes,  
collection.DeclaredTicketQty,  
collection.DeclaredTicketValue,  
collection.COLLECTION_RDC_JACKPOT,  
collection.DeclaredTicketPrintedQty,  
collection.DeclaredTicketPrintedValue,  
collection.COLLECTION_RDC_TICKETS_INSERTED_VALUE,  
collection.COLLECTION_RDC_TICKETS_PRINTED_VALUE,  
collection.progressive_win_value,  
collection.progressive_win_Handpay_value,  
collection.Progressive_Value_Declared,  
collection.Collection_Defloat_Collection,  
collection.Mystery_Machine_Paid,  
collection.Mystery_Attendant_Paid,  
collection.RDC_TICKETS_INSERTED_NONCASHABLE_VALUE,  
collection.RDC_TICKETS_PRINTED_NONCASHABLE_VALUE,  
collection.Promo_Cashable_EFT_IN,  
collection.Promo_Cashable_EFT_OUT,  
collection.NonCashable_EFT_IN,  
collection.NonCashable_EFT_OUT,  
collection.Cashable_EFT_IN,  
collection.Cashable_EFT_OUT,  
CONVERT(DATETIME, collection.Previous_Collection_Date_Of_Collection + ' ' + collection.Previous_Collection_Time_Of_Collection, 101) AS Previous_Collection_Date_Of_Collection ,
cash_in_1p.*
from (batch   
join collection on batch.batch_id = collection.batch_id)  
join Installation ON collection.Installation_id=Installation.Installation_id  
left outer join cash_in_1p ON collection.collection_id = cash_in_1p.collection_no
WHERE batch.Batch_Ref = @SiteCode + ',' + CAST(@pvcCollection_No AS VARCHAR(10))  
order by collection.collection_id  
for xml AUTO,ELEMENTS,ROOT('Batch'))  
  
select @collectionXML  
END


GO

