USE [Enterprise]
GO

IF EXISTS (
       SELECT *
       FROM   sys.objects
       WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[usp_InsertSetting]')
              AND TYPE IN (N'P', N'PC')
   )
    DROP PROCEDURE [dbo].[usp_InsertSetting]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE dbo.usp_InsertSetting
@SettingsProfile_Description VARCHAR(200),
@SettingName VARCHAR(200),
@SettingValue VARCHAR(200)
AS
BEGIN
	IF @SettingName = 'LIQUIDATION_ENABLED'
	BEGIN
	    SET @SettingName = 'SGVI_ENABLED'
	END
	
	IF @SettingName = 'VOUCHER_CREATE_TIMEOUT'
	BEGIN
	    SET @SettingName = 'TICKET_CREATE_TIMEOUT'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLEVOUCHER'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLEVOUCHER'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLEREFUNDRECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLEREFUNDRECEIPT'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_REQUIRES_HEADCASHIER_SIG'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_REQUIRES_HEADCASHIER_SIG'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_REQUIRES_MANAGER_SIG'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_REQUIRES_MANAGER_SIG'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLEHANDPAYRECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLEHANDPAYRECEIPT'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLEISSUERECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLEISSUERECEIPT'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLESHORTPAYRECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLESHORTPAYRECEIPT'
	END
	
	IF @SettingName = 'VOUCHER_DB_NAME'
	BEGIN
	    SET @SettingName = 'TICKET_DB_NAME'
	END
	
	IF @SettingName = 'SAS_UPDATEVOUCHERDETAILS'
	BEGIN
	    SET @SettingName = 'SAS_UPDATETICKETDETAILS'
	END
	
	IF @SettingName = 'PROMO_VOUCHER_CODE'
	BEGIN
	    SET @SettingName = 'PROMO_TICKET_CODE'
	END
	
	IF @SettingName = 'VOUCHERVALIDATION_FILLSCREEN'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATION_FILLSCREEN'
	END
	
	IF @SettingName = 'REDEEMVOUCHERCUSTOMER_MIN'
	BEGIN
	    SET @SettingName = 'REDEEMTICKETCUSTOMER_MIN'
	END
	
	IF @SettingName = 'REDEEMVOUCHERCUSTOMER_MAX'
	BEGIN
	    SET @SettingName = 'REDEEMTICKETCUSTOMER_MAX'
	END
	
	IF @SettingName = 'REDEEMVOUCHERCUSTOMER_BANKACCTNO'
	BEGIN
	    SET @SettingName = 'REDEEMTICKETCUSTOMER_BANKACCTNO'
	END
	
	IF @SettingName = 'ISSUEVOUCHERMAXVALUE'
	BEGIN
	    SET @SettingName = 'ISSUETICKETMAXVALUE'
	END
	
	IF @SettingName = 'ISSUE_VOUCHER_ENCRYPT_BARCODE'
	BEGIN
	    SET @SettingName = 'ISSUE_TICKET_ENCRYPT_BARCODE'
	END
	
	IF @SettingName = 'MANUALENTRYVOUCHERVALIDATION'
	BEGIN
	    SET @SettingName = 'MANUALENTRYTICKETVALIDATION'
	END
	
	IF @SettingName = 'REDEEMEXPIREDVOUCHER'
	BEGIN
	    SET @SettingName = 'REDEEMEXPIREDTICKET'
	END
	
	IF @SettingName = 'VOUCHERDECLARATIONMETHOD'
	BEGIN
	    SET @SettingName = 'TICKETDECLARATIONMETHOD'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLEPROGRESSIVEPAYOUTRECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLEPROGRESSIVEPAYOUTRECEIPT'
	END
	
	IF @SettingName = 'VOUCHER_EXPIRE'
	BEGIN
	    SET @SettingName = 'TICKET_EXPIRE'
	END
	
	IF @SettingName = 'HANDLE_EXCEPTIONVOUCHERS'
	BEGIN
	    SET @SettingName = 'HANDLE_EXCEPTIONTICKETS'
	END
	
	IF @SettingName = 'HANDLE_EXCEPTIONVOUCHERS_COUNTER'
	BEGIN
	    SET @SettingName = 'HANDLE_EXCEPTIONTICKETS_COUNTER'
	END
	
	IF @SettingName = 'VOUCHERVALIDATE_ENABLECUSTOMERRECEIPT'
	BEGIN
	    SET @SettingName = 'TICKETVALIDATE_ENABLECUSTOMERRECEIPT'
	END
	
	IF @SettingName = 'DEC_AUTOMARKACTIVEVOUCHERSASPD'
	BEGIN
	    SET @SettingName = 'DEC_AUTOMARKACTIVETICKETSASPD'
	END
	
	IF @SettingName = 'DEC_AUTOMARKEXCEPTIONVOUCHERASPD'
	BEGIN
	    SET @SettingName = 'DEC_AUTOMARKEXCEPTIONTICKETASPD'
	END
	
	IF @SettingName = 'VOIDEXPIREDVOUCHER'
	BEGIN
	    SET @SettingName = 'VOIDEXPIREDTICKET'
	END
	
	IF @SettingName = 'ISPROMOTIONALVOUCHERENABLED'
	BEGIN
	    SET @SettingName = 'ISPROMOTIONALTICKETENABLED'
	END
	
	IF @SettingName = 'MAXIMUMPROMOTIONALVOUCHERSCOUNT'
	BEGIN
	    SET @SettingName = 'MAXIMUMPROMOTIONALTICKETSCOUNT'
	END
	
	IF @SettingName = 'MAXIMUMPROMOTIONALVOUCHERAMOUNT'
	BEGIN
	    SET @SettingName = 'MAXIMUMPROMOTIONALTICKETAMOUNT'
	END
	
	IF @SettingName = 'DEFAULTPROMOTIONALVOUCHEREXPIREDAYS'
	BEGIN
	    SET @SettingName = 'DEFAULTPROMOTIONALTICKETEXPIREDAYS'
	END
	
	IF @SettingName = 'SAS_-- UPDATEVOUCHERDETAILS'
	BEGIN
	    SET @SettingName = 'SAS_-- UPDATETICKETDETAILS'
	END
	
	IF @SettingName = 'AUTOCALCDECVOUCHERSONEXPORT'
	BEGIN
	    SET @SettingName = 'AUTOCALCDECTICKETSONEXPORT'
	END
	
	IF @SettingName = 'VOUCHERANOMALIESENABLED'
	BEGIN
	    SET @SettingName = 'TICKETANOMALIESENABLED'
	END

	
	DECLARE @SettingProfile_ID  INT
	DECLARE @SettingMaster_ID   INT
	SELECT @SettingProfile_ID = SettingsProfile_ID
	FROM   SettingsProfile
	WHERE  SettingsProfile_Description = @SettingsProfile_Description
	
	SELECT @SettingMaster_ID = SettingsMaster_ID
	FROM   SettingsMaster
	WHERE  SettingsMaster_Name = @SettingName
	
	
	IF NOT EXISTS(
	       SELECT SettingsProfileItems_ID
	       FROM   SettingsProfileItems
	       WHERE  SettingsProfileItems_SettingsProfile_ID = @SettingProfile_ID
	              AND SettingsProfileItems_SettingsMaster_ID = @SettingMaster_ID
	   )
	    INSERT INTO SettingsProfileItems
	    VALUES
	      (
	        @SettingProfile_ID,
	        @SettingMaster_ID,
	        RTRIM(LTRIM(@SettingValue))
	      )
END
 

GO

