/************************************************************
 * Created by Bally Technologies © 2011
 * Time: 09/04/13 1:07:38 PM
 ************************************************************/

USE [Enterprise]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[usp_Insert_Meter_History_bkup]') AND TYPE IN (N'P', N'PC'))
    DROP PROCEDURE [dbo].[usp_Insert_Meter_History_bkup]
GO

USE [Enterprise]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------- 
--
-- Description: Inserts the records into Meter_History 
--
-- Inputs:     @Process (COLL/INST/READ/VTP), @Type(P-previous/C-Current), @LinkRefrence (InstallationNo/ReadNo/VTPNo)
--			   @Reference (Hour for VTP records/Null for others), @vInstalltionNo	
--
-- Outputs:     
--
-- =======================================================================
-- 
-- Revision History
-- 
-- Poorna K. 12/04/07   Created 
-- C.Taylor  16/11/07   moved update into insert, check on date making sure it's not blank or NULL.
-- Poorna K. 22/10/07	Added usp_Export_history call to insert the into EH to export to enterprise
-- Poorna K. 15/04/08   New Column(MH_Coins_In_Actual) to MH and FF, accommadated changes according to that
-- Poorna K. 25/06/08	Removed COLL records insertions in Export_History, this is done by usp_ExportHistory according to the batch number
-- Siva      16/07/08   removed VTP,READ insertions into export_history
--                      read will be done via usp_updatelastmeterdeltas
--                      vtp will be done via usp_updatehourlystatistics
--------------------------------------------------------------------------- 
CREATE PROC usp_Insert_Meter_History_bkup
(
  @Process VARCHAR(10),
  @Type VARCHAR(1),
  @LinkReference INT,
  @Reference VARCHAR(255) = 0,
  @vInstallation_No INT,
  @TheDateTime   DATETIME = NULL --getdate
)
AS
DECLARE @id INT
IF @TheDateTime IS NULL OR @TheDateTime = ''
    SET @TheDateTime = GETDATE()

INSERT INTO Meter_History ( MH_Process, MH_Type, MH_LinkReference, MH_Reference, MH_Installation_No, MH_Datetime, MH_PAYOUT_FLOAT_TOKEN, MH_PAYOUT_FLOAT_10P, MH_PAYOUT_FLOAT_20P, MH_PAYOUT_FLOAT_50P, MH_PAYOUT_FLOAT_100P, MH_CASH_IN_2P, MH_CASH_IN_5P, MH_CASH_IN_10P, MH_CASH_IN_20P, MH_CASH_IN_50P, MH_CASH_IN_100P, MH_CASH_IN_200P, MH_CASH_IN_500P, MH_CASH_IN_1000P, MH_CASH_IN_2000P, MH_CASH_IN_5000P, MH_CASH_IN_10000P, MH_CASH_IN_20000P, MH_CASH_IN_50000P, MH_CASH_IN_100000P, MH_TOKEN_IN_5P, MH_TOKEN_IN_10P, MH_TOKEN_IN_20P, MH_TOKEN_IN_50P, MH_TOKEN_IN_100P, MH_TOKEN_IN_200P, MH_TOKEN_IN_500P, MH_TOKEN_IN_1000P, MH_CASH_OUT_2P, MH_CASH_OUT_5P, MH_CASH_OUT_10P, MH_CASH_OUT_20P, MH_CASH_OUT_50P, MH_CASH_OUT_100P, MH_CASH_OUT_200P, MH_CASH_OUT_500P, MH_CASH_OUT_1000P, MH_CASH_OUT_2000P, MH_CASH_OUT_5000P, MH_CASH_OUT_10000P, MH_CASH_OUT_20000P, MH_CASH_OUT_50000P, MH_CASH_OUT_100000P, MH_TOKEN_OUT_5P, MH_TOKEN_OUT_10P, MH_TOKEN_OUT_20P, MH_TOKEN_OUT_50P, MH_TOKEN_OUT_100P, 
       MH_TOKEN_OUT_200P, MH_TOKEN_OUT_500P, MH_TOKEN_OUT_1000P, MH_CASH_REFILL_5P, MH_CASH_REFILL_10P, MH_CASH_REFILL_20P, MH_CASH_REFILL_50P, MH_CASH_REFILL_100P, MH_CASH_REFILL_200P, MH_CASH_REFILL_500P, MH_CASH_REFILL_1000P, MH_CASH_REFILL_2000P, MH_CASH_REFILL_5000P, MH_CASH_REFILL_10000P, MH_CASH_REFILL_20000P, MH_CASH_REFILL_50000P, MH_CASH_REFILL_100000P, MH_TOKEN_REFILL_5P, MH_TOKEN_REFILL_10P, MH_TOKEN_REFILL_20P, MH_TOKEN_REFILL_50P, MH_TOKEN_REFILL_100P, MH_TOKEN_REFILL_200P, MH_TOKEN_REFILL_500P, MH_TOKEN_REFILL_1000P, MH_COINS_IN, MH_COINS_OUT, MH_COIN_DROP, MH_HANDPAY, MH_EXTERNAL_CREDIT, MH_GAMES_BET, MH_GAMES_WON, MH_NOTES, MH_VTP, MH_CANCELLED_CREDITS, MH_GAMES_LOST, MH_GAMES_SINCE_POWER_UP, MH_TRUE_COIN_IN, MH_TRUE_COIN_OUT, MH_CURRENT_CREDITS, MH_JACKPOT, MH_BILL_1, MH_BILL_2, MH_BILL_5, MH_BILL_10, MH_BILL_20, MH_BILL_50, MH_BILL_100, MH_BILL_250, MH_BILL_10000, MH_BILL_20000, MH_BILL_50000, MH_BILL_100000, MH_TICKET_PRINTED_QTY, MH_TICKET_PRINTED_VALUE, 
       MH_TICKET_INSERTED_QTY, MH_TICKET_INSERTED_VALUE, MH_Progressive_Win_Value, MH_Progressive_Win_Handpay_Value, MH_TICKETS_PRINTED_NONCASHABLE_QTY, MH_TICKETS_PRINTED_NONCASHABLE_VALUE, MH_TICKETS_INSERTED_NONCASHABLE_QTY, MH_TICKETS_INSERTED_NONCASHABLE_VALUE, MH_Mystery_Machine_Paid, MH_Mystery_Attendant_Paid, MH_Promo_Cashable_EFT_IN, MH_Promo_Cashable_EFT_OUT, MH_NonCashable_EFT_IN, MH_NonCashable_EFT_OUT, MH_Cashable_EFT_IN, MH_Cashable_EFT_OUT )
SELECT @Process, @Type, @LinkReference, @Reference, @vInstallation_No, @TheDateTime, PAYOUT_FLOAT_TOKEN, PAYOUT_FLOAT_10P, PAYOUT_FLOAT_20P, PAYOUT_FLOAT_50P, PAYOUT_FLOAT_100P, CASH_IN_2P, CASH_IN_5P, CASH_IN_10P, CASH_IN_20P, CASH_IN_50P, CASH_IN_100P, CASH_IN_200P, CASH_IN_500P, CASH_IN_1000P, CASH_IN_2000P, CASH_IN_5000P, CASH_IN_10000P, CASH_IN_20000P, CASH_IN_50000P, CASH_IN_100000P, TOKEN_IN_5P, TOKEN_IN_10P, TOKEN_IN_20P, TOKEN_IN_50P, TOKEN_IN_100P, TOKEN_IN_200P, TOKEN_IN_500P, TOKEN_IN_1000P, CASH_OUT_2P, CASH_OUT_5P, CASH_OUT_10P, CASH_OUT_20P, CASH_OUT_50P, CASH_OUT_100P, CASH_OUT_200P, CASH_OUT_500P, CASH_OUT_1000P, CASH_OUT_2000P, CASH_OUT_5000P, CASH_OUT_10000P, CASH_OUT_20000P, CASH_OUT_50000P, CASH_OUT_100000P, TOKEN_OUT_5P, TOKEN_OUT_10P, TOKEN_OUT_20P, TOKEN_OUT_50P, TOKEN_OUT_100P, TOKEN_OUT_200P, TOKEN_OUT_500P, TOKEN_OUT_1000P, CASH_REFILL_5P, CASH_REFILL_10P, CASH_REFILL_20P, CASH_REFILL_50P, CASH_REFILL_100P, CASH_REFILL_200P, CASH_REFILL_500P, 
       CASH_REFILL_1000P, CASH_REFILL_2000P, CASH_REFILL_5000P, CASH_REFILL_10000P, CASH_REFILL_20000P, CASH_REFILL_50000P, CASH_REFILL_100000P, TOKEN_REFILL_5P, TOKEN_REFILL_10P, TOKEN_REFILL_20P, TOKEN_REFILL_50P, TOKEN_REFILL_100P, TOKEN_REFILL_200P, TOKEN_REFILL_500P, TOKEN_REFILL_1000P, COINS_IN, COINS_OUT, COIN_DROP, HANDPAY, EXTERNAL_CREDIT, GAMES_BET, GAMES_WON, NOTES, VTP, RDC_CANCELLED_CREDITS, RDC_GAMES_LOST, RDC_GAMES_SINCE_POWER_UP, RDC_TRUE_COIN_IN, RDC_TRUE_COIN_OUT, RDC_CURRENT_CREDITS, RDC_JACKPOT, RDC_BILL_1, RDC_BILL_2, RDC_BILL_5, RDC_BILL_10, RDC_BILL_20, RDC_BILL_50, RDC_BILL_100, RDC_BILL_250, RDC_BILL_10000, RDC_BILL_20000, RDC_BILL_50000, RDC_BILL_100000, RDC_TICKETS_PRINTED_CASHABLE_QTY, RDC_TICKETS_PRINTED_CASHABLE_VALUE, RDC_TICKETS_INSERTED_CASHABLE_QTY, RDC_TICKETS_INSERTED_CASHABLE_VALUE, Progressive_Win_Value, Progressive_Win_Handpay_Value, RDC_TICKETS_PRINTED_NONCASHABLE_QTY, RDC_TICKETS_PRINTED_NONCASHABLE_VALUE, RDC_TICKETS_INSERTED_NONCASHABLE_QTY, 
       RDC_TICKETS_INSERTED_NONCASHABLE_VALUE, Mystery_Machine_Paid, Mystery_Attendant_Paid, Promo_Cashable_EFT_IN, Promo_Cashable_EFT_OUT, NonCashable_EFT_IN, NonCashable_EFT_OUT, Cashable_EFT_IN, Cashable_EFT_OUT FROM Floor_Financials WHERE Installation_No = @vInstallation_No
		
SELECT @id = SCOPE_IDENTITY() 

IF (@Process NOT IN ('SNAP', 'COLL', 'READ', 'VTP'))
BEGIN
    IF @LinkReference IS NOT NULL
        EXEC usp_Export_History @id, NULL, 'METERHISTORY'
END

GO

