USE [Enterprise]
GO

IF EXISTS (
       SELECT *
       FROM   sys.objects
       WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[usp_UpdateCollectionDetailsWithTermsResults]')
              AND TYPE IN (N'P', N'PC')
   )
    DROP PROCEDURE [dbo].[usp_UpdateCollectionDetailsWithTermsResults] 
GO

CREATE PROCEDURE [dbo].[usp_UpdateCollectionDetailsWithTermsResults]    
(    
 @CollectionID int,    
 @Collection_Gross real,      
 @Collection_Days real,    
 @Collection_Prize_Value real,    
 @Collection_Unpaid_Shortfall real,    
 @Collection_Company_Share real,    
 @Collection_Supplier_Share real,    
 @Collection_Location_Share real,    
 @Collection_AMLD real,    
 @Collection_VAT_Output real,    
 @Collection_VAT_Company real,    
 @Collection_VAT_Supplier real,    
 @Collection_VAT_Location real,    
 @Collection_VAT_LOS real,    
 @Collection_VAT_Banked_To_Company real,    
 @Collection_VAT_Banked_To_Supplier real,    
 @Collection_Supplier_VAT_LOS real,    
 @Collection_Company_VAT_LOS real,    
 @Collection_Sec_Brewery_VAT_LOS real,    
 @Collection_Location_VAT_LOS real,    
 @Collection_Supplier_VAT_Banked_To_Company real,    
 @Collection_Company_VAT_Banked_To_Company real,    
 @Collection_Sec_Brewery_VAT_Banked_To_Company real,    
 @Collection_Location_VAT_Banked_To_Company real,    
 @Collection_Supplier_VAT_Banked_To_Supplier real,    
 @Collection_Company_VAT_Banked_To_Supplier real,    
 @Collection_Sec_Brewery_VAT_Banked_To_Supplier real,    
 @Collection_Location_VAT_Banked_To_Supplier real,    
 @Collection_Company_Share_LOS real,    
 @Collection_Supplier_Share_LOS real,    
 @Collection_Location_Share_LOS real,    
 @Collection_Banked_To_Company real,    
 @Collection_Banked_To_Supplier real,    
 @Collection_VAT_Sec_Brewery real,    
 @Collection_Sec_Brewery_Share_LOS real,    
 @Collection_Company_Share_Banked_To_Company real,    
 @Collection_Company_Share_Banked_To_Supplier real,    
 @Collection_Sec_Brewery_Share_Banked_To_Company real,    
 @Collection_Sec_Brewery_Share_Banked_To_Supplier real,    
 @Collection_Supplier_Share_Banked_To_Company real,    
 @Collection_Supplier_Share_Banked_To_Supplier real,    
 @Collection_Site_Share_Banked_To_Company real,    
 @Collection_Site_Share_Banked_To_Supplier real,    
 @Collection_Licence_Banked_To_Company real,    
 @Collection_Licence_Banked_To_Supplier real,    
 @Collection_Licence_LOS real,    
 @Collection_LOS real,    
 @Collection_Deferred_SiteGroupShareLOS_toGroup real,    
 @Collection_Deferred_SiteGroupShareBankedToSupplier_toGroup real,    
 @Collection_Deferred_SecSiteGroupShareLOS_toGroup real,    
 @Collection_Deferred_SecSiteGroupShareLOS_toSecGroup real,    
 @Collection_Deferred_SecSiteGroupShareBankedToSupplier_toGroup real,    
 @Collection_Deferred_SecSiteGroupShareBankedToSupplier_toSecGroup real,    
 @Collection_Deferred_SecSiteGroupShareBankedToGroup_toSecGroup real,    
 @Collection_Deferred_SupplierShareLOS_toSupplier real,    
 @Collection_Deferred_SupplierShareBankedToGroup_toSupplier real,    
 @Collection_Deferred_SiteShareBankedToSupplier_toSite real,    
 @Collection_Deferred_SiteShareBankedToSupplier_toGroup real,    
 @Collection_Deferred_SiteShareBankedToGroup_toSite real,    
 @Collection_Deferred_VATOutputLos_toSupplier real,    
 @Collection_Deferred_VATOutputLos_toGroup real,    
 @Collection_Deferred_VATOutputBankedToSupplier_toGroup real,    
 @Collection_Deferred_VATOutputBankedToSupplier_toSecGroup real,    
 @Collection_Deferred_VATOutputBankedToSupplier_toCustoms real,    
 @Collection_Deferred_VATOutputBankedToGroup_toSupplier real,    
 @Collection_Deferred_VATOutputBankedToGroup_toCustoms real,    
 @Collection_Deferred_VATSupplierLos_toSupplier real,    
 @Collection_Deferred_VATSupplierLos_toGroup real,    
 @Collection_Deferred_VATSupplierBankedToSupplier_toGroup real,    
 @Collection_Deferred_VATSupplierBankedToSupplier_toSecGroup real,    
 @Collection_Deferred_VATSupplierBankedToSupplier_toCustoms real,    
 @Collection_Deferred_VATSupplierBankedToGroup_toSupplier real,    
 @Collection_Deferred_VATSupplierBankedToGroup_toCustoms real,    
 @Collection_Deferred_VATSiteLos_toSupplier real,    
 @Collection_Deferred_VATSiteLos_toGroup real,    
 @Collection_Deferred_VATSiteLos_toCustoms real,    
 @Collection_Deferred_VATSiteBankedToSupplier_toGroup real,    
 @Collection_Deferred_VATSiteBankedToSupplier_toCustoms real,    
 @Collection_Deferred_VATSiteBankedToSupplier_toSite real,    
 @Collection_Deferred_VATSiteBankedToGroup_toSupplier real,    
 @Collection_Deferred_VATSiteBankedToGroup_toCustoms real,    
 @Collection_Deferred_VATGroupLos_toSupplier real,    
 @Collection_Deferred_VATGroupLos_toGroup real,    
 @Collection_Deferred_VATGroupBankedToSupplier_toGroup real,    
 @Collection_Deferred_VATGroupBankedToSupplier_toCustoms real,    
 @Collection_Deferred_VATGroupBankedToGroup_toSupplier real,    
 @Collection_Deferred_VATGroupBankedToGroup_toCustoms real,    
 @Collection_Deferred_VATSecGroupLos_toSupplier real,    
 @Collection_Deferred_VATSecGroupLos_toGroup real,    
 @Collection_Deferred_VATSecGroupLos_toSecGroup real,    
 @Collection_Deferred_VATSecGroupBankedToSupplier_toGroup real,    
 @Collection_Deferred_VATSecGroupBankedToSupplier_toSecGroup real,    
 @Collection_Deferred_VATSecGroupBankedToSupplier_toCustoms real,    
 @Collection_Deferred_VATSecGroupBankedToGroup_toSupplier real,    
 @Collection_Deferred_VATSecGroupBankedToGroup_toSecGroup real,    
 @Collection_Deferred_VATSecGroupBankedToGroup_toCustoms real,    
 @Collection_Deferred_LicenceChargeLOS_toSupplier real,    
 @Collection_Deferred_LicenceChargeLOS_toGroup real,    
 @Collection_Deferred_LicenceChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_LicenceChargeBankedToGroup_toSupplier real,    
 @Collection_Deferred_PrizeChargeLOS_toSupplier real,    
 @Collection_Deferred_PrizeChargeLOS_toGroup real,    
 @Collection_Deferred_PrizeChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_PrizeChargeBankedToGroup_toSupplier real,    
 @Collection_Deferred_ConsultancyChargeLOS_toSupplier real,    
 @Collection_Deferred_ConsultancyChargeLOS_toGroup real,    
 @Collection_Deferred_ConsultancyChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_ConsultancyChargeBankedToGroup_toSupplier real,    
 @Collection_Deferred_RoyaltyChargeLOS_toSupplier real,    
 @Collection_Deferred_RoyaltyChargeLOS_toGroup real,    
 @Collection_Deferred_RoyaltyChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_RoyaltyChargeBankedToGroup_toSupplier real,    
 @Collection_Deferred_Other1ChargeLOS_toSupplier real,    
 @Collection_Deferred_Other1ChargeLOS_toGroup real,    
 @Collection_Deferred_Other1ChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_Other1ChargeBankedToGroup_toSupplier real,    
 @Collection_Deferred_Other2ChargeLOS_toSupplier real,    
 @Collection_Deferred_Other2ChargeLOS_toGroup real,    
 @Collection_Deferred_Other2ChargeBankedToSupplier_toGroup real,    
 @Collection_Deferred_Other2ChargeBankedToGroup_toSupplier real    
)    
AS    
BEGIN    
 UPDATE Collection_Details    
 SET Collection_Gross = @Collection_Gross,    
  Collection_FloatSundries_LOS = Collection_Sundries + Collection_Sundries_Unsupported + Collection_Non_Supplier_Float_Recovered,    
  Collection_FloatSundries_Banked_To_Supplier = Collection_Supplier_Float_Recovered,    
  Collection_Days = @Collection_Days,    
  Collection_Prize_Value = @Collection_Prize_Value,    
  Collection_Unpaid_Shortfall = @Collection_Unpaid_Shortfall,    
  Collection_Company_Share = @Collection_Company_Share,    
  Collection_Supplier_Share = @Collection_Supplier_Share,    
  Collection_Location_Share = @Collection_Location_Share,    
  Collection_AMLD = @Collection_AMLD,    
  Collection_VAT_Output = @Collection_VAT_Output,    
  Collection_VAT_Company = @Collection_VAT_Company,    
  Collection_VAT_Supplier = @Collection_VAT_Supplier,    
  Collection_VAT_Location = @Collection_VAT_Location,    
  Collection_VAT_LOS = @Collection_VAT_LOS,    
  Collection_VAT_Banked_To_Company = @Collection_VAT_Banked_To_Company,    
  Collection_VAT_Banked_To_Supplier = @Collection_VAT_Banked_To_Supplier,    
  Collection_Supplier_VAT_LOS = @Collection_Supplier_VAT_LOS,    
  Collection_Company_VAT_LOS = @Collection_Company_VAT_LOS,    
  Collection_Sec_Brewery_VAT_LOS = @Collection_Sec_Brewery_VAT_LOS,    
  Collection_Location_VAT_LOS = @Collection_Location_VAT_LOS,    
  Collection_Supplier_VAT_Banked_To_Company = @Collection_Supplier_VAT_Banked_To_Company,    
  Collection_Company_VAT_Banked_To_Company = @Collection_Company_VAT_Banked_To_Company,    
  Collection_Sec_Brewery_VAT_Banked_To_Company = @Collection_Sec_Brewery_VAT_Banked_To_Company,    
  Collection_Location_VAT_Banked_To_Company = @Collection_Location_VAT_Banked_To_Company,    
  Collection_Supplier_VAT_Banked_To_Supplier = @Collection_Supplier_VAT_Banked_To_Supplier,    
  Collection_Company_VAT_Banked_To_Supplier = @Collection_Company_VAT_Banked_To_Supplier,    
  Collection_Sec_Brewery_VAT_Banked_To_Supplier = @Collection_Sec_Brewery_VAT_Banked_To_Supplier,    
  Collection_Location_VAT_Banked_To_Supplier = @Collection_Location_VAT_Banked_To_Supplier,    
  Collection_Company_Share_LOS = @Collection_Company_Share_LOS,    
  Collection_Supplier_Share_LOS = @Collection_Supplier_Share_LOS,    
  Collection_Location_Share_LOS = @Collection_Location_Share_LOS,    
  Collection_Banked_To_Company = @Collection_Banked_To_Company,    
  Collection_Banked_To_Supplier = @Collection_Banked_To_Supplier,    
  Collection_VAT_Sec_Brewery = @Collection_VAT_Sec_Brewery,    
  Collection_Sec_Brewery_Share_LOS = @Collection_Sec_Brewery_Share_LOS,    
  Collection_Company_Share_Banked_To_Company = @Collection_Company_Share_Banked_To_Company,    
  Collection_Company_Share_Banked_To_Supplier = @Collection_Company_Share_Banked_To_Supplier,    
  Collection_Sec_Brewery_Share_Banked_To_Company = @Collection_Sec_Brewery_Share_Banked_To_Company,    
  Collection_Sec_Brewery_Share_Banked_To_Supplier = @Collection_Sec_Brewery_Share_Banked_To_Supplier,    
  Collection_Supplier_Share_Banked_To_Company = @Collection_Supplier_Share_Banked_To_Company,    
  Collection_Supplier_Share_Banked_To_Supplier = @Collection_Supplier_Share_Banked_To_Supplier,    
  Collection_Site_Share_Banked_To_Company = @Collection_Site_Share_Banked_To_Company,    
  Collection_Site_Share_Banked_To_Supplier = @Collection_Site_Share_Banked_To_Supplier,    
  Collection_Licence_Banked_To_Company = @Collection_Licence_Banked_To_Company,    
  Collection_Licence_Banked_To_Supplier = @Collection_Licence_Banked_To_Supplier,    
  Collection_Licence_LOS = @Collection_Licence_LOS,    
  Collection_LOS = @Collection_LOS,    
  Collection_Deferred_SiteGroupShareLOS_toGroup = @Collection_Deferred_SiteGroupShareLOS_toGroup,    
  Collection_Deferred_SiteGroupShareBankedToSupplier_toGroup = @Collection_Deferred_SiteGroupShareBankedToSupplier_toGroup,    
  Collection_Deferred_SecSiteGroupShareLOS_toGroup = @Collection_Deferred_SecSiteGroupShareLOS_toGroup,    
  Collection_Deferred_SecSiteGroupShareLOS_toSecGroup = @Collection_Deferred_SecSiteGroupShareLOS_toSecGroup,    
  Collection_Deferred_SecSiteGroupShareBankedToSupplier_toGroup = @Collection_Deferred_SecSiteGroupShareBankedToSupplier_toGroup,    
  Collection_Deferred_SecSiteGroupShareBankedToSupplier_toSecGroup = @Collection_Deferred_SecSiteGroupShareBankedToSupplier_toSecGroup,    
  Collection_Deferred_SecSiteGroupShareBankedToGroup_toSecGroup = @Collection_Deferred_SecSiteGroupShareBankedToGroup_toSecGroup,    
  Collection_Deferred_SupplierShareLOS_toSupplier = @Collection_Deferred_SupplierShareLOS_toSupplier,    
  Collection_Deferred_SupplierShareBankedToGroup_toSupplier = @Collection_Deferred_SupplierShareBankedToGroup_toSupplier,    
  Collection_Deferred_SiteShareBankedToSupplier_toSite = @Collection_Deferred_SiteShareBankedToSupplier_toSite,    
  Collection_Deferred_SiteShareBankedToSupplier_toGroup = @Collection_Deferred_SiteShareBankedToSupplier_toGroup,    
  Collection_Deferred_SiteShareBankedToGroup_toSite = @Collection_Deferred_SiteShareBankedToGroup_toSite,    
  Collection_Deferred_VATOutputLos_toSupplier = @Collection_Deferred_VATOutputLos_toSupplier,    
  Collection_Deferred_VATOutputLos_toGroup = @Collection_Deferred_VATOutputLos_toGroup,    
  Collection_Deferred_VATOutputBankedToSupplier_toGroup = @Collection_Deferred_VATOutputBankedToSupplier_toGroup,    
  Collection_Deferred_VATOutputBankedToSupplier_toSecGroup = @Collection_Deferred_VATOutputBankedToSupplier_toSecGroup,    
  Collection_Deferred_VATOutputBankedToSupplier_toCustoms = @Collection_Deferred_VATOutputBankedToSupplier_toCustoms,    
  Collection_Deferred_VATOutputBankedToGroup_toSupplier = @Collection_Deferred_VATOutputBankedToGroup_toSupplier,    
  Collection_Deferred_VATOutputBankedToGroup_toCustoms = @Collection_Deferred_VATOutputBankedToGroup_toCustoms,    
  Collection_Deferred_VATSupplierLos_toSupplier = @Collection_Deferred_VATSupplierLos_toSupplier,    
  Collection_Deferred_VATSupplierLos_toGroup = @Collection_Deferred_VATSupplierLos_toGroup,    
  Collection_Deferred_VATSupplierBankedToSupplier_toGroup = @Collection_Deferred_VATSupplierBankedToSupplier_toGroup,    
  Collection_Deferred_VATSupplierBankedToSupplier_toSecGroup = @Collection_Deferred_VATSupplierBankedToSupplier_toSecGroup,    
  Collection_Deferred_VATSupplierBankedToSupplier_toCustoms = @Collection_Deferred_VATSupplierBankedToSupplier_toCustoms,    
  Collection_Deferred_VATSupplierBankedToGroup_toSupplier = @Collection_Deferred_VATSupplierBankedToGroup_toSupplier,    
  Collection_Deferred_VATSupplierBankedToGroup_toCustoms = @Collection_Deferred_VATSupplierBankedToGroup_toCustoms,    
  Collection_Deferred_VATSiteLos_toSupplier = @Collection_Deferred_VATSiteLos_toSupplier,    
  Collection_Deferred_VATSiteLos_toGroup = @Collection_Deferred_VATSiteLos_toGroup,    
  Collection_Deferred_VATSiteLos_toCustoms = @Collection_Deferred_VATSiteLos_toCustoms,    
  Collection_Deferred_VATSiteBankedToSupplier_toGroup = @Collection_Deferred_VATSiteBankedToSupplier_toGroup,    
  Collection_Deferred_VATSiteBankedToSupplier_toCustoms = @Collection_Deferred_VATSiteBankedToSupplier_toCustoms,    
  Collection_Deferred_VATSiteBankedToSupplier_toSite = @Collection_Deferred_VATSiteBankedToSupplier_toSite,    
  Collection_Deferred_VATSiteBankedToGroup_toSupplier = @Collection_Deferred_VATSiteBankedToGroup_toSupplier,    
  Collection_Deferred_VATSiteBankedToGroup_toCustoms = @Collection_Deferred_VATSiteBankedToGroup_toCustoms,    
  Collection_Deferred_VATGroupLos_toSupplier = @Collection_Deferred_VATGroupLos_toSupplier,    
  Collection_Deferred_VATGroupLos_toGroup = @Collection_Deferred_VATGroupLos_toGroup,    
  Collection_Deferred_VATGroupBankedToSupplier_toGroup = @Collection_Deferred_VATGroupBankedToSupplier_toGroup,    
  Collection_Deferred_VATGroupBankedToSupplier_toCustoms = @Collection_Deferred_VATGroupBankedToSupplier_toCustoms,    
  Collection_Deferred_VATGroupBankedToGroup_toSupplier = @Collection_Deferred_VATGroupBankedToGroup_toSupplier,    
  Collection_Deferred_VATGroupBankedToGroup_toCustoms = @Collection_Deferred_VATGroupBankedToGroup_toCustoms,    
  Collection_Deferred_VATSecGroupLos_toSupplier = @Collection_Deferred_VATSecGroupLos_toSupplier,    
  Collection_Deferred_VATSecGroupLos_toGroup = @Collection_Deferred_VATSecGroupLos_toGroup,    
  Collection_Deferred_VATSecGroupLos_toSecGroup = @Collection_Deferred_VATSecGroupLos_toSecGroup,    
  Collection_Deferred_VATSecGroupBankedToSupplier_toGroup = @Collection_Deferred_VATSecGroupBankedToSupplier_toGroup,    
  Collection_Deferred_VATSecGroupBankedToSupplier_toSecGroup = @Collection_Deferred_VATSecGroupBankedToSupplier_toSecGroup,    
  Collection_Deferred_VATSecGroupBankedToSupplier_toCustoms = @Collection_Deferred_VATSecGroupBankedToSupplier_toCustoms,    
  Collection_Deferred_VATSecGroupBankedToGroup_toSupplier = @Collection_Deferred_VATSecGroupBankedToGroup_toSupplier,    
  Collection_Deferred_VATSecGroupBankedToGroup_toSecGroup = @Collection_Deferred_VATSecGroupBankedToGroup_toSecGroup,    
  Collection_Deferred_VATSecGroupBankedToGroup_toCustoms = @Collection_Deferred_VATSecGroupBankedToGroup_toCustoms,    
  Collection_Deferred_LicenceChargeLOS_toSupplier = @Collection_Deferred_LicenceChargeLOS_toSupplier,    
  Collection_Deferred_LicenceChargeLOS_toGroup = @Collection_Deferred_LicenceChargeLOS_toGroup,    
  Collection_Deferred_LicenceChargeBankedToSupplier_toGroup = @Collection_Deferred_LicenceChargeBankedToSupplier_toGroup,    
  Collection_Deferred_LicenceChargeBankedToGroup_toSupplier = @Collection_Deferred_LicenceChargeBankedToGroup_toSupplier,    
  Collection_Deferred_PrizeChargeLOS_toSupplier = @Collection_Deferred_PrizeChargeLOS_toSupplier,    
  Collection_Deferred_PrizeChargeLOS_toGroup = @Collection_Deferred_PrizeChargeLOS_toGroup,    
  Collection_Deferred_PrizeChargeBankedToSupplier_toGroup = @Collection_Deferred_PrizeChargeBankedToSupplier_toGroup,    
  Collection_Deferred_PrizeChargeBankedToGroup_toSupplier = @Collection_Deferred_PrizeChargeBankedToGroup_toSupplier,    
  Collection_Deferred_ConsultancyChargeLOS_toSupplier = @Collection_Deferred_ConsultancyChargeLOS_toSupplier,    
  Collection_Deferred_ConsultancyChargeLOS_toGroup = @Collection_Deferred_ConsultancyChargeLOS_toGroup,    
  Collection_Deferred_ConsultancyChargeBankedToSupplier_toGroup = @Collection_Deferred_ConsultancyChargeBankedToSupplier_toGroup,    
  Collection_Deferred_ConsultancyChargeBankedToGroup_toSupplier = @Collection_Deferred_ConsultancyChargeBankedToGroup_toSupplier,    
  Collection_Deferred_RoyaltyChargeLOS_toSupplier = @Collection_Deferred_RoyaltyChargeLOS_toSupplier,    
  Collection_Deferred_RoyaltyChargeLOS_toGroup = @Collection_Deferred_RoyaltyChargeLOS_toGroup,    
  Collection_Deferred_RoyaltyChargeBankedToSupplier_toGroup = @Collection_Deferred_RoyaltyChargeBankedToSupplier_toGroup,    
  Collection_Deferred_RoyaltyChargeBankedToGroup_toSupplier = @Collection_Deferred_RoyaltyChargeBankedToGroup_toSupplier,    
  Collection_Deferred_Other1ChargeLOS_toSupplier = @Collection_Deferred_Other1ChargeLOS_toSupplier,    
  Collection_Deferred_Other1ChargeLOS_toGroup = @Collection_Deferred_Other1ChargeLOS_toGroup,    
  Collection_Deferred_Other1ChargeBankedToSupplier_toGroup = @Collection_Deferred_Other1ChargeBankedToSupplier_toGroup,    
  Collection_Deferred_Other1ChargeBankedToGroup_toSupplier = @Collection_Deferred_Other1ChargeBankedToGroup_toSupplier,    
  Collection_Deferred_Other2ChargeLOS_toSupplier = @Collection_Deferred_Other2ChargeLOS_toSupplier,    
  Collection_Deferred_Other2ChargeLOS_toGroup = @Collection_Deferred_Other2ChargeLOS_toGroup,    
  Collection_Deferred_Other2ChargeBankedToSupplier_toGroup = @Collection_Deferred_Other2ChargeBankedToSupplier_toGroup,    
  Collection_Deferred_Other2ChargeBankedToGroup_toSupplier = @Collection_Deferred_Other2ChargeBankedToGroup_toSupplier     
 WHERE Collection_ID = @CollectionID    
END    

GO
