/************************************************************
 * Code formatted by SoftTree SQL Assistant © v4.8.29
 * Time: 31/01/2013 6:56:04 AM
 ************************************************************/

USE [Enterprise]
GO

/****** Object:  StoredProcedure [dbo].[usp_InsertorUpdateSiteInfo]    Script Date: 01/31/2013 06:54:34 ******/
IF EXISTS (
       SELECT *
       FROM   sys.objects
       WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[usp_InsertorUpdateSiteInfo]')
              AND TYPE IN (N'P', N'PC')
   )
    DROP PROCEDURE [dbo].[usp_InsertorUpdateSiteInfo]
GO

USE [Enterprise]
GO

/****** Object:  StoredProcedure [dbo].[usp_InsertorUpdateSiteInfo]    Script Date: 01/31/2013 06:54:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

  
CREATE PROCEDURE [dbo].[usp_InsertorUpdateSiteInfo]  
(  
    @Site_ID                           INT OUTPUT,  
    @Service_Supplier_ID               INT,  
    @Service_Area_ID                   INT,  
    @Service_Depot_ID                  INT,  
    @Site_Name                         VARCHAR(50),  
    @Site_Code                         VARCHAR(50),  
    @Site_Supplier_Code                VARCHAR(50),  
    @Site_Company_Code                 VARCHAR(50),  
    @Site_Phone_No                     VARCHAR(15),  
    @Site_Fax_No                       VARCHAR(15),  
    @Site_Email_Address                VARCHAR(100),  
    @Site_Address_1                    VARCHAR(50),  
    @Site_Address_2                    VARCHAR(50),  
    @Site_Address_3                    VARCHAR(50),  
    @Site_Address_4                    VARCHAR(50),  
    @Site_Address_5                    VARCHAR(50),  
    @Site_Postcode                     VARCHAR(15),  
    @Site_Manager                      VARCHAR(50),  
    @Site_Price_Per_Play_Default       BIT,  
    @Site_Price_Per_Play               VARCHAR(50),  
    @Site_Jackpot_Default              BIT,  
    @Site_Jackpot                      VARCHAR(50),  
    @Site_Percentage_Payout_Default    BIT,  
    @Site_Percentage_Payout            VARCHAR(50),  
    @Sub_Company_ID                    INT,  
    @Terms_Group_ID_Default            BIT,  
    @Terms_Group_ID                    INT,  
    @Access_Key_ID_Default             BIT,  
    @Access_Key_ID                     INT,  
    @Staff_ID_Default                  BIT,  
    @Staff_ID                          INT,  
    @Site_Invoice_Name                 VARCHAR(50),  
    @Site_Invoice_Address              NTEXT,  
    @Site_Invoice_Postcode             VARCHAR(15),  
    @Sub_Company_Region_ID             INT,  
    @Sub_Company_Area_ID               INT,  
    @Sub_Company_District_ID           INT,  
    @Site_Image_Reference              VARCHAR(255),  
    @Site_Image_Reference_2            VARCHAR(255),  
    @Site_Closed                       INT,  
    @Depot_ID                          INT,  
    @Site_Classification_ID            INT,  
    @Site_Grade                        VARCHAR(10),  
    @Sage_Account_Ref                  VARCHAR(50),  
    @Site_Is_FreeFloat                 BIT,  
    @Site_Local_Inbox                  VARCHAR(100),  
    @Site_Local_Outbox                 VARCHAR(100),  
    @Site_Memo                         NTEXT,  
    @Site_Reference                    VARCHAR(50),  
    @Site_Trade_Type                   VARCHAR(50),  
    @Site_Non_Trading_Period_From      VARCHAR(30),  
    @Site_Non_Trading_Period_To        VARCHAR(30),  
    @Site_Supplier_Service_Area        VARCHAR(50),  
    @Site_Supplier_Area                VARCHAR(50),  
    @Standard_Opening_Hours_ID         INT,  
    @Next_Sub_Company_ID               INT,  
    @Next_Sub_Company_Change_Date      VARCHAR(30),  
    @Site_Previous_Sub_Company_ID      INT,  
    @Previous_Sub_Company_Change_Date  VARCHAR(30),  
    @Site_Honeyframe_EDI               INT,  
    @Site_Datapak_Protocol             INT,  
    @Site_Start_Date                   VARCHAR(30),  
    @Site_End_Date                     VARCHAR(30),  
    @Site_Licence_Number               VARCHAR(25),  
    @Site_Fiscal_Code                  VARCHAR(16),  
    @Site_Street_Number                VARCHAR(15),  
    @Site_Province                     VARCHAR(15),  
    @Site_Municipality                 VARCHAR(40),  
    @Site_Cadastral_Code               VARCHAR(15),  
    @Site_Area                         INT,  
    @Site_Location_Type                INT,  
    @Site_Toponym                      INT,  
    @Site_Licensee_Commenced_Date      SMALLDATETIME,  
    @Site_Licensee_Agreement_End_Date  DATETIME,  
    @Site_Licensee_Agreement_Type      VARCHAR(50),  
    @Site_Application                  SMALLINT,  
    @Region                            VARCHAR(10),  
    @WebURL                            VARCHAR(2000),  
    @Site_Status_ID                    INT,  
    @Site_Inactive_Date                DATETIME,  
    @Site_Connection_IPAddress         VARCHAR(15),  
    @Site_MaxNumber_VLT                INT,  
    @Site_ZonaRice                     VARCHAR(10),  
    @StackerLimitPercentage            INT,  
    @Site_Enabled                      BIT,  
    @IsTITOEnabled                     INT,  
    @IsCrossTicketingEnabled            INT,  
    @IsNonCashVoucherEnabled           INT  
)  
AS  
BEGIN  
 IF @Site_ID = 0  
 BEGIN  
     INSERT INTO SITE  
       (  
         Service_Supplier_ID,  
         Service_Area_ID,  
         Service_Depot_ID,  
         Site_Name,  
         Site_Code,  
         Site_Supplier_Code,  
         Site_Company_Code,  
         Site_Phone_No,  
         Site_Fax_No,  
         Site_Email_Address,  
         Site_Address_1,  
         Site_Address_2,  
         Site_Address_3,  
         Site_Address_4,  
         Site_Address_5,  
         Site_Postcode,  
         Site_Manager,  
         Site_Price_Per_Play_Default,  
         Site_Price_Per_Play,  
         Site_Jackpot_Default,  
         Site_Jackpot,  
         Site_Percentage_Payout_Default,  
         Site_Percentage_Payout,  
         Sub_Company_ID,  
         Terms_Group_ID_Default,  
         Terms_Group_ID,  
         Access_Key_ID_Default,  
         Access_Key_ID,  
         Staff_ID_Default,  
         Staff_ID,  
         Site_Invoice_Name,  
         Site_Invoice_Address,  
         Site_Invoice_Postcode,  
         Sub_Company_Region_ID,  
         Sub_Company_Area_ID,  
         Sub_Company_District_ID,  
         Site_Image_Reference,  
         Site_Image_Reference_2,  
         Site_Closed,  
         Depot_ID,  
         Site_Classification_ID,  
         Site_Grade,  
         Sage_Account_Ref,  
         Site_Is_FreeFloat,  
         Site_Local_Inbox,  
         Site_Local_Outbox,  
         Site_Memo,  
         Site_Reference,  
         Site_Trade_Type,  
         Site_Non_Trading_Period_From,  
         Site_Non_Trading_Period_To,  
         Site_Supplier_Service_Area,  
         Site_Supplier_Area,  
         Standard_Opening_Hours_ID,  
         Next_Sub_Company_ID,  
         Next_Sub_Company_Change_Date,  
         Site_Previous_Sub_Company_ID,  
         Previous_Sub_Company_Change_Date,  
         Site_Honeyframe_EDI,  
         Site_Datapak_Protocol,  
         Site_Start_Date,  
         Site_End_Date,  
         Site_Licence_Number,  
         Site_Fiscal_Code,  
         Site_Street_Number,  
         Site_Province,  
         Site_Municipality,  
         Site_Cadastral_Code,  
         Site_Area,  
         Site_Location_Type,  
         Site_Toponym,  
         Site_Licensee_Commenced_Date,  
         Site_Licensee_Agreement_End_Date,  
         Site_Licensee_Agreement_Type,  
         Site_Application,  
         Region,  
         WebURL,  
         Site_Status_ID,  
         Site_Inactive_Date,  
         Site_Connection_IPAddress,  
         Site_MaxNumber_VLT,  
         Site_ZonaRice,  
         StackerLimitPercentage,  
         SiteStatus,  
         Site_Enabled,  
   IsTITOEnabled,  
   IsCrossTicketingEnabled,  
   IsNonCashVoucherEnabled   
       )  
     VALUES  
       (  
         @Service_Supplier_ID,  
         @Service_Area_ID,  
         @Service_Depot_ID,  
         @Site_Name,  
         @Site_Code,  
         @Site_Supplier_Code,  
         @Site_Company_Code,  
         @Site_Phone_No,  
         @Site_Fax_No,  
         @Site_Email_Address,  
         @Site_Address_1,  
         @Site_Address_2,  
         @Site_Address_3,  
         @Site_Address_4,  
         @Site_Address_5,  
         @Site_Postcode,  
         @Site_Manager,  
         @Site_Price_Per_Play_Default,  
         @Site_Price_Per_Play,  
         @Site_Jackpot_Default,  
         @Site_Jackpot,  
         @Site_Percentage_Payout_Default,  
         @Site_Percentage_Payout,  
         @Sub_Company_ID,  
         @Terms_Group_ID_Default,  
         @Terms_Group_ID,  
         @Access_Key_ID_Default,  
         @Access_Key_ID,  
         @Staff_ID_Default,  
         @Staff_ID,  
         @Site_Invoice_Name,  
         @Site_Invoice_Address,  
         @Site_Invoice_Postcode,  
         @Sub_Company_Region_ID,  
         @Sub_Company_Area_ID,  
         @Sub_Company_District_ID,  
         @Site_Image_Reference,  
         @Site_Image_Reference_2,  
         @Site_Closed,  
         @Depot_ID,  
         @Site_Classification_ID,  
         @Site_Grade,  
         @Sage_Account_Ref,  
         @Site_Is_FreeFloat,  
         @Site_Local_Inbox,  
         @Site_Local_Outbox,  
         @Site_Memo,  
         @Site_Reference,  
         @Site_Trade_Type,  
         @Site_Non_Trading_Period_From,  
         @Site_Non_Trading_Period_To,  
         @Site_Supplier_Service_Area,  
         @Site_Supplier_Area,  
         @Standard_Opening_Hours_ID,  
         @Next_Sub_Company_ID,  
         @Next_Sub_Company_Change_Date,  
         @Site_Previous_Sub_Company_ID,  
         @Previous_Sub_Company_Change_Date,  
         @Site_Honeyframe_EDI,  
         @Site_Datapak_Protocol,  
         @Site_Start_Date,  
         @Site_End_Date,  
         @Site_Licence_Number,  
         @Site_Fiscal_Code,  
         @Site_Street_Number,  
         @Site_Province,  
         @Site_Municipality,  
         @Site_Cadastral_Code,  
         @Site_Area,  
         @Site_Location_Type,  
         @Site_Toponym,  
         @Site_Licensee_Commenced_Date,  
         @Site_Licensee_Agreement_End_Date,  
         @Site_Licensee_Agreement_Type,  
         @Site_Application,  
         @Region,  
         @WebURL,  
         @Site_Status_ID,  
         @Site_Inactive_Date,  
         @Site_Connection_IPAddress,  
         @Site_MaxNumber_VLT,  
         @Site_ZonaRice,  
         @StackerLimitPercentage,  
         'PARTIALLYCONFIGURED',  
         @Site_Enabled,  
   @IsTITOEnabled,  
   @IsCrossTicketingEnabled,  
   @IsNonCashVoucherEnabled   
       )  
       
       INSERT INTO MeterAnalysis.dbo.SITE  
       (  
         Service_Supplier_ID,  
         Service_Area_ID,  
         Service_Depot_ID,  
         Site_Name,  
         Site_Code,  
         Site_Supplier_Code,  
         Site_Company_Code,  
         Site_Phone_No,  
         Site_Fax_No,  
         Site_Email_Address,  
         Site_Address_1,  
         Site_Address_2,  
         Site_Address_3,  
         Site_Address_4,  
         Site_Address_5,  
         Site_Postcode,  
         Site_Manager,  
         Site_Price_Per_Play_Default,  
         Site_Price_Per_Play,  
         Site_Jackpot_Default,  
         Site_Jackpot,  
         Site_Percentage_Payout_Default,  
         Site_Percentage_Payout,  
         Sub_Company_ID,  
         Terms_Group_ID_Default,  
         Terms_Group_ID,  
         Access_Key_ID_Default,  
         Access_Key_ID,  
         Staff_ID_Default,  
         Staff_ID,  
         Site_Invoice_Name,  
         Site_Invoice_Address,  
         Site_Invoice_Postcode,  
         Sub_Company_Region_ID,  
         Sub_Company_Area_ID,  
         Sub_Company_District_ID,  
         Site_Image_Reference,  
         Site_Image_Reference_2,  
         Site_Closed,  
         Depot_ID,  
         Site_Classification_ID,  
         Site_Grade,  
         Sage_Account_Ref,  
         Site_Is_FreeFloat,  
         Site_Local_Inbox,  
         Site_Local_Outbox,  
         Site_Memo,  
         Site_Reference,  
         Site_Trade_Type,  
         Site_Non_Trading_Period_From,  
         Site_Non_Trading_Period_To,  
         Site_Supplier_Service_Area,  
         Site_Supplier_Area,  
         Standard_Opening_Hours_ID,  
         Next_Sub_Company_ID,  
         Next_Sub_Company_Change_Date,  
         Site_Previous_Sub_Company_ID,  
         Previous_Sub_Company_Change_Date,  
         Site_Honeyframe_EDI,  
         Site_Datapak_Protocol,  
         Site_Start_Date,  
         Site_End_Date,  
         Site_Licence_Number,  
         Site_Fiscal_Code,  
         Site_Street_Number,  
         Site_Province,  
         Site_Municipality,  
         Site_Cadastral_Code,  
         Site_Area,  
         Site_Location_Type,  
         Site_Toponym,  
         Site_Licensee_Commenced_Date,  
         Site_Licensee_Agreement_End_Date,  
         Site_Licensee_Agreement_Type,  
         Site_Application,  
         Region,  
         WebURL,  
         Site_Status_ID,  
         Site_Inactive_Date,  
         Site_Connection_IPAddress,  
         Site_MaxNumber_VLT,  
         Site_ZonaRice,  
         StackerLimitPercentage,  
         SiteStatus,  
         Site_Enabled,  
   IsTITOEnabled,  
   IsCrossTicketingEnabled,  
   IsNonCashVoucherEnabled   
       )  
     VALUES  
       (  
         @Service_Supplier_ID,  
         @Service_Area_ID,  
         @Service_Depot_ID,  
         @Site_Name,  
         @Site_Code,  
         @Site_Supplier_Code,  
         @Site_Company_Code,  
         @Site_Phone_No,  
         @Site_Fax_No,  
         @Site_Email_Address,  
         @Site_Address_1,  
         @Site_Address_2,  
         @Site_Address_3,  
         @Site_Address_4,  
         @Site_Address_5,  
         @Site_Postcode,  
         @Site_Manager,  
         @Site_Price_Per_Play_Default,  
         @Site_Price_Per_Play,  
         @Site_Jackpot_Default,  
         @Site_Jackpot,  
         @Site_Percentage_Payout_Default,  
         @Site_Percentage_Payout,  
         @Sub_Company_ID,  
         @Terms_Group_ID_Default,  
         @Terms_Group_ID,  
         @Access_Key_ID_Default,  
         @Access_Key_ID,  
         @Staff_ID_Default,  
         @Staff_ID,  
         @Site_Invoice_Name,  
         @Site_Invoice_Address,  
         @Site_Invoice_Postcode,  
         @Sub_Company_Region_ID,  
         @Sub_Company_Area_ID,  
         @Sub_Company_District_ID,  
         @Site_Image_Reference,  
         @Site_Image_Reference_2,  
         @Site_Closed,  
         @Depot_ID,  
         @Site_Classification_ID,  
         @Site_Grade,  
         @Sage_Account_Ref,  
         @Site_Is_FreeFloat,  
         @Site_Local_Inbox,  
         @Site_Local_Outbox,  
         @Site_Memo,  
         @Site_Reference,  
         @Site_Trade_Type,  
         @Site_Non_Trading_Period_From,  
         @Site_Non_Trading_Period_To,  
         @Site_Supplier_Service_Area,  
         @Site_Supplier_Area,  
         @Standard_Opening_Hours_ID,  
         @Next_Sub_Company_ID,  
         @Next_Sub_Company_Change_Date,  
         @Site_Previous_Sub_Company_ID,  
         @Previous_Sub_Company_Change_Date,  
         @Site_Honeyframe_EDI,  
         @Site_Datapak_Protocol,  
         @Site_Start_Date,  
         @Site_End_Date,  
         @Site_Licence_Number,  
         @Site_Fiscal_Code,  
         @Site_Street_Number,  
         @Site_Province,  
         @Site_Municipality,  
         @Site_Cadastral_Code,  
         @Site_Area,  
         @Site_Location_Type,  
         @Site_Toponym,  
         @Site_Licensee_Commenced_Date,  
         @Site_Licensee_Agreement_End_Date,  
         @Site_Licensee_Agreement_Type,  
         @Site_Application,  
         @Region,  
         @WebURL,  
         @Site_Status_ID,  
         @Site_Inactive_Date,  
         @Site_Connection_IPAddress,  
         @Site_MaxNumber_VLT,  
         @Site_ZonaRice,  
         @StackerLimitPercentage,  
         'PARTIALLYCONFIGURED',  
         @Site_Enabled,  
   @IsTITOEnabled,  
   @IsCrossTicketingEnabled,  
   @IsNonCashVoucherEnabled   
       )  
       SET @Site_ID = scope_identity()  
  EXEC [dbo].[usp_EBS_UpdateSiteDetails] @Site_ID    
 END  
 ELSE  
 BEGIN  
   
 DECLARE @_Modified TABLE (  
            SiteId INT,  
            OldSiteCode VARCHAR(50),  
            NewSiteCode VARCHAR(50),  
            OldSiteName VARCHAR(50),  
            NewSiteName VARCHAR(50),  
            FlagChanged AS (CASE WHEN (OldSiteCode = NewSiteCode) AND (OldSiteName = NewSiteName) THEN 0 ELSE 1 END)  
     )  
  
   
     UPDATE SITE  
     SET    Service_Supplier_ID = @Service_Supplier_ID,  
            Service_Area_ID = @Service_Area_ID,  
            Service_Depot_ID = @Service_Depot_ID,  
            Site_Name = @Site_Name,  
            Site_Code = @Site_Code,  
            Site_Supplier_Code = @Site_Supplier_Code,  
            Site_Company_Code = @Site_Company_Code,  
            Site_Phone_No = @Site_Phone_No,  
            Site_Fax_No = @Site_Fax_No,  
            Site_Email_Address = @Site_Email_Address,  
            Site_Address_1 = @Site_Address_1,  
            Site_Address_2 = @Site_Address_2,  
            Site_Address_3 = @Site_Address_3,  
            Site_Address_4 = @Site_Address_4,  
            Site_Address_5 = @Site_Address_5,  
            Site_Postcode = @Site_Postcode,  
            Site_Manager = @Site_Manager,  
            Site_Price_Per_Play_Default = @Site_Price_Per_Play_Default,  
            Site_Price_Per_Play = @Site_Price_Per_Play,  
            Site_Jackpot_Default = @Site_Jackpot_Default,  
            Site_Jackpot = @Site_Jackpot,  
            Site_Percentage_Payout_Default = @Site_Percentage_Payout_Default,  
            Site_Percentage_Payout = @Site_Percentage_Payout,  
            Sub_Company_ID = @Sub_Company_ID,  
            --Company_ID = @Company_ID,  
            Terms_Group_ID_Default = @Terms_Group_ID_Default,  
            Terms_Group_ID = @Terms_Group_ID,  
            Access_Key_ID_Default = @Access_Key_ID_Default,  
            Access_Key_ID = @Access_Key_ID,  
            Staff_ID_Default = @Staff_ID_Default,  
            Staff_ID = @Staff_ID,  
            Site_Invoice_Name = @Site_Invoice_Name,  
            Site_Invoice_Address = @Site_Invoice_Address,  
            Site_Invoice_Postcode = @Site_Invoice_Postcode,  
            Sub_Company_Region_ID = @Sub_Company_Region_ID,  
            Sub_Company_Area_ID = @Sub_Company_Area_ID,  
            Sub_Company_District_ID = @Sub_Company_District_ID,  
            Site_Image_Reference = @Site_Image_Reference,  
            Site_Image_Reference_2 = @Site_Image_Reference_2,  
            Site_Closed = @Site_Closed,  
            Depot_ID = @Depot_ID,  
            Site_Classification_ID = @Site_Classification_ID,  
            Site_Grade = @Site_Grade,  
            Sage_Account_Ref = @Sage_Account_Ref,  
            Site_Is_FreeFloat = @Site_Is_FreeFloat,  
            Site_Local_Inbox = @Site_Local_Inbox,  
            Site_Local_Outbox = @Site_Local_Outbox,  
            Site_Memo = @Site_Memo,  
            Site_Reference = @Site_Reference,  
            Site_Trade_Type = @Site_Trade_Type,  
            Site_Non_Trading_Period_From = @Site_Non_Trading_Period_From,  
            Site_Non_Trading_Period_To = @Site_Non_Trading_Period_To,  
            Site_Supplier_Service_Area = @Site_Supplier_Service_Area,  
            Site_Supplier_Area = @Site_Supplier_Area,  
            Standard_Opening_Hours_ID = @Standard_Opening_Hours_ID,  
            Next_Sub_Company_ID = @Next_Sub_Company_ID,  
            Next_Sub_Company_Change_Date = @Next_Sub_Company_Change_Date,  
            Site_Previous_Sub_Company_ID = @Site_Previous_Sub_Company_ID,  
            Previous_Sub_Company_Change_Date = @Previous_Sub_Company_Change_Date,  
            Site_Honeyframe_EDI = @Site_Honeyframe_EDI,  
            Site_Datapak_Protocol = @Site_Datapak_Protocol,  
            Site_Start_Date = @Site_Start_Date,  
            Site_End_Date = @Site_End_Date,  
            Site_Licence_Number = @Site_Licence_Number,  
            Site_Fiscal_Code = @Site_Fiscal_Code,  
            Site_Street_Number = @Site_Street_Number,  
            Site_Province = @Site_Province,  
            Site_Municipality = @Site_Municipality,  
            Site_Cadastral_Code = @Site_Cadastral_Code,  
            Site_Area = @Site_Area,  
            Site_Location_Type = @Site_Location_Type,  
            Site_Toponym = @Site_Toponym,  
            Site_Licensee_Commenced_Date = @Site_Licensee_Commenced_Date,  
            Site_Licensee_Agreement_End_Date = @Site_Licensee_Agreement_End_Date,  
            Site_Licensee_Agreement_Type = @Site_Licensee_Agreement_Type,  
            Site_Application = @Site_Application,  
            Region = @Region,  
            WebURL = @WebURL,  
            Site_Status_ID = @Site_Status_ID,  
            Site_Inactive_Date = @Site_Inactive_Date,  
            Site_Connection_IPAddress = @Site_Connection_IPAddress,  
            Site_MaxNumber_VLT = @Site_MaxNumber_VLT,  
            Site_ZonaRice = @Site_ZonaRice,  
            StackerLimitPercentage = @StackerLimitPercentage,  
            Site_Enabled = @Site_Enabled,  
      IsTITOEnabled = @IsTITOEnabled,  
      IsCrossTicketingEnabled = @IsCrossTicketingEnabled,  
      IsNonCashVoucherEnabled = @IsNonCashVoucherEnabled   
        
      OUTPUT INSERTED.Site_ID,  
            DELETED.Site_Code,  
            INSERTED.Site_Code,  
            DELETED.Site_Name,  
            INSERTED.Site_Name  
               INTO @_Modified  
     WHERE  Site_ID = @Site_ID  
     
       UPDATE MeterAnalysis.dbo.SITE  
     SET    Service_Supplier_ID = @Service_Supplier_ID,  
            Service_Area_ID = @Service_Area_ID,  
            Service_Depot_ID = @Service_Depot_ID,  
            Site_Name = @Site_Name,  
            Site_Code = @Site_Code,  
            Site_Supplier_Code = @Site_Supplier_Code,  
            Site_Company_Code = @Site_Company_Code,  
            Site_Phone_No = @Site_Phone_No,  
            Site_Fax_No = @Site_Fax_No,  
            Site_Email_Address = @Site_Email_Address,  
            Site_Address_1 = @Site_Address_1,  
            Site_Address_2 = @Site_Address_2,  
            Site_Address_3 = @Site_Address_3,  
            Site_Address_4 = @Site_Address_4,  
            Site_Address_5 = @Site_Address_5,  
            Site_Postcode = @Site_Postcode,  
            Site_Manager = @Site_Manager,  
            Site_Price_Per_Play_Default = @Site_Price_Per_Play_Default,  
            Site_Price_Per_Play = @Site_Price_Per_Play,  
            Site_Jackpot_Default = @Site_Jackpot_Default,  
            Site_Jackpot = @Site_Jackpot,  
            Site_Percentage_Payout_Default = @Site_Percentage_Payout_Default,  
            Site_Percentage_Payout = @Site_Percentage_Payout,  
            Sub_Company_ID = @Sub_Company_ID,  
            --Company_ID = @Company_ID,  
            Terms_Group_ID_Default = @Terms_Group_ID_Default,  
            Terms_Group_ID = @Terms_Group_ID,  
            Access_Key_ID_Default = @Access_Key_ID_Default,  
            Access_Key_ID = @Access_Key_ID,  
            Staff_ID_Default = @Staff_ID_Default,  
            Staff_ID = @Staff_ID,  
            Site_Invoice_Name = @Site_Invoice_Name,  
            Site_Invoice_Address = @Site_Invoice_Address,  
            Site_Invoice_Postcode = @Site_Invoice_Postcode,  
            Sub_Company_Region_ID = @Sub_Company_Region_ID,  
            Sub_Company_Area_ID = @Sub_Company_Area_ID,  
            Sub_Company_District_ID = @Sub_Company_District_ID,  
            Site_Image_Reference = @Site_Image_Reference,  
            Site_Image_Reference_2 = @Site_Image_Reference_2,  
            Site_Closed = @Site_Closed,  
            Depot_ID = @Depot_ID,  
            Site_Classification_ID = @Site_Classification_ID,  
            Site_Grade = @Site_Grade,  
            Sage_Account_Ref = @Sage_Account_Ref,  
            Site_Is_FreeFloat = @Site_Is_FreeFloat,  
            Site_Local_Inbox = @Site_Local_Inbox,  
            Site_Local_Outbox = @Site_Local_Outbox,  
            Site_Memo = @Site_Memo,  
            Site_Reference = @Site_Reference,  
            Site_Trade_Type = @Site_Trade_Type,  
            Site_Non_Trading_Period_From = @Site_Non_Trading_Period_From,  
            Site_Non_Trading_Period_To = @Site_Non_Trading_Period_To,  
            Site_Supplier_Service_Area = @Site_Supplier_Service_Area,  
            Site_Supplier_Area = @Site_Supplier_Area,  
            Standard_Opening_Hours_ID = @Standard_Opening_Hours_ID,  
            Next_Sub_Company_ID = @Next_Sub_Company_ID,  
            Next_Sub_Company_Change_Date = @Next_Sub_Company_Change_Date,  
            Site_Previous_Sub_Company_ID = @Site_Previous_Sub_Company_ID,  
            Previous_Sub_Company_Change_Date = @Previous_Sub_Company_Change_Date,  
            Site_Honeyframe_EDI = @Site_Honeyframe_EDI,  
            Site_Datapak_Protocol = @Site_Datapak_Protocol,  
            Site_Start_Date = @Site_Start_Date,  
            Site_End_Date = @Site_End_Date,  
            Site_Licence_Number = @Site_Licence_Number,  
            Site_Fiscal_Code = @Site_Fiscal_Code,  
            Site_Street_Number = @Site_Street_Number,  
            Site_Province = @Site_Province,  
            Site_Municipality = @Site_Municipality,  
            Site_Cadastral_Code = @Site_Cadastral_Code,  
            Site_Area = @Site_Area,  
            Site_Location_Type = @Site_Location_Type,  
            Site_Toponym = @Site_Toponym,  
            Site_Licensee_Commenced_Date = @Site_Licensee_Commenced_Date,  
            Site_Licensee_Agreement_End_Date = @Site_Licensee_Agreement_End_Date,  
            Site_Licensee_Agreement_Type = @Site_Licensee_Agreement_Type,  
            Site_Application = @Site_Application,  
            Region = @Region,  
            WebURL = @WebURL,  
            Site_Status_ID = @Site_Status_ID,  
            Site_Inactive_Date = @Site_Inactive_Date,  
            Site_Connection_IPAddress = @Site_Connection_IPAddress,  
            Site_MaxNumber_VLT = @Site_MaxNumber_VLT,  
            Site_ZonaRice = @Site_ZonaRice,  
            StackerLimitPercentage = @StackerLimitPercentage,  
            Site_Enabled = @Site_Enabled,  
      IsTITOEnabled = @IsTITOEnabled,  
      IsCrossTicketingEnabled = @IsCrossTicketingEnabled,  
      IsNonCashVoucherEnabled = @IsNonCashVoucherEnabled   
        
      OUTPUT INSERTED.Site_ID,  
            DELETED.Site_Code,  
            INSERTED.Site_Code,  
            DELETED.Site_Name,  
            INSERTED.Site_Name  
               INTO @_Modified  
     WHERE  Site_ID = @Site_ID  
       
     SET @Site_ID =@Site_ID  
 END  
EXEC usp_Export_History @Site_ID,"SITESETTINGS",@Site_id  
EXEC usp_Export_History @Site_ID,"SITESETUP",@Site_id  
  
 IF EXISTS(SELECT 1 FROM   @_Modified m WHERE  m.FlagChanged = 1)  
 BEGIN  
  EXEC [dbo].[usp_EBS_UpdateSiteDetails] @Site_ID   
 END        
  
END  



GO

