//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.MeterAdjustmentTool.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CollectionsSchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectionsSchema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMC.MeterAdjustmentTool.Schemas.CollectionsSchema", typeof(CollectionsSchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string Bar_pos_Name {
            get {
                return ResourceManager.GetString("Bar_pos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000# (Count).
        /// </summary>
        internal static string CASH_IN_100000P {
            get {
                return ResourceManager.GetString("CASH_IN_100000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000# (Count).
        /// </summary>
        internal static string CASH_IN_10000P {
            get {
                return ResourceManager.GetString("CASH_IN_10000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000# (Count).
        /// </summary>
        internal static string CASH_IN_1000P {
            get {
                return ResourceManager.GetString("CASH_IN_1000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100# (Count).
        /// </summary>
        internal static string CASH_IN_100P {
            get {
                return ResourceManager.GetString("CASH_IN_100P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10# (Count).
        /// </summary>
        internal static string CASH_IN_10P {
            get {
                return ResourceManager.GetString("CASH_IN_10P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1# (Count).
        /// </summary>
        internal static string CASH_IN_1P {
            get {
                return ResourceManager.GetString("CASH_IN_1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000# (Count).
        /// </summary>
        internal static string CASH_IN_20000P {
            get {
                return ResourceManager.GetString("CASH_IN_20000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000# (Count).
        /// </summary>
        internal static string CASH_IN_2000P {
            get {
                return ResourceManager.GetString("CASH_IN_2000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200# (Count).
        /// </summary>
        internal static string CASH_IN_200P {
            get {
                return ResourceManager.GetString("CASH_IN_200P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20# (Count).
        /// </summary>
        internal static string CASH_IN_20P {
            get {
                return ResourceManager.GetString("CASH_IN_20P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2# (Count).
        /// </summary>
        internal static string CASH_IN_2P {
            get {
                return ResourceManager.GetString("CASH_IN_2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50000# (Count).
        /// </summary>
        internal static string CASH_IN_50000P {
            get {
                return ResourceManager.GetString("CASH_IN_50000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000# (Count).
        /// </summary>
        internal static string CASH_IN_5000P {
            get {
                return ResourceManager.GetString("CASH_IN_5000P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500# (Count).
        /// </summary>
        internal static string CASH_IN_500P {
            get {
                return ResourceManager.GetString("CASH_IN_500P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50# (Count).
        /// </summary>
        internal static string CASH_IN_50P {
            get {
                return ResourceManager.GetString("CASH_IN_50P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5# (Count).
        /// </summary>
        internal static string CASH_IN_5P {
            get {
                return ResourceManager.GetString("CASH_IN_5P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT In (#).
        /// </summary>
        internal static string Cashable_EFT_IN {
            get {
                return ResourceManager.GetString("Cashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT Out (#).
        /// </summary>
        internal static string Cashable_EFT_OUT {
            get {
                return ResourceManager.GetString("Cashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Variance (#).
        /// </summary>
        internal static string Coin_Var {
            get {
                return ResourceManager.GetString("Coin_Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Date.
        /// </summary>
        internal static string Collection_Date {
            get {
                return ResourceManager.GetString("Collection_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Credits (#).
        /// </summary>
        internal static string COLLECTION_RDC_CANCELLED_CREDITS {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_CANCELLED_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Drop (#).
        /// </summary>
        internal static string COLLECTION_RDC_COIN_DROP {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_COIN_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin In (#).
        /// </summary>
        internal static string COLLECTION_RDC_COINS_IN {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_COINS_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Out (#).
        /// </summary>
        internal static string COLLECTION_RDC_COINS_OUT {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_COINS_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Credits (#).
        /// </summary>
        internal static string COLLECTION_RDC_CURRENT_CREDITS {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_CURRENT_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Bet.
        /// </summary>
        internal static string COLLECTION_RDC_GAMES_BET {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_GAMES_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Lost.
        /// </summary>
        internal static string COLLECTION_RDC_GAMES_LOST {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_GAMES_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Won.
        /// </summary>
        internal static string COLLECTION_RDC_GAMES_WON {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_GAMES_WON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handpay (#).
        /// </summary>
        internal static string COLLECTION_RDC_HANDPAY {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_HANDPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackpot (#).
        /// </summary>
        internal static string COLLECTION_RDC_JACKPOT {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_JACKPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (#).
        /// </summary>
        internal static string COLLECTION_RDC_TICKETS_INSERTED_VALUE {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_TICKETS_INSERTED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (#).
        /// </summary>
        internal static string COLLECTION_RDC_TICKETS_PRINTED_VALUE {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_TICKETS_PRINTED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Coin In (#).
        /// </summary>
        internal static string COLLECTION_RDC_TRUE_COIN_IN {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_TRUE_COIN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Coin Out (#).
        /// </summary>
        internal static string COLLECTION_RDC_TRUE_COIN_OUT {
            get {
                return ResourceManager.GetString("COLLECTION_RDC_TRUE_COIN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandPay Variance (#).
        /// </summary>
        internal static string HandpayVar {
            get {
                return ResourceManager.GetString("HandpayVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Variance (#).
        /// </summary>
        internal static string MeterVar {
            get {
                return ResourceManager.GetString("MeterVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Attendant Paid (#).
        /// </summary>
        internal static string Mystery_Attendant_Paid {
            get {
                return ResourceManager.GetString("Mystery_Attendant_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Machine Paid (#).
        /// </summary>
        internal static string Mystery_Machine_Paid {
            get {
                return ResourceManager.GetString("Mystery_Machine_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Title.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT In (#).
        /// </summary>
        internal static string NonCashable_EFT_IN {
            get {
                return ResourceManager.GetString("NonCashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT Out (#).
        /// </summary>
        internal static string NonCashable_EFT_OUT {
            get {
                return ResourceManager.GetString("NonCashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills Variance (#).
        /// </summary>
        internal static string Note_Var {
            get {
                return ResourceManager.GetString("Note_Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Collection Date.
        /// </summary>
        internal static string PreviousCollectionDate {
            get {
                return ResourceManager.GetString("PreviousCollectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Variance (#).
        /// </summary>
        internal static string Progressive_Value_Variance {
            get {
                return ResourceManager.GetString("Progressive_Value_Variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Handpay (#).
        /// </summary>
        internal static string progressive_win_Handpay_value {
            get {
                return ResourceManager.GetString("progressive_win_Handpay_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Wins (#).
        /// </summary>
        internal static string progressive_win_value {
            get {
                return ResourceManager.GetString("progressive_win_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT In (#).
        /// </summary>
        internal static string Promo_Cashable_EFT_IN {
            get {
                return ResourceManager.GetString("Promo_Cashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT Out (#).
        /// </summary>
        internal static string Promo_Cashable_EFT_OUT {
            get {
                return ResourceManager.GetString("Promo_Cashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Non Cashable Value) (#).
        /// </summary>
        internal static string RDC_TICKETS_INSERTED_NONCASHABLE_VALUE {
            get {
                return ResourceManager.GetString("RDC_TICKETS_INSERTED_NONCASHABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (Non Cashable Value)  (#).
        /// </summary>
        internal static string RDC_TICKETS_PRINTED_NONCASHABLE_VALUE {
            get {
                return ResourceManager.GetString("RDC_TICKETS_PRINTED_NONCASHABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDC Variance (#).
        /// </summary>
        internal static string RDCVar {
            get {
                return ResourceManager.GetString("RDCVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset No.
        /// </summary>
        internal static string Stock_no {
            get {
                return ResourceManager.GetString("Stock_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Non Cashable Qty).
        /// </summary>
        internal static string TICKETS_INSERTED_NONCASHABLE_QTY {
            get {
                return ResourceManager.GetString("TICKETS_INSERTED_NONCASHABLE_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Qty).
        /// </summary>
        internal static string TICKETS_INSERTED_QTY {
            get {
                return ResourceManager.GetString("TICKETS_INSERTED_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Variance (#).
        /// </summary>
        internal static string TicketVar {
            get {
                return ResourceManager.GetString("TicketVar", resourceCulture);
            }
        }
    }
}
