//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.MeterAdjustmentTool.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DailySchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailySchema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMC.MeterAdjustmentTool.Schemas.DailySchema", typeof(DailySchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string Bar_Pos_Name {
            get {
                return ResourceManager.GetString("Bar_Pos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT In (#).
        /// </summary>
        internal static string Cashable_EFT_IN {
            get {
                return ResourceManager.GetString("Cashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT Out (#).
        /// </summary>
        internal static string Cashable_EFT_OUT {
            get {
                return ResourceManager.GetString("Cashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Datetime.
        /// </summary>
        internal static string CollectedDateTime {
            get {
                return ResourceManager.GetString("CollectedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Attendant Paid (#).
        /// </summary>
        internal static string Mystery_Attendant_Paid {
            get {
                return ResourceManager.GetString("Mystery_Attendant_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Machine Paid (#).
        /// </summary>
        internal static string Mystery_Machine_Paid {
            get {
                return ResourceManager.GetString("Mystery_Machine_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT In (#).
        /// </summary>
        internal static string NonCashable_EFT_IN {
            get {
                return ResourceManager.GetString("NonCashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT Out (#).
        /// </summary>
        internal static string NonCashable_EFT_OUT {
            get {
                return ResourceManager.GetString("NonCashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Handpay (#).
        /// </summary>
        internal static string progressive_win_Handpay_value {
            get {
                return ResourceManager.GetString("progressive_win_Handpay_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Win (#).
        /// </summary>
        internal static string progressive_win_value {
            get {
                return ResourceManager.GetString("progressive_win_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT In (#).
        /// </summary>
        internal static string Promo_Cashable_EFT_IN {
            get {
                return ResourceManager.GetString("Promo_Cashable_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT Out (#).
        /// </summary>
        internal static string Promo_Cashable_EFT_OUT {
            get {
                return ResourceManager.GetString("Promo_Cashable_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Drop (#).
        /// </summary>
        internal static string READ_COIN_DROP {
            get {
                return ResourceManager.GetString("READ_COIN_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin in (#).
        /// </summary>
        internal static string READ_COINS_IN {
            get {
                return ResourceManager.GetString("READ_COINS_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin out (#).
        /// </summary>
        internal static string READ_COINS_OUT {
            get {
                return ResourceManager.GetString("READ_COINS_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Date.
        /// </summary>
        internal static string READ_DATE {
            get {
                return ResourceManager.GetString("READ_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Bet.
        /// </summary>
        internal static string READ_GAMES_BET {
            get {
                return ResourceManager.GetString("READ_GAMES_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Won.
        /// </summary>
        internal static string READ_GAMES_WON {
            get {
                return ResourceManager.GetString("READ_GAMES_WON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandPay (#).
        /// </summary>
        internal static string READ_HANDPAY {
            get {
                return ResourceManager.GetString("READ_HANDPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_1 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_10 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_100 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_10000 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_100000 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_100000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_2 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_20 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_200 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_20000 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_250 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_5 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50#  (Count).
        /// </summary>
        internal static string READ_RDC_BILL_50 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_500 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50000# (Count).
        /// </summary>
        internal static string READ_RDC_BILL_50000 {
            get {
                return ResourceManager.GetString("READ_RDC_BILL_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Credits (#).
        /// </summary>
        internal static string READ_RDC_CANCELLED_CREDITS {
            get {
                return ResourceManager.GetString("READ_RDC_CANCELLED_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Credits (#).
        /// </summary>
        internal static string READ_RDC_CURRENT_CREDITS {
            get {
                return ResourceManager.GetString("READ_RDC_CURRENT_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Lost.
        /// </summary>
        internal static string READ_RDC_GAMES_LOST {
            get {
                return ResourceManager.GetString("READ_RDC_GAMES_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackpot (#).
        /// </summary>
        internal static string READ_RDC_JACKPOT {
            get {
                return ResourceManager.GetString("READ_RDC_JACKPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Coin In (#).
        /// </summary>
        internal static string READ_RDC_TRUE_COIN_IN {
            get {
                return ResourceManager.GetString("READ_RDC_TRUE_COIN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Coin Out (#).
        /// </summary>
        internal static string READ_RDC_TRUE_COIN_OUT {
            get {
                return ResourceManager.GetString("READ_RDC_TRUE_COIN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (#).
        /// </summary>
        internal static string READ_TICKET {
            get {
                return ResourceManager.GetString("READ_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (#).
        /// </summary>
        internal static string READ_TICKET_IN_SUSPENSE {
            get {
                return ResourceManager.GetString("READ_TICKET_IN_SUSPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Qty).
        /// </summary>
        internal static string READ_TICKET_IN_SUSPENSE_VALUE {
            get {
                return ResourceManager.GetString("READ_TICKET_IN_SUSPENSE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (Qty).
        /// </summary>
        internal static string READ_TICKET_VALUE {
            get {
                return ResourceManager.GetString("READ_TICKET_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Non Cashable) (#).
        /// </summary>
        internal static string TICKETS_INSERTED_NONCASHABLE_VALUE {
            get {
                return ResourceManager.GetString("TICKETS_INSERTED_NONCASHABLE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (Non Cashable) (#).
        /// </summary>
        internal static string TICKETS_PRINTED_NONCASHABLE_VALUE {
            get {
                return ResourceManager.GetString("TICKETS_PRINTED_NONCASHABLE_VALUE", resourceCulture);
            }
        }
    }
}
