//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC.MeterAdjustmentTool.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HourlySchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HourlySchema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMC.MeterAdjustmentTool.Schemas.HourlySchema", typeof(HourlySchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Bet (#).
        /// </summary>
        internal static string AVG_BET {
            get {
                return ResourceManager.GetString("AVG_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarPosition.
        /// </summary>
        internal static string Bar_Pos_Name {
            get {
                return ResourceManager.GetString("Bar_Pos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Credits (#).
        /// </summary>
        internal static string CANCELLED_CREDITS {
            get {
                return ResourceManager.GetString("CANCELLED_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT In (#).
        /// </summary>
        internal static string CASHABLE_EFT_IN {
            get {
                return ResourceManager.GetString("CASHABLE_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashable EFT Out (#).
        /// </summary>
        internal static string CASHABLE_EFT_OUT {
            get {
                return ResourceManager.GetString("CASHABLE_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Win (#).
        /// </summary>
        internal static string CASINO_WIN {
            get {
                return ResourceManager.GetString("CASINO_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits Wagered (#).
        /// </summary>
        internal static string CREDITS_WAGERED {
            get {
                return ResourceManager.GetString("CREDITS_WAGERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits Won (#).
        /// </summary>
        internal static string CREDITS_WON {
            get {
                return ResourceManager.GetString("CREDITS_WON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop (#).
        /// </summary>
        internal static string DROP {
            get {
                return ResourceManager.GetString("DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Bet.
        /// </summary>
        internal static string GAMES_BET {
            get {
                return ResourceManager.GetString("GAMES_BET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Lost.
        /// </summary>
        internal static string GAMES_LOST {
            get {
                return ResourceManager.GetString("GAMES_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Won.
        /// </summary>
        internal static string GAMES_WON {
            get {
                return ResourceManager.GetString("GAMES_WON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handpay (#).
        /// </summary>
        internal static string HANDPAY {
            get {
                return ResourceManager.GetString("HANDPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string HS_Date {
            get {
                return ResourceManager.GetString("HS_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24:00.
        /// </summary>
        internal static string HS_Hour {
            get {
                return ResourceManager.GetString("HS_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00 - 1:00.
        /// </summary>
        internal static string HS_Hour1 {
            get {
                return ResourceManager.GetString("HS_Hour1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00 - 10:00.
        /// </summary>
        internal static string HS_Hour10 {
            get {
                return ResourceManager.GetString("HS_Hour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00 - 11:00.
        /// </summary>
        internal static string HS_Hour11 {
            get {
                return ResourceManager.GetString("HS_Hour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11:00 - 12:00.
        /// </summary>
        internal static string HS_Hour12 {
            get {
                return ResourceManager.GetString("HS_Hour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 - 13:00.
        /// </summary>
        internal static string HS_Hour13 {
            get {
                return ResourceManager.GetString("HS_Hour13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13:00 - 14:00.
        /// </summary>
        internal static string HS_Hour14 {
            get {
                return ResourceManager.GetString("HS_Hour14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14:00 - 15:00.
        /// </summary>
        internal static string HS_Hour15 {
            get {
                return ResourceManager.GetString("HS_Hour15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15:00 - 16:00.
        /// </summary>
        internal static string HS_Hour16 {
            get {
                return ResourceManager.GetString("HS_Hour16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:00 - 17:00.
        /// </summary>
        internal static string HS_Hour17 {
            get {
                return ResourceManager.GetString("HS_Hour17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17:00 - 18:00.
        /// </summary>
        internal static string HS_Hour18 {
            get {
                return ResourceManager.GetString("HS_Hour18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18:00 - 19:00.
        /// </summary>
        internal static string HS_Hour19 {
            get {
                return ResourceManager.GetString("HS_Hour19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:00 - 2:00.
        /// </summary>
        internal static string HS_Hour2 {
            get {
                return ResourceManager.GetString("HS_Hour2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19:00 - 20:00.
        /// </summary>
        internal static string HS_Hour20 {
            get {
                return ResourceManager.GetString("HS_Hour20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20:00 - 21:00.
        /// </summary>
        internal static string HS_Hour21 {
            get {
                return ResourceManager.GetString("HS_Hour21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21:00 - 22:00.
        /// </summary>
        internal static string HS_Hour22 {
            get {
                return ResourceManager.GetString("HS_Hour22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22:00 - 23:00.
        /// </summary>
        internal static string HS_Hour23 {
            get {
                return ResourceManager.GetString("HS_Hour23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23:00 - 00:00.
        /// </summary>
        internal static string HS_Hour24 {
            get {
                return ResourceManager.GetString("HS_Hour24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:00 - 3:00.
        /// </summary>
        internal static string HS_Hour3 {
            get {
                return ResourceManager.GetString("HS_Hour3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:00 - 4:00.
        /// </summary>
        internal static string HS_Hour4 {
            get {
                return ResourceManager.GetString("HS_Hour4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:00 - 5:00.
        /// </summary>
        internal static string HS_Hour5 {
            get {
                return ResourceManager.GetString("HS_Hour5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5:00 - 6:00.
        /// </summary>
        internal static string HS_Hour6 {
            get {
                return ResourceManager.GetString("HS_Hour6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6:00 - 7:00.
        /// </summary>
        internal static string HS_Hour7 {
            get {
                return ResourceManager.GetString("HS_Hour7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7:00 - 8:00.
        /// </summary>
        internal static string HS_Hour8 {
            get {
                return ResourceManager.GetString("HS_Hour8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8:00 - 9:00.
        /// </summary>
        internal static string HS_Hour9 {
            get {
                return ResourceManager.GetString("HS_Hour9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackpot (#).
        /// </summary>
        internal static string JACKPOT {
            get {
                return ResourceManager.GetString("JACKPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Attendant Paid (#).
        /// </summary>
        internal static string MYSTERY_ATTENDANT_PAID {
            get {
                return ResourceManager.GetString("MYSTERY_ATTENDANT_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Machine Paid (#).
        /// </summary>
        internal static string MYSTERY_MACHINE_PAID {
            get {
                return ResourceManager.GetString("MYSTERY_MACHINE_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT In (#).
        /// </summary>
        internal static string NON_CASHABLE_EFT_IN {
            get {
                return ResourceManager.GetString("NON_CASHABLE_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCashable EFT Out (#).
        /// </summary>
        internal static string NON_CASHABLE_EFT_OUT {
            get {
                return ResourceManager.GetString("NON_CASHABLE_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Non Cashable Qty).
        /// </summary>
        internal static string NON_CASHABLE_VOUCHERS_IN_QTY {
            get {
                return ResourceManager.GetString("NON_CASHABLE_VOUCHERS_IN_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted (Non Cashable) (#).
        /// </summary>
        internal static string NON_CASHABLE_VOUCHERS_IN_VALUE {
            get {
                return ResourceManager.GetString("NON_CASHABLE_VOUCHERS_IN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (Non Cashable Qty).
        /// </summary>
        internal static string NON_CASHABLE_VOUCHERS_OUT_QTY {
            get {
                return ResourceManager.GetString("NON_CASHABLE_VOUCHERS_OUT_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed (Non Cashable) (#).
        /// </summary>
        internal static string NON_CASHABLE_VOUCHERS_OUT_VALUE {
            get {
                return ResourceManager.GetString("NON_CASHABLE_VOUCHERS_OUT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        internal static string OCCUPANCY {
            get {
                return ResourceManager.GetString("OCCUPANCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Handpay (#).
        /// </summary>
        internal static string PROGRESSIVE_HANDPAY {
            get {
                return ResourceManager.GetString("PROGRESSIVE_HANDPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Win (#).
        /// </summary>
        internal static string PROGRESSIVE_WIN {
            get {
                return ResourceManager.GetString("PROGRESSIVE_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT In (#).
        /// </summary>
        internal static string PROMO_CASHABLE_EFT_IN {
            get {
                return ResourceManager.GetString("PROMO_CASHABLE_EFT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Cashable EFT Out (#).
        /// </summary>
        internal static string PROMO_CASHABLE_EFT_OUT {
            get {
                return ResourceManager.GetString("PROMO_CASHABLE_EFT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted Quantity.
        /// </summary>
        internal static string TICKETS_INSERTED_QTY {
            get {
                return ResourceManager.GetString("TICKETS_INSERTED_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Inserted Value (#).
        /// </summary>
        internal static string TICKETS_INSERTED_VALUE {
            get {
                return ResourceManager.GetString("TICKETS_INSERTED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed Quantity.
        /// </summary>
        internal static string TICKETS_PRINTED_QTY {
            get {
                return ResourceManager.GetString("TICKETS_PRINTED_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Printed Value (#).
        /// </summary>
        internal static string TICKETS_PRINTED_VALUE {
            get {
                return ResourceManager.GetString("TICKETS_PRINTED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
