<?xml version="1.0" encoding="utf-8"?><Database Name="Exchange" Class="ExCommsSQLDataAccess" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=inchn-bmcbuild;Initial Catalog=Exchange;User ID=sa" SettingsObjectName="BMC.ExComms.DataLayer.Properties.Settings" SettingsPropertyName="ExchangeConnectionString" Provider="System.Data.SqlClient" />
</Database>