USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[COLINF_REJ]') AND name = N'COLINF_REJECT_ID')
DROP INDEX [COLINF_REJECT_ID] ON [dbo].[COLINF_REJ] WITH ( ONLINE = OFF )
GO

USE [Enterprise]
GO

CREATE UNIQUE NONCLUSTERED INDEX [COLINF_REJECT_ID] ON [dbo].[COLINF_REJ] 
(
	[COLINF_REJECT_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO

