USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Meter_history]') AND name = N'IX_Meter_history_Installation_No')
DROP INDEX [IX_Meter_history_Installation_No] ON [dbo].[Meter_history] WITH ( ONLINE = OFF )
GO

USE [Enterprise]
GO

CREATE NONCLUSTERED INDEX [IX_Meter_history_Installation_No] ON [dbo].[Meter_history] 
(
	[MH_Installation_No] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO

USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Meter_history]') AND name = N'IX_Meter_history_process_LinkReference')
DROP INDEX [IX_Meter_history_process_LinkReference] ON [dbo].[Meter_history] WITH ( ONLINE = OFF )
GO

USE [Enterprise]
GO

CREATE NONCLUSTERED INDEX [IX_Meter_history_process_LinkReference] ON [dbo].[Meter_history] 
(
	[MH_LinkReference] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO

USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Meter_history]') AND name = N'IX_Meter_history_process_Type')
DROP INDEX [IX_Meter_history_process_Type] ON [dbo].[Meter_history] WITH ( ONLINE = OFF )
GO

USE [Enterprise]
GO

CREATE NONCLUSTERED INDEX [IX_Meter_history_process_Type] ON [dbo].[Meter_history] 
(
	[MH_Process] ASC,
	[MH_Type] ASC
)
INCLUDE ( [MH_ID],
[MH_LinkReference],
[MH_Reference],
[MH_Installation_No],
[MH_PAYOUT_FLOAT_TOKEN],
[MH_PAYOUT_FLOAT_10P],
[MH_PAYOUT_FLOAT_20P],
[MH_PAYOUT_FLOAT_50P],
[MH_PAYOUT_FLOAT_100P],
[MH_CASH_IN_2P],
[MH_CASH_IN_5P],
[MH_CASH_IN_10P],
[MH_CASH_IN_20P],
[MH_CASH_IN_50P],
[MH_CASH_IN_100P],
[MH_CASH_IN_200P],
[MH_CASH_IN_500P],
[MH_CASH_IN_1000P],
[MH_CASH_IN_2000P],
[MH_CASH_IN_5000P],
[MH_CASH_IN_10000P],
[MH_CASH_IN_20000P],
[MH_CASH_IN_50000P],
[MH_CASH_IN_100000P],
[MH_TOKEN_IN_5P],
[MH_TOKEN_IN_10P],
[MH_TOKEN_IN_20P],
[MH_TOKEN_IN_50P],
[MH_TOKEN_IN_100P],
[MH_TOKEN_IN_200P],
[MH_TOKEN_IN_500P],
[MH_TOKEN_IN_1000P],
[MH_CASH_OUT_2P],
[MH_CASH_OUT_5P],
[MH_CASH_OUT_10P],
[MH_CASH_OUT_20P],
[MH_CASH_OUT_50P],
[MH_CASH_OUT_100P],
[MH_CASH_OUT_200P],
[MH_CASH_OUT_500P],
[MH_CASH_OUT_1000P],
[MH_CASH_OUT_2000P],
[MH_CASH_OUT_5000P],
[MH_CASH_OUT_10000P],
[MH_CASH_OUT_20000P],
[MH_CASH_OUT_50000P],
[MH_CASH_OUT_100000P],
[MH_TOKEN_OUT_5P],
[MH_TOKEN_OUT_10P],
[MH_TOKEN_OUT_20P],
[MH_TOKEN_OUT_50P],
[MH_TOKEN_OUT_100P],
[MH_TOKEN_OUT_200P],
[MH_TOKEN_OUT_500P],
[MH_TOKEN_OUT_1000P],
[MH_CASH_REFILL_5P],
[MH_CASH_REFILL_10P],
[MH_CASH_REFILL_20P],
[MH_CASH_REFILL_50P],
[MH_CASH_REFILL_100P],
[MH_CASH_REFILL_200P],
[MH_CASH_REFILL_500P],
[MH_CASH_REFILL_1000P],
[MH_CASH_REFILL_2000P],
[MH_CASH_REFILL_5000P],
[MH_CASH_REFILL_10000P],
[MH_CASH_REFILL_20000P],
[MH_CASH_REFILL_50000P],
[MH_CASH_REFILL_100000P],
[MH_TOKEN_REFILL_5P],
[MH_TOKEN_REFILL_10P],
[MH_TOKEN_REFILL_20P],
[MH_TOKEN_REFILL_50P],
[MH_TOKEN_REFILL_100P],
[MH_TOKEN_REFILL_200P],
[MH_TOKEN_REFILL_500P],
[MH_TOKEN_REFILL_1000P],
[MH_COINS_IN],
[MH_COINS_OUT],
[MH_COIN_DROP],
[MH_HANDPAY],
[MH_EXTERNAL_CREDIT],
[MH_GAMES_BET],
[MH_GAMES_WON],
[MH_NOTES],
[MH_VTP],
[MH_CANCELLED_CREDITS],
[MH_GAMES_LOST],
[MH_GAMES_SINCE_POWER_UP],
[MH_TRUE_COIN_IN],
[MH_TRUE_COIN_OUT],
[MH_CURRENT_CREDITS],
[MH_JACKPOT],
[MH_BILL_1],
[MH_BILL_2],
[MH_BILL_5],
[MH_BILL_10],
[MH_BILL_20],
[MH_BILL_50],
[MH_BILL_100],
[MH_BILL_250],
[MH_BILL_10000],
[MH_BILL_20000],
[MH_BILL_50000],
[MH_BILL_100000],
[MH_TICKET_PRINTED_QTY],
[MH_TICKET_PRINTED_VALUE],
[MH_TICKET_INSERTED_QTY],
[MH_TICKET_INSERTED_VALUE],
[MH_Datetime],
[MH_progressive_win_value],
[MH_progressive_win_Handpay_value],
[MH_Mystery_Machine_Paid],
[MH_Mystery_Attendant_Paid],
[MH_TICKETS_PRINTED_NONCASHABLE_QTY],
[MH_TICKETS_PRINTED_NONCASHABLE_VALUE],
[MH_TICKETS_INSERTED_NONCASHABLE_QTY],
[MH_TICKETS_INSERTED_NONCASHABLE_VALUE],
[MH_Promo_Cashable_EFT_IN],
[MH_Promo_Cashable_EFT_OUT],
[MH_NonCashable_EFT_IN],
[MH_NonCashable_EFT_OUT],
[MH_Cashable_EFT_IN],
[MH_Cashable_EFT_OUT],
[MH_BILL_200],
[MH_BILL_500]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


