USE [Enterprise]
GO

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MOVINF_REJ]') AND name = N'MOVINF_REJECT_ID')
DROP INDEX [MOVINF_REJECT_ID] ON [dbo].[MOVINF_REJ] WITH ( ONLINE = OFF )
GO

USE [Enterprise]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MOVINF_REJECT_ID] ON [dbo].[MOVINF_REJ] 
(
	[MOVINF_REJECT_ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO

